//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIResponder.h>

#import "UIApplicationDelegate-Protocol.h"

@class NSString, UIWindow;

@interface AppDelegate : UIResponder <UIApplicationDelegate>
{
    UIWindow *_window;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0000000100009e48
@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
- (void)application:(id)arg1 didDiscardSceneSessions:(id)arg2;	// IMP=0x0000000100009d74
- (id)application:(id)arg1 configurationForConnectingSceneSession:(id)arg2 options:(id)arg3;	// IMP=0x0000000100009c50
- (void)applicationWillTerminate:(id)arg1;	// IMP=0x0000000100009be0
- (void)applicationDidBecomeActive:(id)arg1;	// IMP=0x0000000100009b70
- (void)applicationWillEnterForeground:(id)arg1;	// IMP=0x0000000100009b00
- (void)applicationDidEnterBackground:(id)arg1;	// IMP=0x0000000100009a90
- (void)applicationWillResignActive:(id)arg1;	// IMP=0x0000000100009a20
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;	// IMP=0x00000001000099ac

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

