//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class LASecureData, NSMutableArray;
@protocol PinFieldDelegate;

@interface PinField : UIView
{
    NSMutableArray *_pinDashViews;	// 8 = 0x8
    NSMutableArray *_pinDotViews;	// 16 = 0x10
    struct CGSize _pinDashSize;	// 24 = 0x18
    struct CGSize _pinDotSize;	// 40 = 0x28
    double _slotHeight;	// 56 = 0x38
    double _slotWidth;	// 64 = 0x40
    id <PinFieldDelegate> _delegate;	// 72 = 0x48
    LASecureData *_pinValue;	// 80 = 0x50
    unsigned long long _pinLength;	// 88 = 0x58
}

- (void).cxx_destruct;	// IMP=0x000000010001758c
@property(readonly, nonatomic) unsigned long long pinLength; // @synthesize pinLength=_pinLength;
@property(readonly, nonatomic) LASecureData *pinValue; // @synthesize pinValue=_pinValue;
@property(nonatomic) __weak id <PinFieldDelegate> delegate; // @synthesize delegate=_delegate;
- (void)deleteLastPinCharacter;	// IMP=0x00000001000174d8
- (void)appendPinCharacter:(id)arg1;	// IMP=0x0000000100017364
- (void)layoutSubviews;	// IMP=0x00000001000171fc
- (void)updateLayoutForWidth:(double)arg1;	// IMP=0x0000000100016fa0
- (id)initWithPinLength:(id)arg1;	// IMP=0x0000000100016bdc

@end

