/*
* This header is generated by classdump-dyld 1.0
* on Sunday, September 27, 2020 at 11:52:43 AM Mountain Standard Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /usr/lib/libnfshared.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/NFAWDEventProtocol.h>

@class AWDNFCSERestrictedModeEnteredEvent, NSData, NSString;

@interface NFAWDSERestrictedModeEntered : NSObject <NFAWDEventProtocol> {

	unsigned _hardwareType;
	AWDNFCSERestrictedModeEnteredEvent* _metric;

}

@property (assign,nonatomic) unsigned hardwareType;                                    //@synthesize hardwareType=_hardwareType - In the implementation block
@property (assign,nonatomic) BOOL contactlessMode; 
@property (nonatomic,retain) NSData * restrictedModeID; 
@property (nonatomic,retain) NSString * platformIdentifier; 
@property (nonatomic,retain) NSData * attackLog; 
@property (nonatomic,retain) AWDNFCSERestrictedModeEnteredEvent * metric;              //@synthesize metric=_metric - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(unsigned)hardwareType;
-(void)setMetric:(AWDNFCSERestrictedModeEnteredEvent *)arg1 ;
-(AWDNFCSERestrictedModeEnteredEvent *)metric;
-(id)getMetric;
-(id)init;
-(NSString *)platformIdentifier;
-(unsigned)getMetricId;
-(void)setPlatformIdentifier:(NSString *)arg1 ;
-(void)setHardwareType:(unsigned)arg1 ;
-(void)setAttackLog:(NSData *)arg1 ;
-(NSData *)attackLog;
-(BOOL)contactlessMode;
-(void)setContactlessMode:(BOOL)arg1 ;
-(NSData *)restrictedModeID;
-(void)setRestrictedModeID:(NSData *)arg1 ;
@end

