//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "AbstractTimer-Protocol.h"

@class NSString;

@interface WakingTimer : NSObject <AbstractTimer>
{
    _Bool _invalidated;	// 8 = 0x8
    unsigned long long _startTime;	// 16 = 0x10
    unsigned long long _earliestFireTime;	// 24 = 0x18
    unsigned long long _deadline;	// 32 = 0x20
    NSString *_identifier;	// 40 = 0x28
    double _delay;	// 48 = 0x30
    double _gracePeriod;	// 56 = 0x38
    CDUnknownBlockType _handlerBlock;	// 64 = 0x40
}

- (void).cxx_destruct;	// IMP=0x000000010000cb68
@property(copy, nonatomic) CDUnknownBlockType handlerBlock; // @synthesize handlerBlock=_handlerBlock;
@property(nonatomic) double gracePeriod; // @synthesize gracePeriod=_gracePeriod;
@property(nonatomic) double delay; // @synthesize delay=_delay;
@property(retain, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(nonatomic, getter=isInvalidated) _Bool invalidated; // @synthesize invalidated=_invalidated;
@property(nonatomic) unsigned long long deadline; // @synthesize deadline=_deadline;
@property(nonatomic) unsigned long long earliestFireTime; // @synthesize earliestFireTime=_earliestFireTime;
@property(nonatomic) unsigned long long startTime; // @synthesize startTime=_startTime;
- (void)fireTimer;	// IMP=0x000000010000cac0
@property(readonly, nonatomic, getter=isWaking) _Bool waking;
- (void)invalidate;	// IMP=0x000000010000ca4c
- (void)dealloc;	// IMP=0x000000010000c9f4
- (id)initWithIdentifier:(id)arg1 delay:(double)arg2 gracePeriod:(double)arg3 handlerBlock:(CDUnknownBlockType)arg4;	// IMP=0x000000010000c900

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

