//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import "NSCopying-Protocol.h"

@class NSData;

@interface SDAutoUnlockAuthPromptImageData : PBCodable <NSCopying>
{
    NSData *_imageData;	// 8 = 0x8
    unsigned int _version;	// 16 = 0x10
    _Bool _finalMessage;	// 20 = 0x14
    struct {
        unsigned int version:1;
        unsigned int finalMessage:1;
    } _has;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00000001000e1a88
@property(nonatomic) _Bool finalMessage; // @synthesize finalMessage=_finalMessage;
@property(retain, nonatomic) NSData *imageData; // @synthesize imageData=_imageData;
@property(nonatomic) unsigned int version; // @synthesize version=_version;
- (void)mergeFrom:(id)arg1;	// IMP=0x00000001000e19a0
- (unsigned long long)hash;	// IMP=0x00000001000e190c
- (_Bool)isEqual:(id)arg1;	// IMP=0x00000001000e17f8
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001000e1724
- (void)copyTo:(id)arg1;	// IMP=0x00000001000e1680
- (void)writeTo:(id)arg1;	// IMP=0x00000001000e15e8
- (_Bool)readFrom:(id)arg1;	// IMP=0x00000001000e15e0
- (id)dictionaryRepresentation;	// IMP=0x00000001000e11a4
- (id)description;	// IMP=0x00000001000e10f0
@property(nonatomic) _Bool hasFinalMessage;
@property(readonly, nonatomic) _Bool hasImageData;
@property(nonatomic) _Bool hasVersion;

@end

