//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import "NSCopying-Protocol.h"

@class NSString;

@interface SDUnlockDisable : PBCodable <NSCopying>
{
    NSString *_pairingID;	// 8 = 0x8
    unsigned int _version;	// 16 = 0x10
    CDStruct_f20694ce _has;	// 20 = 0x14
}

- (void).cxx_destruct;	// IMP=0x00000001000f5a28
@property(retain, nonatomic) NSString *pairingID; // @synthesize pairingID=_pairingID;
@property(nonatomic) unsigned int version; // @synthesize version=_version;
- (void)mergeFrom:(id)arg1;	// IMP=0x00000001000f597c
- (unsigned long long)hash;	// IMP=0x00000001000f5918
- (_Bool)isEqual:(id)arg1;	// IMP=0x00000001000f5840
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001000f5798
- (void)copyTo:(id)arg1;	// IMP=0x00000001000f5720
- (void)writeTo:(id)arg1;	// IMP=0x00000001000f56b0
- (_Bool)readFrom:(id)arg1;	// IMP=0x00000001000f56a8
- (id)dictionaryRepresentation;	// IMP=0x00000001000f5384
- (id)description;	// IMP=0x00000001000f52d0
@property(readonly, nonatomic) _Bool hasPairingID;
@property(nonatomic) _Bool hasVersion;

@end

