//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSSecureCoding-Protocol.h"

@protocol APContentDataTransientDelegate;

@interface APContentDataTransient : NSObject <NSSecureCoding>
{
    _Bool _playbackInProgress;	// 8 = 0x8
    _Bool _isVisible;	// 9 = 0x9
    _Bool _hasImpressed;	// 10 = 0xa
    _Bool _hasConfirmedClick;	// 11 = 0xb
    int _impressionSequenceNumber;	// 12 = 0xc
    int _videoEventSequence;	// 16 = 0x10
    int _clickCount;	// 20 = 0x14
    id <APContentDataTransientDelegate> _delegate;	// 24 = 0x18
    double _initialVisibleTime;	// 32 = 0x20
    double _clickTime;	// 40 = 0x28
    double _overImpressionThresholdTime;	// 48 = 0x30
    double _accumulatedPlaybackTime;	// 56 = 0x38
    double _playbackStartTime;	// 64 = 0x40
    double _duration;	// 72 = 0x48
    double _lastPosition;	// 80 = 0x50
    double _volume;	// 88 = 0x58
    CDStruct_34734122 _clickLocation;	// 96 = 0x60
}

+ (_Bool)supportsSecureCoding;	// IMP=0x0000000100062810
- (void).cxx_destruct;	// IMP=0x00000001000630dc
@property CDStruct_c3b9c2ee clickLocation; // @synthesize clickLocation=_clickLocation;
@property int clickCount; // @synthesize clickCount=_clickCount;
@property _Bool hasConfirmedClick; // @synthesize hasConfirmedClick=_hasConfirmedClick;
@property _Bool hasImpressed; // @synthesize hasImpressed=_hasImpressed;
@property _Bool isVisible; // @synthesize isVisible=_isVisible;
@property int videoEventSequence; // @synthesize videoEventSequence=_videoEventSequence;
@property double volume; // @synthesize volume=_volume;
@property double lastPosition; // @synthesize lastPosition=_lastPosition;
@property double duration; // @synthesize duration=_duration;
@property _Bool playbackInProgress; // @synthesize playbackInProgress=_playbackInProgress;
@property double playbackStartTime; // @synthesize playbackStartTime=_playbackStartTime;
@property double accumulatedPlaybackTime; // @synthesize accumulatedPlaybackTime=_accumulatedPlaybackTime;
@property double overImpressionThresholdTime; // @synthesize overImpressionThresholdTime=_overImpressionThresholdTime;
@property double clickTime; // @synthesize clickTime=_clickTime;
@property double initialVisibleTime; // @synthesize initialVisibleTime=_initialVisibleTime;
@property(nonatomic) __weak id <APContentDataTransientDelegate> delegate; // @synthesize delegate=_delegate;
@property int impressionSequenceNumber; // @synthesize impressionSequenceNumber=_impressionSequenceNumber;
- (void)save;	// IMP=0x0000000100062ed0
- (void)updateAccumulatedPlaybackTime:(double)arg1;	// IMP=0x0000000100062d1c
- (void)incrementVideoEventSequence;	// IMP=0x0000000100062d0c
- (void)encodeWithCoder:(id)arg1;	// IMP=0x0000000100062a30
- (id)initWithCoder:(id)arg1;	// IMP=0x0000000100062818

@end

