//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData;

@interface APCryptor : NSObject
{
    _Bool _verbose;	// 8 = 0x8
    int _status;	// 12 = 0xc
    NSData *_initializationVector;	// 16 = 0x10
    struct _CCCryptor *_cryptor;	// 24 = 0x18
    unsigned long long _nextOffset;	// 32 = 0x20
}

+ (unsigned int)predictedEncodedLength:(unsigned int)arg1;	// IMP=0x000000010005c0c0
+ (id)constructAKey;	// IMP=0x000000010005bf9c
+ (id)_keyFromSeed:(id)arg1;	// IMP=0x000000010005be2c
+ (void)removeSeed;	// IMP=0x000000010005be0c
+ (id)fetchSeed;	// IMP=0x000000010005bcec
+ (void)storeSeed:(id)arg1;	// IMP=0x000000010005bcd0
+ (id)constructSeed;	// IMP=0x000000010005bc88
+ (id)encryptionKey;	// IMP=0x000000010005b45c
- (void).cxx_destruct;	// IMP=0x000000010005c110
@property(nonatomic) _Bool verbose; // @synthesize verbose=_verbose;
@property(nonatomic) unsigned long long nextOffset; // @synthesize nextOffset=_nextOffset;
@property(nonatomic) struct _CCCryptor *cryptor; // @synthesize cryptor=_cryptor;
@property(nonatomic) int status; // @synthesize status=_status;
@property(copy, nonatomic) NSData *initializationVector; // @synthesize initializationVector=_initializationVector;
- (id)constructIV;	// IMP=0x000000010005c044
- (id)cryptFinal;	// IMP=0x000000010005bbdc
- (id)cryptChunkOfData:(id)arg1;	// IMP=0x000000010005b990
- (id)_cryptData:(id)arg1;	// IMP=0x000000010005b7f8
- (id)decryptData:(id)arg1;	// IMP=0x000000010005b7ec
- (id)encryptData:(id)arg1;	// IMP=0x000000010005b7e0
- (void)dealloc;	// IMP=0x000000010005b6e8
- (void)_commonInitForOperation:(unsigned int)arg1;	// IMP=0x000000010005b618
- (id)initForDecodingWithInitializationVector:(id)arg1;	// IMP=0x000000010005b58c
- (id)initForEncoding;	// IMP=0x000000010005b508

@end

