//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "APSettings.h"

@class NSData;

@interface APMescalSigningSettings : APSettings
{
}

+ (id)storageWithDefaultValues:(id)arg1;	// IMP=0x000000010003f508

// Remaining properties
@property(retain) NSData *cachedCertificate; // @dynamic cachedCertificate;

@end

