//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBRequest.h>

#import "NSCopying-Protocol.h"

@class NSData, NSMutableArray;

@interface APPBConfigurationRequest : PBRequest <NSCopying>
{
    NSMutableArray *_currentConfigurations;	// 8 = 0x8
    NSData *_iAdID;	// 16 = 0x10
}

+ (Class)currentConfigurationType;	// IMP=0x000000010006d0ac
+ (id)options;	// IMP=0x000000010006cf98
- (void).cxx_destruct;	// IMP=0x000000010006dc7c
@property(retain, nonatomic) NSData *iAdID; // @synthesize iAdID=_iAdID;
@property(retain, nonatomic) NSMutableArray *currentConfigurations; // @synthesize currentConfigurations=_currentConfigurations;
- (void)mergeFrom:(id)arg1;	// IMP=0x000000010006dad8
- (unsigned long long)hash;	// IMP=0x000000010006da7c
- (_Bool)isEqual:(id)arg1;	// IMP=0x000000010006d9a8
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x000000010006d7fc
- (void)copyTo:(id)arg1;	// IMP=0x000000010006d708
- (void)writeTo:(id)arg1;	// IMP=0x000000010006d5c0
- (_Bool)readFrom:(id)arg1;	// IMP=0x000000010006d5b8
- (id)dictionaryRepresentation;	// IMP=0x000000010006d184
- (id)description;	// IMP=0x000000010006d0d0
@property(readonly, nonatomic) _Bool hasIAdID;
- (id)currentConfigurationAtIndex:(unsigned long long)arg1;	// IMP=0x000000010006d094
- (unsigned long long)currentConfigurationsCount;	// IMP=0x000000010006d07c
- (void)addCurrentConfiguration:(id)arg1;	// IMP=0x000000010006d008
- (void)clearCurrentConfigurations;	// IMP=0x000000010006cff0

@end

