/*
* This header is generated by classdump-dyld 1.0
* on Sunday, September 27, 2020 at 12:32:54 PM Mountain Standard Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /usr/lib/libSLAMDynamic.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface SLAMObjC : NSObject
+(id)PerformScript:(unsigned long long)arg1 seHandle:(id)arg2 logSink:(id)arg3 ;
+(id)PerformRecovery:(id)arg1 logSink:(id)arg2 ;
+(id)PerformScript:(unsigned long long)arg1 sefwPath:(id)arg2 seHandle:(id)arg3 logSink:(id)arg4 ;
@end

