//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "CLLocationManagerDelegate-Protocol.h"

@class CLLocationManager, NSDate, NSNumber, NSString;

__attribute__((visibility("hidden")))
@interface XxyDq1mpwtvCuJnm : NSObject <CLLocationManagerDelegate>
{
    int _YGGzx6XAo42A7s6x;	// 8 = 0x8
    CLLocationManager *_N8Azi3NI6QrNPsLP;	// 16 = 0x10
    NSNumber *_yABQBiEYyLNkt6IY;	// 24 = 0x18
    NSNumber *_kp3LsdVLlXwFNqJV;	// 32 = 0x20
    double _Msur5CGmk1XEBjLD;	// 40 = 0x28
    double _zDlKxUFITTJsP8iN;	// 48 = 0x30
    NSDate *_LUsBOf3PLbri6v6o;	// 56 = 0x38
}

+ (id)sharedInstance;	// IMP=0x000000010000f974
+ (void)x7PkBasAKbApbiZS:(struct _KUwyEjpVZR65eUyl *)arg1;	// IMP=0x000000010000f560
- (void).cxx_destruct;	// IMP=0x0000000100010b58
@property(retain) NSDate *LUsBOf3PLbri6v6o; // @synthesize LUsBOf3PLbri6v6o=_LUsBOf3PLbri6v6o;
@property double zDlKxUFITTJsP8iN; // @synthesize zDlKxUFITTJsP8iN=_zDlKxUFITTJsP8iN;
@property double Msur5CGmk1XEBjLD; // @synthesize Msur5CGmk1XEBjLD=_Msur5CGmk1XEBjLD;
@property(retain, nonatomic) NSNumber *kp3LsdVLlXwFNqJV; // @synthesize kp3LsdVLlXwFNqJV=_kp3LsdVLlXwFNqJV;
@property(retain, nonatomic) NSNumber *yABQBiEYyLNkt6IY; // @synthesize yABQBiEYyLNkt6IY=_yABQBiEYyLNkt6IY;
@property int YGGzx6XAo42A7s6x; // @synthesize YGGzx6XAo42A7s6x=_YGGzx6XAo42A7s6x;
@property(retain) CLLocationManager *N8Azi3NI6QrNPsLP; // @synthesize N8Azi3NI6QrNPsLP=_N8Azi3NI6QrNPsLP;
- (void)locationManager:(id)arg1 didChangeAuthorizationStatus:(int)arg2;	// IMP=0x0000000100010ac0
- (void)locationManager:(id)arg1 didFailWithError:(id)arg2;	// IMP=0x0000000100010a90
- (void)locationManager:(id)arg1 didUpdateLocations:(id)arg2;	// IMP=0x0000000100010884
- (void)initLocationManager:(id)arg1 dko5Pwm7el1Ulopu:(double)arg2;	// IMP=0x00000001000105f8
- (void)UupMWO2j2nYek7xf:(CDUnknownBlockType)arg1 exi2C8VfynTXu5cU:(struct _KUwyEjpVZR65eUyl *)arg2 TYPlhTGwKuAdWgfx:(id)arg3;	// IMP=0x000000010000fa38
- (_Bool)SNfHoVX7xML3tdWp;	// IMP=0x000000010000fa24
- (_Bool)LjU00AjDrcTJbVJD;	// IMP=0x000000010000fa14

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

