//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData, NSDictionary;
@protocol OS_xpc_object;

@interface MSDF200Message : NSObject
{
    unsigned char _command;	// 8 = 0x8
    unsigned char _type;	// 9 = 0x9
    NSData *_payload;	// 16 = 0x10
    NSDictionary *_payloadDict;	// 24 = 0x18
    NSObject<OS_xpc_object> *_xpcRequest;	// 32 = 0x20
    unsigned long long _timeout;	// 40 = 0x28
    CDUnknownBlockType _timeoutHandler;	// 48 = 0x30
}

+ (id)messageFromPacketData:(id)arg1;	// IMP=0x0000000100009198
+ (id)messageWithCommand:(unsigned char)arg1 messageType:(unsigned char)arg2 payloadData:(id)arg3 fromXPCRequest:(id)arg4;	// IMP=0x0000000100008d6c
+ (id)messageReplyForCommand:(unsigned char)arg1 payloadData:(id)arg2;	// IMP=0x0000000100008d4c
+ (id)messageWithOneWayCommand:(unsigned char)arg1 payloadData:(id)arg2;	// IMP=0x0000000100008d2c
+ (id)messageWithCommand:(unsigned char)arg1 payloadData:(id)arg2 fromXPCRequest:(id)arg3;	// IMP=0x0000000100008cbc
- (void).cxx_destruct;	// IMP=0x000000010000a294
@property(copy, nonatomic) CDUnknownBlockType timeoutHandler; // @synthesize timeoutHandler=_timeoutHandler;
@property unsigned long long timeout; // @synthesize timeout=_timeout;
@property(retain, nonatomic) NSObject<OS_xpc_object> *xpcRequest; // @synthesize xpcRequest=_xpcRequest;
@property(retain, nonatomic) NSDictionary *payloadDict; // @synthesize payloadDict=_payloadDict;
@property(retain, nonatomic) NSData *payload; // @synthesize payload=_payload;
@property unsigned char type; // @synthesize type=_type;
@property unsigned char command; // @synthesize command=_command;
- (_Bool)resolveMessageTypeBasedOnCommandAndPayload;	// IMP=0x000000010000a014
- (_Bool)insertMessageIdToPayloadDict;	// IMP=0x0000000100009e28
- (id)errorFromDictionaryPayload;	// IMP=0x0000000100009cd0
- (id)dictionaryFromPayloadData;	// IMP=0x0000000100009c6c
- (id)stringFromPayloadData;	// IMP=0x0000000100009bfc
- (_Bool)runReplyMatchCheckAgainstMessage:(id)arg1;	// IMP=0x0000000100009a14
- (void)invalidateTimeoutHandler;	// IMP=0x0000000100009988
- (void)scheduleTimeoutHandler:(CDUnknownBlockType)arg1 inQueue:(id)arg2;	// IMP=0x00000001000098c0
- (id)formulatePacketData;	// IMP=0x00000001000095ac

@end

