//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSMutableArray.h>

@interface NSMutableArray (AluminiumAuthenticator)
- (_Bool)_addHMACComponent:(id)arg1 error:(id *)arg2;	// IMP=0x00000001000615d0
@end

