//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface KmlClientReporterFactory : NSObject
{
}

+ (void)removeTestReporter;	// IMP=0x0000000100053084
+ (id)getTestReporter;	// IMP=0x0000000100053024
+ (id)getReporter;	// IMP=0x0000000100052fd0

@end

