//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SLAMLogSink-Protocol.h"
#import "SLAMSEHandle-Protocol.h"
#import "SecureElement-Protocol.h"

@class NSData, RAPDU;
@protocol OS_dispatch_queue, SecureElementTransceiver;

@interface SecureElementImpl : NSObject <SLAMSEHandle, SLAMLogSink, SecureElement>
{
    NSData *_currentSelectedAID;	// 8 = 0x8
    RAPDU *_currentSelectedAIDRapdu;	// 16 = 0x10
    _Bool _isProd;	// 24 = 0x18
    NSData *_seid;	// 32 = 0x20
    NSData *_casdCertificate;	// 40 = 0x28
    NSData *_casdCertificateRSA;	// 48 = 0x30
    NSObject<OS_dispatch_queue> *_queue;	// 56 = 0x38
    id <SecureElementTransceiver> _transceiver;	// 64 = 0x40
}

- (void).cxx_destruct;	// IMP=0x000000010002f578
@property(readonly) _Bool isProd; // @synthesize isProd=_isProd;
@property(readonly) NSData *casdCertificateRSA; // @synthesize casdCertificateRSA=_casdCertificateRSA;
@property(readonly) NSData *casdCertificate; // @synthesize casdCertificate=_casdCertificate;
@property(readonly) NSData *seid; // @synthesize seid=_seid;
- (id)performSLAM:(unsigned long long)arg1;	// IMP=0x000000010002f418
- (id)slamApplets:(_Bool)arg1 scriptWasPerformed:(_Bool *)arg2;	// IMP=0x000000010002f2fc
- (id)transceiveAndCheckSW:(id)arg1 outError:(id *)arg2;	// IMP=0x000000010002f140
- (id)transceiveExtAndCheckSW:(unsigned char)arg1 ins:(unsigned char)arg2 p1:(unsigned char)arg3 p2:(unsigned char)arg4 cData:(id)arg5 Le:(unsigned short)arg6 outError:(id *)arg7;	// IMP=0x000000010002ee28
- (id)transceiveAndCheckSW:(unsigned char)arg1 ins:(unsigned char)arg2 p1:(unsigned char)arg3 p2:(unsigned char)arg4 capdu:(id)arg5 Le:(unsigned char)arg6 outError:(id *)arg7;	// IMP=0x000000010002eb1c
- (id)selectAID:(id)arg1 outRAPDU:(id *)arg2;	// IMP=0x000000010002e514
- (id)selectAID:(id)arg1;	// IMP=0x000000010002e3a0
- (id)transceive:(id)arg1 error:(id *)arg2;	// IMP=0x000000010002e330
- (void)log:(id)arg1;	// IMP=0x000000010000d4a8

@end

