//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSData;

@interface SESTLV : NSObject
{
    unsigned int _tag;	// 8 = 0x8
    NSData *_value;	// 16 = 0x10
    NSArray *_children;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x0000000100082a1c
- (id)description;	// IMP=0x0000000100082208

@end

