//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, PHBottomBar, UIImage;

@protocol PHBottomBarDelegateProtocol <NSObject>

@optional
- (_Bool)shouldShowUseRTT;
- (_Bool)shouldShowAnswerRTT;
- (_Bool)shouldShowHardPauseNumbers;
- (_Bool)shouldShowActionTypeEffects;
- (_Bool)shouldShowActionTypePhotoCapture;
- (_Bool)shouldShowActionTypePunchOut;
- (_Bool)shouldShowActionTypeSendToVoicemail;
- (_Bool)shouldShowActionTypeAudioRoute;
- (_Bool)shouldShowActionTypeCameraFlip;
- (long long)bottomBarCallStateInBar:(PHBottomBar *)arg1;
- (UIImage *)imageForItemInBar:(PHBottomBar *)arg1 withActionType:(long long)arg2;
- (NSString *)customizedTitleForItemInBar:(PHBottomBar *)arg1 withActionType:(long long)arg2;
- (void)bottomBarActionPerformed:(long long)arg1 withCompletionState:(long long)arg2 fromBar:(PHBottomBar *)arg3;
- (void)sliderActionFromBar:(PHBottomBar *)arg1 slidToProportion:(float)arg2;
@end

