//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "PHHandsetDialerLCDView.h"

@class PHTextCycleLabel;

@interface PHEmergencyHandsetDialerLCDView : PHHandsetDialerLCDView
{
    PHTextCycleLabel *_emergencyTitleLabel;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x000000010009b654
@property(readonly) PHTextCycleLabel *emergencyTitleLabel; // @synthesize emergencyTitleLabel=_emergencyTitleLabel;
- (_Bool)shrinkLabelWhenNumbersEntered;	// IMP=0x000000010009b618
- (double)_emergencyDialerFontSize;	// IMP=0x000000010009b5d0
- (void)deleteCharacter;	// IMP=0x000000010009b580
- (void)setText:(id)arg1 needsFormat:(_Bool)arg2;	// IMP=0x000000010009b530
- (void)setText:(id)arg1 needsFormat:(_Bool)arg2 name:(id)arg3 label:(id)arg4;	// IMP=0x000000010009b48c
- (void)_updateEmergencyLabel;	// IMP=0x000000010009b248
- (_Bool)textFieldShouldBeginEditing:(id)arg1;	// IMP=0x000000010009b240
- (void)_applyLayoutConstraints;	// IMP=0x000000010009ade8
- (void)updateNumberLabelHorizontalConstraints;	// IMP=0x000000010009ade4
- (void)applyLayoutConstraints;	// IMP=0x000000010009ade0
- (id)newAddContactButton;	// IMP=0x000000010009add8
- (id)initWithFrame:(struct CGRect)arg1 forDialerType:(int)arg2;	// IMP=0x000000010009aa10

@end

