//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "PHAbstractCallParticipantLabelView.h"

@class NSArray, NSLayoutConstraint, TPBadgeView, UIActivityIndicatorView, UIButton, UILabel;

@interface PHMultipleCallParticipantLabelView : PHAbstractCallParticipantLabelView
{
    NSLayoutConstraint *_participantMarqueeLabelRightConstraint;	// 8 = 0x8
    UILabel *_statusLabel;	// 16 = 0x10
    NSLayoutConstraint *_statusLabelRightConstraint;	// 24 = 0x18
    UIActivityIndicatorView *_progressSpinner;	// 32 = 0x20
    UIButton *_conferenceParticipantsButton;	// 40 = 0x28
    TPBadgeView *_badgeView;	// 48 = 0x30
    NSArray *_badgeViewHiddenLayoutConstraints;	// 56 = 0x38
    NSArray *_badgeViewVisibleLayoutConstraints;	// 64 = 0x40
}

- (void).cxx_destruct;	// IMP=0x0000000100026d28
@property(readonly, copy) NSArray *badgeViewVisibleLayoutConstraints; // @synthesize badgeViewVisibleLayoutConstraints=_badgeViewVisibleLayoutConstraints;
@property(readonly, copy) NSArray *badgeViewHiddenLayoutConstraints; // @synthesize badgeViewHiddenLayoutConstraints=_badgeViewHiddenLayoutConstraints;
@property(retain) TPBadgeView *badgeView; // @synthesize badgeView=_badgeView;
@property(retain) UIButton *conferenceParticipantsButton; // @synthesize conferenceParticipantsButton=_conferenceParticipantsButton;
@property(retain) UIActivityIndicatorView *progressSpinner; // @synthesize progressSpinner=_progressSpinner;
@property(retain) NSLayoutConstraint *statusLabelRightConstraint; // @synthesize statusLabelRightConstraint=_statusLabelRightConstraint;
@property(retain) UILabel *statusLabel; // @synthesize statusLabel=_statusLabel;
@property(retain) NSLayoutConstraint *participantMarqueeLabelRightConstraint; // @synthesize participantMarqueeLabelRightConstraint=_participantMarqueeLabelRightConstraint;
- (void)infoButtonTapped:(id)arg1;	// IMP=0x0000000100026c18
- (void)setShowsInfoButton:(_Bool)arg1;	// IMP=0x00000001000268c8
- (void)setHidesLabel:(_Bool)arg1;	// IMP=0x000000010002682c
- (double)labelAlphaValueForActivityState:(unsigned short)arg1;	// IMP=0x0000000100026818
- (void)setActivityState:(unsigned short)arg1 animated:(_Bool)arg2;	// IMP=0x00000001000265d0
- (void)setActivityState:(unsigned short)arg1;	// IMP=0x00000001000265c0
- (void)setTextColor:(id)arg1;	// IMP=0x0000000100026544
- (void)setShowsActivitySpinner:(_Bool)arg1;	// IMP=0x0000000100026258
- (void)setLabelDescriptor:(id)arg1;	// IMP=0x0000000100025ff4
- (void)dealloc;	// IMP=0x0000000100025f7c
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100025728

@end

