//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@interface PHSOSNumberTableViewCell : UITableViewCell
{
}

- (void)populate:(id)arg1;	// IMP=0x000000010005e8c0
- (void)commonInit;	// IMP=0x000000010005e68c
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;	// IMP=0x000000010005e630

@end

