//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSArray, NSString, UILabel, UITableView;
@protocol PHSOSNumbersViewControllerDelegate;

@interface PHSOSNumbersViewController : UIViewController <UITableViewDelegate, UITableViewDataSource>
{
    id <PHSOSNumbersViewControllerDelegate> _delegate;	// 8 = 0x8
    UILabel *_titleLabel;	// 16 = 0x10
    UITableView *_tableView;	// 24 = 0x18
    NSArray *_sosHandles;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x0000000100076d88
@property(retain, nonatomic) NSArray *sosHandles; // @synthesize sosHandles=_sosHandles;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak id <PHSOSNumbersViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;	// IMP=0x0000000100076c78
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x0000000100076b34
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;	// IMP=0x0000000100076ae8
- (_Bool)_canShowWhileLocked;	// IMP=0x0000000100076ae0
- (void)updateSOSHandles:(id)arg1;	// IMP=0x0000000100076a6c
- (void)setUpConstraints;	// IMP=0x0000000100076458
- (void)didReceiveMemoryWarning;	// IMP=0x0000000100076424
- (void)viewDidLoad;	// IMP=0x0000000100075ed8
- (id)initWithSOSHandles:(id)arg1;	// IMP=0x0000000100075e58

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

