//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NDTActivity, NSObject;
@protocol OS_xpc_object;

@protocol NDTActiviityDelegate <NSObject>
- (char *)activitySubsystem:(NDTActivity *)arg1;
- (char *)activityIdentifier:(NDTActivity *)arg1;
- (void)activityRun:(NDTActivity *)arg1;

@optional
- (void)activity:(NDTActivity *)arg1 customizeCriteria:(NSObject<OS_xpc_object> *)arg2;
@end

