//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SYChange-Protocol.h"

@class NEKCalendarAttributes, NEKSourceID, NSString;

@interface NEKCalendarWrapper : NSObject <SYChange>
{
    _Bool _isDefaultTaskCalendar;	// 8 = 0x8
    _Bool _isDefaultEventCalendar;	// 9 = 0x9
    NEKSourceID *_storeIdentifier;	// 16 = 0x10
    NSString *_calendarIdentifier;	// 24 = 0x18
    NSString *_oldCalendarIdentifier;	// 32 = 0x20
    NEKCalendarAttributes *_attributes;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x0000000100005ae4
@property(nonatomic) _Bool isDefaultEventCalendar; // @synthesize isDefaultEventCalendar=_isDefaultEventCalendar;
@property(nonatomic) _Bool isDefaultTaskCalendar; // @synthesize isDefaultTaskCalendar=_isDefaultTaskCalendar;
@property(readonly, nonatomic) NEKCalendarAttributes *attributes; // @synthesize attributes=_attributes;
@property(retain, nonatomic) NSString *oldCalendarIdentifier; // @synthesize oldCalendarIdentifier=_oldCalendarIdentifier;
@property(retain, nonatomic) NSString *calendarIdentifier; // @synthesize calendarIdentifier=_calendarIdentifier;
@property(readonly, nonatomic) NEKSourceID *storeIdentifier; // @synthesize storeIdentifier=_storeIdentifier;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) long long changeType;
@property(readonly, nonatomic) NSString *sequencer;
@property(readonly, nonatomic) NSString *objectIdentifier;
- (id)initWithSourceIdentifier:(id)arg1 attributes:(id)arg2 calendarIdentifier:(id)arg3;	// IMP=0x0000000100005890
- (id)initWithList:(id)arg1;	// IMP=0x000000010003c808
- (id)initWithList:(id)arg1 useAttributes:(_Bool)arg2;	// IMP=0x000000010003c688
- (id)initWithCalendarRef:(id)arg1;	// IMP=0x000000010006f368
- (id)initWithCalendarRef:(id)arg1 useAttributes:(_Bool)arg2;	// IMP=0x000000010006f230

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

