//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class ACAccountStore;

@interface FMDAppleAccountManager : NSObject
{
    ACAccountStore *_accountStore;	// 8 = 0x8
}

+ (id)sharedInstance;	// IMP=0x0000000100040b2c
- (void).cxx_destruct;	// IMP=0x0000000100042218
@property(retain, nonatomic) ACAccountStore *accountStore; // @synthesize accountStore=_accountStore;
- (void)setFMIPDataclass:(_Bool)arg1;	// IMP=0x0000000100041ff4
- (void)fixFMIPAuthTokenShouldForce:(_Bool)arg1;	// IMP=0x0000000100041974
- (void)forceUserAuthForiCloudAccountForApp:(id)arg1 message:(id)arg2 really:(_Bool)arg3 withCompletion:(CDUnknownBlockType)arg4;	// IMP=0x0000000100041524
- (_Bool)populateiCloudAccountInfoIntoAccount:(id)arg1;	// IMP=0x00000001000413dc
- (id)_currentFMDFMIPAccount;	// IMP=0x0000000100041380
- (_Bool)isKnownFMIPAccount:(id)arg1;	// IMP=0x00000001000412bc
- (id)fmipACAccount;	// IMP=0x0000000100041258
- (id)iCloudACAccount;	// IMP=0x0000000100041204
- (void)syncFMIPAccountInfo;	// IMP=0x0000000100040da4
- (void)dealloc;	// IMP=0x0000000100040d20
- (id)initSingleton;	// IMP=0x0000000100040c9c
- (id)init;	// IMP=0x0000000100040c44

@end

