//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "FMDBluetoothDeviceDiscovering-Protocol.h"

@class NSDate, NSString, NSUUID;
@protocol FMDBluetoothDiscoveryTokenDelegate;

@interface FMDBluetoothDiscoveryToken : NSObject <FMDBluetoothDeviceDiscovering>
{
    CDUnknownBlockType _tokenDiscoveryEnded;	// 8 = 0x8
    NSObject<FMDBluetoothDiscoveryTokenDelegate> *_delegate;	// 16 = 0x10
    NSDate *_endDate;	// 24 = 0x18
    NSUUID *_uuid;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x00000001000078c8
@property(retain, nonatomic) NSUUID *uuid; // @synthesize uuid=_uuid;
@property(retain, nonatomic) NSDate *endDate; // @synthesize endDate=_endDate;
@property(nonatomic) __weak NSObject<FMDBluetoothDiscoveryTokenDelegate> *delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) CDUnknownBlockType tokenDiscoveryEnded; // @synthesize tokenDiscoveryEnded=_tokenDiscoveryEnded;
@property(readonly) unsigned long long hash;
- (_Bool)isEqual:(id)arg1;	// IMP=0x000000010000776c
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) _Bool isDiscoveryActive;
- (void)stopDiscovery;	// IMP=0x00000001000075f0
- (void)startDiscoveryForDuration:(double)arg1;	// IMP=0x0000000100007544
- (id)init;	// IMP=0x00000001000074c0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

