//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface FMDBluetoothFrameworkBTManagingFactory : NSObject
{
}

+ (id)bluetoothManagerWithQueue:(id)arg1 delegate:(id)arg2;	// IMP=0x00000001000a68d0
+ (_Bool)isAutomationActive;	// IMP=0x00000001000a6780

@end

