//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"
#import "NSSecureCoding-Protocol.h"

@class NSString;

@protocol FMDBluetoothFrameworkDevice <NSObject, NSSecureCoding>
@property(readonly, nonatomic) NSString *address;
@property(readonly, nonatomic) NSString *name;
- (_Bool)isTemporaryPaired;
- (_Bool)connected;
- (unsigned int)productId;
- (unsigned int)vendorId;
- (NSString *)scoUID;
- (unsigned int)minorClass;
- (unsigned int)majorClass;
@end

