//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSData, NSNumber, NSSet, NSString;
@protocol FMDCodable, FMDDecoderFactory;

@protocol FMDDecoder <NSObject>
+ (id)decodeCollectionClass:(Class)arg1 fromData:(NSData *)arg2 usingObjectKeyType:(NSString *)arg3 forObjectClass:(Class)arg4 error:(id *)arg5;
+ (id)decodeObjectOfClass:(Class)arg1 fromData:(NSData *)arg2 usingFactory:(id <FMDDecoderFactory>)arg3 error:(id *)arg4;
+ (id)decodeObjectOfClass:(Class)arg1 fromData:(NSData *)arg2 error:(id *)arg3;
- (id)decodeCollectionOfClass:(Class)arg1 usingFactory:(id <FMDDecoderFactory>)arg2 forKey:(NSString *)arg3 error:(id *)arg4;
- (id)decodeObjectOfProtocols:(NSSet *)arg1 forKey:(NSString *)arg2 error:(id *)arg3;
- (id <FMDCodable>)decodeObjectOfClass:(Class)arg1 forKey:(NSString *)arg2 error:(id *)arg3;
- (NSNumber *)decodeNumberForKey:(NSString *)arg1;
- (NSString *)decodeStringForKey:(NSString *)arg1;
- (double)decodeDoubleForKey:(NSString *)arg1;
- (float)decodeFloatForKey:(NSString *)arg1;
- (unsigned long long)decodeUnsignedIntegerForKey:(NSString *)arg1;
- (long long)decodeIntegerForKey:(NSString *)arg1;
- (_Bool)decodeBoolForKey:(NSString *)arg1;
- (_Bool)containsValueForKey:(NSString *)arg1;
@end

