//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class CADisplayLink, CMMotionManager, UIImageView;

@interface SRCompactDeviceMotionEffectView : UIView
{
    UIImageView *_effectImageView;	// 8 = 0x8
    CMMotionManager *_motionManager;	// 16 = 0x10
    CADisplayLink *_displayLink;	// 24 = 0x18
    long long _cachedInterfaceOrientation;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x0000000100093584
- (long long)_currentInterfaceOrientation;	// IMP=0x0000000100093528
- (id)_currentWindowScene;	// IMP=0x00000001000933a8
- (void)_motionManagerDidReceiveMotion:(id)arg1;	// IMP=0x0000000100093250
- (void)_cleanUpIfNeeded;	// IMP=0x00000001000931e0
- (void)_displayLinkFired:(id)arg1;	// IMP=0x0000000100093184
- (void)_configureDeviceMotionIfNeeded;	// IMP=0x0000000100092f58
- (void)_updateImageView:(id)arg1 forUserInterfaceStyle:(long long)arg2;	// IMP=0x0000000100092e78
- (_Bool)_supportsDeviceMotion;	// IMP=0x0000000100092e60
- (void)layoutSubviews;	// IMP=0x0000000100092d1c
- (void)invalidate;	// IMP=0x0000000100092d10
- (void)updateMaskingForView:(id)arg1;	// IMP=0x0000000100092b54
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x0000000100092a48
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100092960

@end

