//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class UILabel;

@interface SRSpeechAlternativeTapToEditCellView : UIView
{
    UILabel *_tapToEditLabel;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x000000010008c84c
- (void)layoutSubviews;	// IMP=0x000000010008c744
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;	// IMP=0x000000010008c734
- (void)setTextHidden:(_Bool)arg1;	// IMP=0x000000010008c5a8
- (id)init;	// IMP=0x000000010008c348

@end

