//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "SRTranscriptViewControllerDataSource-Protocol.h"
#import "SRTranscriptViewControllerDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"

@class NSArray, NSMutableArray, NSString, NSTimer, SRTranscriptStackView, UINavigationController;
@protocol SRTranscriptStackViewControllerDataSource, SRTranscriptStackViewControllerDelegate;

@interface SRTranscriptStackViewController : UIViewController <SRTranscriptViewControllerDataSource, SRTranscriptViewControllerDelegate, UINavigationControllerDelegate>
{
    _Bool _inUITrackingRunLoopMode;	// 8 = 0x8
    id <SRTranscriptStackViewControllerDataSource> _dataSource;	// 16 = 0x10
    id <SRTranscriptStackViewControllerDelegate> _delegate;	// 24 = 0x18
    UINavigationController *_navigationController;	// 32 = 0x20
    NSMutableArray *_navigationTransitionQueue;	// 40 = 0x28
    NSTimer *_navigationTransitionTimer;	// 48 = 0x30
}

+ (id)_createViewControllerWithItemIdentifier:(id)arg1;	// IMP=0x0000000100005fc8
- (void).cxx_destruct;	// IMP=0x000000010000a90c
@property(nonatomic, getter=_isInUITrackingRunLoopMode, setter=_setInUITrackingRunLoopMode:) _Bool inUITrackingRunLoopMode; // @synthesize inUITrackingRunLoopMode=_inUITrackingRunLoopMode;
@property(retain, nonatomic, getter=_navigationTransitionTimer, setter=_setNavigationTransitionTimer:) NSTimer *navigationTransitionTimer; // @synthesize navigationTransitionTimer=_navigationTransitionTimer;
@property(retain, nonatomic, getter=_navigationTransitionQueue, setter=_navigationTransitionQueue:) NSMutableArray *navigationTransitionQueue; // @synthesize navigationTransitionQueue=_navigationTransitionQueue;
@property(readonly, nonatomic, getter=_navigationController) UINavigationController *navigationController; // @synthesize navigationController=_navigationController;
@property(nonatomic) __weak id <SRTranscriptStackViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak id <SRTranscriptStackViewControllerDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (_Bool)_canShowWhileLocked;	// IMP=0x000000010000a83c
- (void)navigationControllerInteractivePopGestureRecognized:(id)arg1;	// IMP=0x000000010000a7ec
- (void)navigationController:(id)arg1 didShowViewController:(id)arg2 animated:(_Bool)arg3;	// IMP=0x000000010000a518
- (void)navigationController:(id)arg1 willShowViewController:(id)arg2 animated:(_Bool)arg3;	// IMP=0x000000010000a424
- (unsigned long long)navigationIndexOfTranscriptViewController:(id)arg1;	// IMP=0x000000010000a38c
- (_Bool)inTextInputModeForTranscriptViewController:(id)arg1;	// IMP=0x000000010000a338
- (CDStruct_a82615c4)keyboardInfoForTranscriptViewController:(id)arg1;	// IMP=0x000000010000a2c8
- (void)transcriptViewControllerDidResignFirstResponder:(id)arg1;	// IMP=0x000000010000a280
- (void)transcriptViewController:(id)arg1 viewDidSetContentSize:(struct CGSize)arg2;	// IMP=0x000000010000a1cc
- (void)transcriptViewController:(id)arg1 requestPasscodeUnlockWithCompletion:(CDUnknownBlockType)arg2;	// IMP=0x000000010000a15c
- (unsigned long long)deviceLockStateForTranscriptViewController:(id)arg1;	// IMP=0x000000010000a108
- (id)transcriptViewController:(id)arg1 updatedUserUtteranceForRefId:(id)arg2;	// IMP=0x000000010000a084
- (id)transcriptViewController:(id)arg1 additionalSpeechInterpretationsForRefId:(id)arg2;	// IMP=0x000000010000a000
- (void)transcriptViewController:(id)arg1 didShowGuideStartDate:(id)arg2 endDate:(id)arg3;	// IMP=0x0000000100009f74
- (void)transcriptViewController:(id)arg1 didShowTipWithIdentifier:(id)arg2 startDate:(id)arg3 endDate:(id)arg4 flowID:(id)arg5;	// IMP=0x0000000100009ea8
- (void)transcriptViewController:(id)arg1 didShowAceViewWithIdentifier:(id)arg2 aceViewClass:(Class)arg3 metricsContext:(id)arg4 forInterval:(double)arg5;	// IMP=0x0000000100009dfc
- (void)transcriptViewController:(id)arg1 didScrollForInterval:(double)arg2;	// IMP=0x0000000100009d70
- (void)transcriptViewController:(id)arg1 didEditSpeechRecognized:(id)arg2 forInterval:(double)arg3;	// IMP=0x0000000100009cf0
- (void)transcriptViewController:(id)arg1 shouldPresentPicker:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0000000100009c64
- (void)transcriptViewController:(id)arg1 setStatusBarHidden:(_Bool)arg2 animated:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x0000000100009bdc
- (void)transcriptViewController:(id)arg1 setStatusBarHidden:(_Bool)arg2 animated:(_Bool)arg3;	// IMP=0x0000000100009b7c
- (void)transcriptViewController:(id)arg1 didRequestKeyboardWithVisibility:(_Bool)arg2;	// IMP=0x0000000100009b24
- (void)transcriptViewController:(id)arg1 didDismissViewController:(id)arg2;	// IMP=0x0000000100009ab4
- (void)transcriptViewController:(id)arg1 willDismissViewController:(id)arg2;	// IMP=0x0000000100009a44
- (void)transcriptViewController:(id)arg1 didPresentViewController:(id)arg2;	// IMP=0x00000001000099d4
- (void)transcriptViewController:(id)arg1 willPresentViewController:(id)arg2;	// IMP=0x0000000100009964
- (void)transcriptViewController:(id)arg1 setTypeToSiriViewHidden:(_Bool)arg2;	// IMP=0x000000010000990c
- (void)transcriptViewController:(id)arg1 setStatusViewHidden:(_Bool)arg2;	// IMP=0x00000001000098b4
- (void)cancelSpeakingForTranscriptViewController:(id)arg1;	// IMP=0x000000010000986c
- (void)transcriptViewController:(id)arg1 speakText:(id)arg2 isPhonetic:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x00000001000097d0
- (void)cancelRequestForTranscriptViewController:(id)arg1;	// IMP=0x0000000100009788
- (void)transcriptViewControllerDidEndEditing:(id)arg1;	// IMP=0x0000000100009740
- (void)transcriptViewControllerWillBeginEditing:(id)arg1;	// IMP=0x00000001000096f8
- (void)transcriptViewControllerRequestKeyboardForTapToEditWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010000968c
- (_Bool)transcriptViewControllerShouldPreventUserInteraction:(id)arg1;	// IMP=0x0000000100009638
- (void)willSendStartRequestForTranscriptViewController:(id)arg1;	// IMP=0x00000001000095f0
- (void)transcriptViewController:(id)arg1 performAceCommand:(id)arg2 conversationItemIdentifier:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x0000000100009540
- (void)transcriptViewController:(id)arg1 showSiriStatusWithText:(id)arg2 speakableDescription:(id)arg3;	// IMP=0x000000010000953c
- (void)transcriptViewController:(id)arg1 didCorrectRecognition:(id)arg2 correctionIdentifier:(id)arg3 forItemAtIndex:(long long)arg4 userSelectionResults:(id)arg5;	// IMP=0x0000000100009438
- (void)transcriptViewController:(id)arg1 openURL:(id)arg2 conversationItemIdentifier:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x0000000100009388
- (id)effectiveCoreLocationBundleForTranscriptViewController:(id)arg1;	// IMP=0x000000010000932c
- (void)transcriptViewController:(id)arg1 didDelayPresentationOfItemsWithIdentifiers:(id)arg2;	// IMP=0x00000001000092bc
- (void)transcriptViewController:(id)arg1 willDiscardConversationItemsWithIdentifiers:(id)arg2;	// IMP=0x0000000100009210
- (void)transcriptViewController:(id)arg1 didPresentConversationItemsWithIdentifiers:(id)arg2;	// IMP=0x0000000100009164
- (void)transcriptViewController:(id)arg1 didHideVibrantView:(id)arg2;	// IMP=0x00000001000090f4
- (void)transcriptViewControllerDidShowSuggestions:(id)arg1;	// IMP=0x00000001000090ac
- (_Bool)transcriptViewControllerWillShowSuggestions:(id)arg1;	// IMP=0x0000000100009058
- (_Bool)transcriptViewControllerShouldDelaySuggestions:(id)arg1;	// IMP=0x0000000100009004
- (long long)initialDisplayTypeForTranscriptViewController:(id)arg1;	// IMP=0x0000000100008fb0
- (double)statusViewHeightForTranscriptViewController:(id)arg1;	// IMP=0x0000000100008f54
- (struct CGRect)statusBarFrameForTranscriptViewController:(id)arg1;	// IMP=0x0000000100008ed8
- (struct CGSize)estimatedVisibleContentSizeForTranscriptViewController:(id)arg1;	// IMP=0x0000000100008e30
- (double)contentWidthForTranscriptViewController:(id)arg1;	// IMP=0x0000000100008dd4
- (id)siriEnabledAppListForTranscriptViewController:(id)arg1;	// IMP=0x0000000100008d78
- (id)domainObjectStoreForTranscriptViewController:(id)arg1;	// IMP=0x0000000100008d1c
- (id)conversationItemListForTranscriptViewController:(id)arg1;	// IMP=0x0000000100008c44
- (long long)siriStateForTranscriptViewController:(id)arg1;	// IMP=0x0000000100008bf0
- (void)_exitUITrackingRunLoopMode;	// IMP=0x0000000100008bb0
- (void)_enterUITrackingRunLoopMode;	// IMP=0x0000000100008b6c
- (void)_enumerateSortedParentItemIndexPathsForItemIndexPaths:(id)arg1 usingBlock:(CDUnknownBlockType)arg2;	// IMP=0x0000000100008b18
- (void)_enumerateSortedParentItemIndexPathsForItemIndexPaths:(id)arg1 withOptions:(unsigned long long)arg2 usingBlock:(CDUnknownBlockType)arg3;	// IMP=0x0000000100008768
- (id)_indexPathsForItemsAtIndexes:(id)arg1 inTranscriptViewController:(id)arg2;	// IMP=0x0000000100008598
- (id)_indexPathForItemAtIndex:(long long)arg1 inTranscriptViewController:(id)arg2;	// IMP=0x0000000100008538
- (id)_indexPathForViewControllerDisplayingItemAtIndexPath:(id)arg1;	// IMP=0x0000000100008528
- (id)_transcriptViewControllerDisplayingChildrenOfItemAtIndexPath:(id)arg1;	// IMP=0x00000001000084c8
- (id)_transcriptViewControllerDisplayingChildrenOfItemWithIdentifier:(id)arg1;	// IMP=0x0000000100008284
- (id)_indexPathForParentOfItemsInTranscriptViewController:(id)arg1;	// IMP=0x0000000100008220
- (id)_indexPathForItemWithIdentifier:(id)arg1;	// IMP=0x00000001000081a0
- (id)_identifierOfItemAtIndexPath:(id)arg1;	// IMP=0x0000000100008120
- (id)_topTranscriptViewController;	// IMP=0x00000001000080cc
- (_Bool)logActiveTranscriptContents;	// IMP=0x0000000100008080
- (void)siriDidDetectSpeechStartpoint;	// IMP=0x0000000100008040
- (void)siriStoppedFingerprintingMusic;	// IMP=0x0000000100008000
- (void)siriBeganFingerprintingMusic;	// IMP=0x0000000100007fc0
- (void)showSpeechAlternatives:(id)arg1;	// IMP=0x0000000100007f54
- (void)showFullScreenEffect:(id)arg1;	// IMP=0x0000000100007ee8
- (void)handleGetResponseAlternativesPlayback:(id)arg1;	// IMP=0x0000000100007e7c
- (void)changeUtterance:(id)arg1;	// IMP=0x0000000100007e10
- (void)_processTransitionQueue;	// IMP=0x0000000100007c08
- (void)_queuePushViewController:(id)arg1 animated:(_Bool)arg2;	// IMP=0x0000000100007a5c
- (void)_queuePopToViewController:(id)arg1 animated:(_Bool)arg2;	// IMP=0x0000000100007850
- (void)siriDidFinishActionsForConversationItemWithIdentifier:(id)arg1;	// IMP=0x0000000100007798
- (void)presentationStateDidChangeForItemsAtIndexPaths:(id)arg1;	// IMP=0x00000001000076b4
- (void)removeItemsWithIdentifiers:(id)arg1 atIndexPaths:(id)arg2 parentItemIdentifiers:(id)arg3;	// IMP=0x000000010000727c
- (void)reloadItemsAtIndexPaths:(id)arg1;	// IMP=0x0000000100007198
- (void)insertItemsAtIndexPaths:(id)arg1;	// IMP=0x0000000100006e60
@property(readonly, nonatomic) _Bool transcriptIsAnimating;
- (void)restoreTopTranscriptPositionAnimated:(_Bool)arg1;	// IMP=0x0000000100006dcc
- (void)showTranscriptEnd;	// IMP=0x0000000100006d8c
- (void)showTranscriptStart;	// IMP=0x0000000100006d2c
@property(readonly, nonatomic) _Bool transcriptEndIsVisible;
@property(readonly, nonatomic) _Bool transcriptStartIsVisible;
- (id)_conversation;	// IMP=0x0000000100006c38
- (void)siriDidStopSpeakingWithIdentifier:(id)arg1 speechQueueIsEmpty:(_Bool)arg2;	// IMP=0x0000000100006bc4
- (void)siriDidStartSpeakingWithIdentifier:(id)arg1;	// IMP=0x0000000100006b58
- (void)siriRequestWillStart;	// IMP=0x0000000100006b18
- (void)siriDidDeactivate;	// IMP=0x00000001000069a8
- (_Bool)currentSnippetContainsFooterButtons;	// IMP=0x000000010000695c
- (void)siriDidTransitionFromState:(long long)arg1 event:(long long)arg2;	// IMP=0x0000000100006828
- (void)siriWillActivateFromSource:(long long)arg1;	// IMP=0x00000001000066fc
@property(readonly, nonatomic) NSArray *requestContext;
- (void)keyboardHeightDidChange;	// IMP=0x0000000100006660
- (void)statusViewHeightDidChange;	// IMP=0x0000000100006618
- (void)statusBarFrameDidChange;	// IMP=0x00000001000065d0
- (void)endEditingAndCorrect:(_Bool)arg1;	// IMP=0x00000001000064a4
- (void)showRootTranscript;	// IMP=0x000000010000642c
- (void)pinLastDisplayedChildOfItemWithIdentifier:(id)arg1;	// IMP=0x00000001000063e0
- (void)pinItemWithIdentifier:(id)arg1;	// IMP=0x0000000100006328
- (id)identifierOfLastDisplayedChildOfItemWithIdentifier:(id)arg1;	// IMP=0x00000001000062d4
- (void)resumeTouchesIfNecessary;	// IMP=0x00000001000061b8
- (void)cancelTouchesIfNecessary;	// IMP=0x000000010000609c
- (id)_transcriptViewControllers;	// IMP=0x0000000100006048
- (id)_createViewControllerWithItemIdentifier:(id)arg1;	// IMP=0x0000000100005f40
- (void)reloadData;	// IMP=0x0000000100005e0c
- (void)loadView;	// IMP=0x0000000100005bc8
- (id)childViewControllerForHomeIndicatorAutoHidden;	// IMP=0x0000000100005bbc
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x0000000100005afc
- (void)dealloc;	// IMP=0x0000000100005964
- (id)initWithNibName:(id)arg1 bundle:(id)arg2 delegate:(id)arg3 dataSource:(id)arg4;	// IMP=0x0000000100005600
- (id)initWithDelegate:(id)arg1 dataSource:(id)arg2;	// IMP=0x000000010000559c
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x0000000100005538
- (void)srsvc_setConversation:(id)arg1;	// IMP=0x000000010008c2f8
- (id)srsvc_conversation;	// IMP=0x000000010008c2ec

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(retain, nonatomic) SRTranscriptStackView *view; // @dynamic view;

@end

