//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "CMWakeGestureDelegate-Protocol.h"

@class AWAttentionAwarenessClient, CMWakeGestureManager, NSMutableDictionary, NSString, SRUserAttentionSignalProviderFactory;
@protocol OS_dispatch_queue, SRUserAttentionControllerDelegate;

@interface SRUserAttentionController : NSObject <CMWakeGestureDelegate>
{
    SRUserAttentionSignalProviderFactory *_userAttentionSignalProviderFactory;	// 8 = 0x8
    unsigned long long _supportedAttentionAwarenessEvents;	// 16 = 0x10
    _Bool _deviceSupportsRaiseGestureDetection;	// 24 = 0x18
    AWAttentionAwarenessClient *_faceAttentionAwarenessClient;	// 32 = 0x20
    AWAttentionAwarenessClient *_touchAttentionAwarenessClient;	// 40 = 0x28
    CMWakeGestureManager *_wakeGestureManager;	// 48 = 0x30
    NSObject<OS_dispatch_queue> *_attentionAwarenessHandlerQueue;	// 56 = 0x38
    NSMutableDictionary *_attentionDetectionStatuses;	// 64 = 0x40
    NSObject<OS_dispatch_queue> *_asynchronousCallQueue;	// 72 = 0x48
    _Bool _deviceLowered;	// 80 = 0x50
    id <SRUserAttentionControllerDelegate> _delegate;	// 88 = 0x58
}

- (void).cxx_destruct;	// IMP=0x000000010000463c
@property(nonatomic, getter=_isDeviceLowered, setter=_setDeviceLowered:) _Bool deviceLowered; // @synthesize deviceLowered=_deviceLowered;
@property(nonatomic) __weak id <SRUserAttentionControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (_Bool)_deviceSupportsFaceDetection;	// IMP=0x00000001000045fc
- (void)_setDetectionStarted:(_Bool)arg1 forType:(unsigned long long)arg2;	// IMP=0x0000000100004530
- (_Bool)_detectionStartedForType:(unsigned long long)arg1;	// IMP=0x00000001000044a8
- (void)wakeGestureManager:(id)arg1 didUpdateWakeGesture:(long long)arg2;	// IMP=0x0000000100004240
- (void)_stopWakeGestureManagerIfNeeded;	// IMP=0x00000001000041d4
- (void)_startWakeGestureManagerIfNeeded;	// IMP=0x000000010000414c
- (void)_handleTouchAttentionEvent:(id)arg1;	// IMP=0x0000000100003fd0
- (void)_handleFaceAttentionEvent:(id)arg1;	// IMP=0x0000000100003e04
- (_Bool)_restartFaceAttentionAwarenessClient:(id *)arg1;	// IMP=0x0000000100003da0
- (_Bool)_stopTouchAttentionAwarenessClient:(id *)arg1;	// IMP=0x0000000100003d60
- (_Bool)_stopFaceAttentionAwarenessClient:(id *)arg1;	// IMP=0x0000000100003d20
- (_Bool)_startTouchAttentionAwarenessClient:(id *)arg1;	// IMP=0x0000000100003bb8
- (_Bool)_startFaceAttentionAwarenessClient:(id *)arg1;	// IMP=0x0000000100003a3c
- (_Bool)stopIfNeededForTypes:(unsigned long long)arg1 error:(id *)arg2;	// IMP=0x0000000100003930
- (_Bool)stopIfNeeded:(id *)arg1;	// IMP=0x000000010000391c
- (_Bool)startIfNeededForTypes:(unsigned long long)arg1 error:(id *)arg2;	// IMP=0x00000001000037fc
- (_Bool)startIfNeeded:(id *)arg1;	// IMP=0x00000001000037e8
- (void)dealloc;	// IMP=0x0000000100003744
- (id)initWithSignalProviderFactory:(id)arg1 supportedAttentionAwarenessEvents:(unsigned long long)arg2 deviceSupportsRaiseGestureDetection:(_Bool)arg3;	// IMP=0x0000000100003690
- (id)initWithSamplingInterval:(double)arg1 attentionLossTimeout:(double)arg2 supportedAttentionAwarenessEvents:(unsigned long long)arg3 deviceSupportsRaiseGestureDetection:(_Bool)arg4;	// IMP=0x0000000100003600
- (void)startIfNeededForTypes:(unsigned long long)arg1 completionQueue:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00000001000046b0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

