//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC8wifip2pd21InternetSharingPolicy.h"

@class MISSING_TYPE;

@interface _TtC8wifip2pd29InternetSharingProviderPolicy : _TtC8wifip2pd21InternetSharingPolicy
{
    MISSING_TYPE *requesters;	// 32 = 0x20
    MISSING_TYPE *ssid;	// 40 = 0x28
    MISSING_TYPE *bssid;	// 56 = 0x38
    MISSING_TYPE *infrastructureChannel;	// 64 = 0x40
}

@end

