//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "B238SetupBaseViewController.h"

@class UIButton, UILabel;

@interface B238SetupRecognizeVoiceViewController : B238SetupBaseViewController
{
    UILabel *_titleLabel;	// 32 = 0x20
    UILabel *_infoLabel;	// 40 = 0x28
    UILabel *_subInfoLabel;	// 48 = 0x30
    UIButton *_continueButton;	// 56 = 0x38
    UIButton *_skipButton;	// 64 = 0x40
}

- (void).cxx_destruct;	// IMP=0x00000001000268bc
@property(retain, nonatomic) UIButton *skipButton; // @synthesize skipButton=_skipButton;
@property(retain, nonatomic) UIButton *continueButton; // @synthesize continueButton=_continueButton;
@property(retain, nonatomic) UILabel *subInfoLabel; // @synthesize subInfoLabel=_subInfoLabel;
@property(retain, nonatomic) UILabel *infoLabel; // @synthesize infoLabel=_infoLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void)handleSkipButton:(id)arg1;	// IMP=0x0000000100026584
- (void)handleDismissButton:(id)arg1;	// IMP=0x00000001000264f4
- (void)handleContinueButton:(id)arg1;	// IMP=0x000000010002643c
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x000000010002633c

@end

