//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SVSBaseMainController.h"

@class CUXPCAgent, NFCTagReaderScanViewController, NSString, SVSCommonNavController, UIStoryboard;

@interface NFCTagReaderMainController : SVSBaseMainController
{
    _Bool _dismissed;	// 24 = 0x18
    _Bool _dismissPending;	// 25 = 0x19
    int _operationCount;	// 28 = 0x1c
    UIStoryboard *_storyboard;	// 32 = 0x20
    NFCTagReaderScanViewController *_vcIdle;	// 40 = 0x28
    SVSCommonNavController *_vcNav;	// 48 = 0x30
    NFCTagReaderScanViewController *_vcScan;	// 56 = 0x38
    CUXPCAgent *_xpcAgent;	// 64 = 0x40
    _Bool _appeared;	// 72 = 0x48
    _Bool _dismissing;	// 73 = 0x49
    NSString *_purpose;	// 80 = 0x50
    long long _tagCount;	// 88 = 0x58
}

- (void).cxx_destruct;	// IMP=0x00000001000426a8
@property(nonatomic) long long tagCount; // @synthesize tagCount=_tagCount;
@property(copy, nonatomic) NSString *purpose; // @synthesize purpose=_purpose;
@property(nonatomic) _Bool dismissing; // @synthesize dismissing=_dismissing;
@property(nonatomic) _Bool appeared; // @synthesize appeared=_appeared;
- (void)uiOperationEnd;	// IMP=0x0000000100042574
- (void)uiOperationBegin;	// IMP=0x000000010004255c
- (void)showScanUI;	// IMP=0x00000001000423f4
- (void)showIdleUI;	// IMP=0x000000010004228c
- (void)nfcTagScannedCount:(long long)arg1;	// IMP=0x0000000100042110
- (void)handleButtonActions:(id)arg1;	// IMP=0x0000000100041f84
- (void)dismissIfIdle;	// IMP=0x0000000100041e14
- (void)dismissAnimated:(_Bool)arg1;	// IMP=0x0000000100041d30
- (void)dismiss:(int)arg1;	// IMP=0x0000000100041d1c
- (void)viewDidDisappear:(_Bool)arg1;	// IMP=0x0000000100041a40
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x00000001000416fc
- (unsigned long long)supportedInterfaceOrientations;	// IMP=0x0000000100041674
- (void)configureWithContext:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100041238

@end

