//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "tGraphDataSource-Protocol.h"

@class AWDServerConnection, AggDThermalMonitor, ArcController, CameraTS, ContextualClampController, LifetimeServoController, NSArray, NSDictionary, NSMutableArray, NSUserDefaults, TableDrivenDecisionTree;
@protocol OS_dispatch_queue;

@interface CommonProduct : NSObject <tGraphDataSource>
{
    AggDThermalMonitor *aggdTM;	// 8 = 0x8
    _Bool thermalTrap;	// 16 = 0x10
    NSMutableArray *listofComponentControl;	// 24 = 0x18
    NSMutableArray *listOfSupervisorControl;	// 32 = 0x20
    int calibrationResistorSensor;	// 40 = 0x28
    int calibrationResistorTempDefault;	// 44 = 0x2c
    unsigned int requiredCalibrationResistorSamples;	// 48 = 0x30
    TableDrivenDecisionTree *decisionTree;	// 56 = 0x38
    int thermalState;	// 64 = 0x40
    unsigned long long componentThermalStatusLevel;	// 72 = 0x48
    unsigned long long previousOSThermalNotificationLevel;	// 80 = 0x50
    long long previousThermalPressureLevel;	// 88 = 0x58
    int moderatePressureToLevelVersion;	// 96 = 0x60
    CameraTS *camSensor;	// 104 = 0x68
    _Bool canForceThermalLevels;	// 112 = 0x70
    _Bool usesFastDieTempControl;	// 113 = 0x71
    _Bool suppressesTrapSubCountLogging;	// 114 = 0x72
    _Bool needsAppleConnectThermalTrapLogging;	// 115 = 0x73
    _Bool sendMaxTemp;	// 116 = 0x74
    int tsfdIndex;	// 120 = 0x78
    _Bool _blendStillNeeded;	// 124 = 0x7c
    _Bool _haveUsedDeferral;	// 125 = 0x7d
    int baseVT[30];	// 128 = 0x80
    int _forcedThermalLevelLower;	// 248 = 0xf8
    int _forcedThermalLevelUpper;	// 252 = 0xfc
    ContextualClampController *contextualClampController;	// 256 = 0x100
    ArcController *_arcController;	// 264 = 0x108
    AWDServerConnection *awdConnection;	// 272 = 0x110
    NSDictionary *simulatedThermalMitigationLimits;	// 280 = 0x118
    NSDictionary *simulatedLowTempMitigationLimits;	// 288 = 0x120
    int _totalSensorCount;	// 296 = 0x128
    int _powerSensorCount;	// 300 = 0x12c
    unsigned long long _PMUtcalAdjustMask;	// 304 = 0x130
    _Bool _reducedRateModeActive;	// 312 = 0x138
    _Bool _skipRegularAggdCountUpdate;	// 313 = 0x139
    long long thermalPressureLevel;	// 320 = 0x140
    NSArray *_maximumDieTempSensorIndexSet;	// 328 = 0x148
    NSArray *_averageDieTempSensorIndexSet;	// 336 = 0x150
    NSArray *_filteredAverageDieTempSensorIndexSet;	// 344 = 0x158
    LifetimeServoController *lifetimeServoController;	// 352 = 0x160
    _Bool _isBackLightOn;	// 360 = 0x168
    _Bool _isCPMSMitigationEnabled;	// 361 = 0x169
    int _displayToken;	// 364 = 0x16c
    int _chargerToken;	// 368 = 0x170
    int _chargerState;	// 372 = 0x174
    NSObject<OS_dispatch_queue> *_thermalQueue;	// 376 = 0x178
    NSUserDefaults *_defaults;	// 384 = 0x180
}

@property(nonatomic) _Bool isCPMSMitigationEnabled; // @synthesize isCPMSMitigationEnabled=_isCPMSMitigationEnabled;
@property(retain, nonatomic) NSUserDefaults *defaults; // @synthesize defaults=_defaults;
@property(readonly, nonatomic) long long thermalPressureLevel; // @synthesize thermalPressureLevel;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *thermalQueue; // @synthesize thermalQueue=_thermalQueue;
@property(nonatomic) int chargerState; // @synthesize chargerState=_chargerState;
@property(nonatomic) int chargerToken; // @synthesize chargerToken=_chargerToken;
@property(nonatomic) int displayToken; // @synthesize displayToken=_displayToken;
@property(nonatomic) _Bool isBackLightOn; // @synthesize isBackLightOn=_isBackLightOn;
@property(nonatomic) int thermalState; // @synthesize thermalState;
@property(readonly, nonatomic) NSMutableArray *listOfSupervisorControl; // @synthesize listOfSupervisorControl;
@property(readonly, nonatomic) NSMutableArray *listofComponentControl; // @synthesize listofComponentControl;
@property(nonatomic) unsigned long long componentThermalStatusLevel; // @synthesize componentThermalStatusLevel;
@property(readonly, nonatomic) unsigned int requiredCalibrationResistorSamples; // @synthesize requiredCalibrationResistorSamples;
@property(readonly, nonatomic) int calibrationResistorTempDefault; // @synthesize calibrationResistorTempDefault;
@property(readonly, nonatomic) int calibrationResistorSensor; // @synthesize calibrationResistorSensor;
- (struct __CFString *)copyFieldCurrentValueForIndex:(int)arg1;	// IMP=0x0000000100053504
- (struct __CFString *)copyHeaderForIndex:(int)arg1;	// IMP=0x0000000100053488
- (int)numberOfFields;	// IMP=0x0000000100053480
- (void)canaryModeExitEarly:(int)arg1;	// IMP=0x000000010005347c
- (int)canaryTempThreshold;	// IMP=0x0000000100053474
- (int)canaryTempSensorIndex;	// IMP=0x000000010005346c
- (int)desiredLoopInterval;	// IMP=0x0000000100053460
- (void)suppressStandardBehaviors;	// IMP=0x000000010005345c
- (_Bool)shouldSuppressStandardBehaviors:(struct __CFDictionary *)arg1;	// IMP=0x0000000100053158
- (_Bool)canSystemSleep;	// IMP=0x0000000100053150
- (void)updateSystemPowerState:(_Bool)arg1;	// IMP=0x00000001000530e0
- (void)replaceOrAppendHotspotEntry:(struct __CFDictionary *)arg1 existingHotspots:(struct __CFArray *)arg2;	// IMP=0x0000000100053000
- (struct __CFArray *)copyHotspotsArray:(id)arg1;	// IMP=0x0000000100052fbc
- (int)sensorIndexFromList:(struct __CFArray *)arg1 fourCharCode:(struct __CFString *)arg2;	// IMP=0x0000000100052f24
- (int)getModeratePressureVersion;	// IMP=0x0000000100052f1c
- (_Bool)getPotentialForcedThermalPressureLevel;	// IMP=0x0000000100052dfc
- (unsigned long long)getPotentialForcedThermalLevel:(unsigned long long)arg1;	// IMP=0x0000000100052c80
- (_Bool)useTcalAdjust:(unsigned int)arg1;	// IMP=0x0000000100052c70
- (void)updateTrapTargetFor:(int)arg1:(unsigned int)arg2;	// IMP=0x0000000100052c20
- (void)updateSleepTargetFor:(int)arg1:(unsigned int)arg2;	// IMP=0x0000000100052bd0
- (void)updateMaxLIFor:(int)arg1:(unsigned int)arg2;	// IMP=0x0000000100052b50
- (void)removeHotspotTargetOverrides;	// IMP=0x0000000100052a4c
- (void)updateHotSpotPIDTargetFor:(int)arg1:(unsigned int)arg2;	// IMP=0x0000000100052a0c
- (void)updateControlEffortFor:(int)arg1:(unsigned int)arg2;	// IMP=0x000000010005294c
- (void)overrideArcParam:(id)arg1 value:(int)arg2;	// IMP=0x000000010005293c
- (int)arcVirtualTemperature;	// IMP=0x0000000100052934
- (int)arcModuleTemperature;	// IMP=0x000000010005292c
- (int)gasGaugeBatteryTemperature;	// IMP=0x0000000100052924
- (int)thermalSensorValuesMaxFromIndexSet:(id)arg1 filteredOnly:(_Bool)arg2;	// IMP=0x00000001000527d8
- (int)dieTempFilteredMaxAverage;	// IMP=0x00000001000527b0
- (int)dieTempMaxAverage;	// IMP=0x000000010005279c
- (int)dieTempMaxMax;	// IMP=0x0000000100052788
- (void)updateContextualClamp;	// IMP=0x0000000100052770
- (void)overrideLifetimeServoParam:(id)arg1 value:(int)arg2;	// IMP=0x0000000100052758
- (void)updateLifetimeServo;	// IMP=0x00000001000526e8
- (void)predictSignal;	// IMP=0x00000001000526e4
- (void)updateCoreAnalyticsInfo;	// IMP=0x00000001000526e0
- (void)updateAggdInfo;	// IMP=0x00000001000526dc
- (id)getGridY;	// IMP=0x0000000100052698
- (id)getGridX;	// IMP=0x0000000100052654
- (void)setup2DGridDisplayDriver;	// IMP=0x0000000100052420
- (void)send2DGridTempsToDisplayDriver:(int *)arg1;	// IMP=0x0000000100052268
- (void)sendMaxTempToDisplayDriver:(int)arg1;	// IMP=0x00000001000520c8
- (void)updateDisplayDriver:(_Bool)arg1;	// IMP=0x0000000100051cf0
- (void)writeAllCornerTemperatures:(int)arg1;	// IMP=0x0000000100051bb0
- (int)getFrontDisplayCenterTemperature;	// IMP=0x0000000100051ba8
- (void)updatePowerzoneTelemetry;	// IMP=0x0000000100051b7c
- (int)computeMaxCGTemp;	// IMP=0x0000000100051b38
- (int *)compute2DGridTemps;	// IMP=0x0000000100051af4
- (void)updateAllThermalLoad:(_Bool)arg1;	// IMP=0x0000000100051ab4
- (void)tryTakeAction;	// IMP=0x0000000100051974
- (int)powerSensors;	// IMP=0x000000010005196c
- (int)totalSensors;	// IMP=0x0000000100051964
- (void)probeAllSupervisorControlLoadingIndex;	// IMP=0x000000010005192c
- (_Bool)isInternalInstall;	// IMP=0x00000001000518c8
- (int)maxControlEffort;	// IMP=0x00000001000517a4
- (unsigned long long)getMaxSensorValue;	// IMP=0x000000010005164c
- (int)getHighestSkinTemp;	// IMP=0x0000000100051528
- (struct iir_filter_t *)getFilterValues;	// IMP=0x00000001000514fc
- (_Bool)isSendingMaxTempToDisplayDriverEnabled;	// IMP=0x00000001000514f4
- (void)enableSendingMaxTempToDisplayDriver;	// IMP=0x00000001000514e8
- (id)newBacklightComponentController:(struct __CFDictionary *)arg1;	// IMP=0x00000001000514b4
- (int)getCurrentMaxLIForComponent:(unsigned int)arg1;	// IMP=0x0000000100051490
- (void)getAllComponentID:(struct __SCPreferences *)arg1;	// IMP=0x0000000100051288
- (id)findComponent:(int)arg1;	// IMP=0x00000001000510b4
- (void)logTrapEntryForAC:(id)arg1;	// IMP=0x0000000100051048
- (void)evaluteMitigationMaxLoadingIndex;	// IMP=0x0000000100050e04
- (void)createConnectionToCT;	// IMP=0x0000000100050ddc
- (void)clearLoadingIndexOverrides;	// IMP=0x0000000100050cd4
- (void)clearControlEffortOverrides;	// IMP=0x0000000100050b28
- (void)registerChargerNotification;	// IMP=0x00000001000508ec
- (void)registerDisplayNotification;	// IMP=0x00000001000507c8
- (void)pushChargerTypeToAWD:(int)arg1;	// IMP=0x0000000100050768
- (int)getChargerState;	// IMP=0x0000000100050760
- (_Bool)mitigationsFullyReleased;	// IMP=0x0000000100050648
- (_Bool)fourCharCodeNeedsPMUtcal:(struct __CFString *)arg1;	// IMP=0x0000000100050594
- (_Bool)fourCharCodeMatchesDieTempType:(BOOL)arg1 fourCharCode:(struct __CFString *)arg2;	// IMP=0x00000001000504a8
- (id)copyDieTempSensorIndexSetForFourthChar:(BOOL)arg1 sensors:(struct __CFArray *)arg2 filteredOnly:(_Bool)arg3;	// IMP=0x0000000100050324
- (void)dealloc;	// IMP=0x0000000100050290
- (void)putDeviceInLowTempSimulationMode:(id)arg1;	// IMP=0x0000000100050074
- (void)putDeviceInThermalSimulationMode:(id)arg1;	// IMP=0x000000010004fe1c
- (void)thermalUpdatesToWatchdogEnabled:(id)arg1;	// IMP=0x000000010004fcd8
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x000000010004fb54
- (void)setHiPFeatureEnabled:(_Bool)arg1;	// IMP=0x000000010004fb44
- (void)removeLightPressureOverride;	// IMP=0x000000010004fb28
- (void)simulateLightThermalPressure;	// IMP=0x000000010004fae0
- (void)registerDefaultsDomain;	// IMP=0x000000010004fa30
- (id)initProduct:(id)arg1;	// IMP=0x000000010004e05c

@end

