//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "ContextAwareObject.h"

#import "CARSessionObserving-Protocol.h"
#import "tGraphDataSource-Protocol.h"

@class CARSessionStatus, NSObject, NSString;
@protocol OS_dispatch_queue;

@interface ContextInPocket : ContextAwareObject <CARSessionObserving, tGraphDataSource>
{
    CARSessionStatus *_carSessionStatus;	// 16 = 0x10
    _Bool _carSessionActive;	// 24 = 0x18
    _Bool contextIsActive;	// 25 = 0x19
    _Bool connectedExternally;	// 26 = 0x1a
    _Bool backlightIsOn;	// 27 = 0x1b
    _Bool audioIsOn;	// 28 = 0x1c
    _Bool powerIsOn;	// 29 = 0x1d
    unsigned char _minCPU;	// 30 = 0x1e
    unsigned char _minGPU;	// 31 = 0x1f
    _Bool usesPackagePowerControl;	// 32 = 0x20
    int mitigationControllerListID;	// 36 = 0x24
    int _displayToken;	// 40 = 0x28
    int _audioRunningToken;	// 44 = 0x2c
    int _uncapRequestClientID;	// 48 = 0x30
    int _stockholmToken;	// 52 = 0x34
    unsigned int pmuPowerService;	// 56 = 0x38
    unsigned int _notification;	// 60 = 0x3c
    unsigned int _ioIterator;	// 64 = 0x40
    int _minPackagePower;	// 68 = 0x44
    unsigned long long stockholmFieldDetectInProgressUntilTime;	// 72 = 0x48
    unsigned long long wakeInProgressUntilTime;	// 80 = 0x50
    struct IONotificationPort *notificationPort;	// 88 = 0x58
    NSObject<OS_dispatch_queue> *_inPocketQueue;	// 96 = 0x60
}

@property(nonatomic) int minPackagePower; // @synthesize minPackagePower=_minPackagePower;
@property(nonatomic) _Bool usesPackagePowerControl; // @synthesize usesPackagePowerControl;
@property(nonatomic) NSObject<OS_dispatch_queue> *inPocketQueue; // @synthesize inPocketQueue=_inPocketQueue;
@property(nonatomic) unsigned int ioIterator; // @synthesize ioIterator=_ioIterator;
@property(nonatomic) unsigned int notification; // @synthesize notification=_notification;
@property(nonatomic) struct IONotificationPort *notificationPort; // @synthesize notificationPort;
@property(nonatomic) unsigned int pmuPowerService; // @synthesize pmuPowerService;
@property(nonatomic) unsigned char minGPU; // @synthesize minGPU=_minGPU;
@property(nonatomic) unsigned char minCPU; // @synthesize minCPU=_minCPU;
@property(nonatomic) int stockholmToken; // @synthesize stockholmToken=_stockholmToken;
@property(nonatomic) int uncapRequestClientID; // @synthesize uncapRequestClientID=_uncapRequestClientID;
@property(nonatomic) int audioRunningToken; // @synthesize audioRunningToken=_audioRunningToken;
@property(nonatomic) int displayToken; // @synthesize displayToken=_displayToken;
@property(nonatomic) int mitigationControllerListID; // @synthesize mitigationControllerListID;
@property(nonatomic) unsigned long long wakeInProgressUntilTime; // @synthesize wakeInProgressUntilTime;
@property(nonatomic) _Bool powerIsOn; // @synthesize powerIsOn;
@property(nonatomic) unsigned long long stockholmFieldDetectInProgressUntilTime; // @synthesize stockholmFieldDetectInProgressUntilTime;
@property(nonatomic) _Bool audioIsOn; // @synthesize audioIsOn;
@property(nonatomic) _Bool backlightIsOn; // @synthesize backlightIsOn;
@property(nonatomic) _Bool connectedExternally; // @synthesize connectedExternally;
@property(nonatomic) _Bool contextIsActive; // @synthesize contextIsActive;
- (struct __CFString *)copyFieldCurrentValueForIndex:(int)arg1;	// IMP=0x000000010001f2ec
- (struct __CFString *)copyHeaderForIndex:(int)arg1;	// IMP=0x000000010001f2d8
- (int)numberOfFields;	// IMP=0x000000010001f2d0
- (void)sessionDidDisconnect:(id)arg1;	// IMP=0x000000010001f208
- (void)sessionDidConnect:(id)arg1;	// IMP=0x000000010001f140
- (void)updateSystemPowerState:(_Bool)arg1;	// IMP=0x000000010001efb4
- (_Bool)synchContext;	// IMP=0x000000010001efac
- (void)updateContextActiveState;	// IMP=0x000000010001e868
- (_Bool)isContextTriggered;	// IMP=0x000000010001e85c
- (int)getContextState;	// IMP=0x000000010001e840
- (void)initStockholmHandling;	// IMP=0x000000010001e664
- (void)initAudioHandling;	// IMP=0x000000010001e51c
- (void)initBacklightHandling;	// IMP=0x000000010001e360
- (void)initPowerHandling;	// IMP=0x000000010001e10c
- (void)dealloc;	// IMP=0x000000010001e024
- (id)initWithParams:(id)arg1;	// IMP=0x000000010001dcd8
- (void)registerForTopOffStatusChanges;	// IMP=0x000000010001db84
- (void)handleCurrentTopOffStatusWithContext:(id)arg1;	// IMP=0x000000010001db3c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

