//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "tGraphDataSource-Protocol.h"

@class AggDThermalMonitor, LifetimeServoAFLUT;

@interface LifetimeServoControlLoop : NSObject <tGraphDataSource>
{
    int _loopType;	// 8 = 0x8
    AggDThermalMonitor *_aggdController;	// 16 = 0x10
    long long _is;	// 24 = 0x18
    long long _isUp;	// 32 = 0x20
    long long _isDown;	// 40 = 0x28
    float _r;	// 48 = 0x30
    float _af_i;	// 52 = 0x34
    int _u;	// 56 = 0x38
    int _Lmin;	// 60 = 0x3c
    int _Lmax;	// 64 = 0x40
    float _ki_ls;	// 68 = 0x44
    LifetimeServoAFLUT *_afLUT;	// 72 = 0x48
    int _perfStateVoltages[16];	// 80 = 0x50
    int _override_is;	// 144 = 0x90
    int _override_af_i;	// 148 = 0x94
    const void **_persistenceKeyNames;	// 152 = 0x98
    int _aggdIndexStateChange;	// 160 = 0xa0
    int _aggdIndexAFiBucket1;	// 164 = 0xa4
    int _aggdIndexAFiBucket2;	// 168 = 0xa8
    struct __CFString *_tGraphHeaderSuffix;	// 176 = 0xb0
}

- (struct __CFString *)copyFieldCurrentValueForIndex:(int)arg1;	// IMP=0x0000000100049b5c
- (struct __CFString *)copyHeaderForIndex:(int)arg1;	// IMP=0x0000000100049ac0
- (int)numberOfFields;	// IMP=0x0000000100049ab8
- (void)processSleepInterval:(long long)arg1;	// IMP=0x0000000100049994
- (_Bool)loopIsActive;	// IMP=0x0000000100049984
- (void)overrideAFi:(int)arg1;	// IMP=0x000000010004997c
- (void)overrideIS:(int)arg1;	// IMP=0x0000000100049974
- (float)accelerationFactorForTemperature:(int)arg1 cpuPerfStateIndex:(int)arg2;	// IMP=0x00000001000498ec
- (void)updateForPerfStateResidency:(float *)arg1 count:(int)arg2 tempMax:(int)arg3 tempAverage:(int)arg4;	// IMP=0x0000000100049650
- (void)updatePersistedState;	// IMP=0x000000010004948c
- (void)initializeLifetimeServoStateAsPersisted;	// IMP=0x000000010004906c
- (int)defaultDieTempTarget;	// IMP=0x0000000100049064
- (int)dieTempTarget;	// IMP=0x000000010004905c
- (void)updateDieTempTarget;	// IMP=0x0000000100049004
- (id)initWithParams:(id)arg1 aggdController:(id)arg2 perfStateVoltages:(int *)arg3 voltageCount:(int)arg4 loopType:(int)arg5;	// IMP=0x0000000100048a3c

@end

