//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class CommonProduct;

@interface ThermalManager : NSObject
{
    struct __CFRunLoop *localMainRunloop;	// 8 = 0x8
    int productName;	// 16 = 0x10
    CommonProduct *product;	// 24 = 0x18
    struct __CFDictionary *_plistConfig;	// 32 = 0x20
}

@property(readonly) struct __CFRunLoop *localMainRunloop; // @synthesize localMainRunloop;
- (_Bool)getPotentialForcedThermalPressureLevel;	// IMP=0x000000010000d3e4
- (void)canaryModeExitEarly:(int)arg1;	// IMP=0x000000010000d3d4
- (int)canaryTempThreshold;	// IMP=0x000000010000d3c4
- (int)canaryTempSensorIndex;	// IMP=0x000000010000d3b4
- (int)desiredLoopInterval;	// IMP=0x000000010000d3a4
- (_Bool)useTcalAdjust:(unsigned int)arg1;	// IMP=0x000000010000d394
- (struct __CFString *)getTGraphData:(int)arg1;	// IMP=0x000000010000d358
- (void)initDataCollection;	// IMP=0x000000010000d2c4
- (int)canSystemSleep;	// IMP=0x000000010000d2a4
- (void)updateSystemPowerState:(_Bool)arg1;	// IMP=0x000000010000d294
- (void)updateSystemLoad:(_Bool)arg1;	// IMP=0x000000010000d120
- (void)checkForArcOverride:(struct __SCPreferences *)arg1 key:(struct __CFString *)arg2;	// IMP=0x000000010000d09c
- (void)checkForLifetimeServoOverride:(struct __SCPreferences *)arg1 key:(struct __CFString *)arg2;	// IMP=0x000000010000d000
- (void)updatePrefs:(struct __SCPreferences *)arg1:(_Bool)arg2;	// IMP=0x000000010000bd0c
- (int)getModeratePressureVersion;	// IMP=0x000000010000bcfc
- (void)SaveProductString:(int)arg1;	// IMP=0x000000010000bcf4
- (void)probeAllSupervisorControlLoadingIndex;	// IMP=0x000000010000bce4
- (void)initializeReadPrefs:(struct __SCPreferences *)arg1;	// IMP=0x000000010000bcd4
- (void)hintComponentControlTakeAction;	// IMP=0x000000010000bcc4
- (int)getProductTotalPowerSensors;	// IMP=0x000000010000bcb4
- (int)getProductTotalSensors;	// IMP=0x000000010000bca4
- (struct iir_filter_t *)getProductFilterValues;	// IMP=0x000000010000bc94
- (unsigned long long)getMaxSensorValue;	// IMP=0x000000010000bc84
- (unsigned int)getRequiredCalibrationResistorSamples;	// IMP=0x000000010000bc74
- (int)getProductCalibrationSensorID;	// IMP=0x000000010000bc64
- (int)getProductCalibrationDefault;	// IMP=0x000000010000bc54
- (void *)getConfigurationFor:(struct __CFString *)arg1;	// IMP=0x000000010000bc48
- (void)createNewProduct:(struct __CFRunLoop *)arg1;	// IMP=0x000000010000b1c8
- (void)createConnectionToCT;	// IMP=0x000000010000b1b8
- (void)dealloc;	// IMP=0x000000010000b170
- (id)initWithConfig:(struct __CFDictionary *)arg1;	// IMP=0x000000010000b128

@end

