//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CommonProduct.h"

@class NSArray;

@interface tm53972ad9731c7b39eca2360f2cc4f798 : CommonProduct
{
    int _filteredTempRearCameraDie;	// 360 = 0x168
    int _filteredTempMic1;	// 364 = 0x16c
    int _filteredTempMic1_2DGrid;	// 368 = 0x170
    int _filteredTempMic2;	// 372 = 0x174
    NSArray *gridX;	// 376 = 0x178
    NSArray *gridY;	// 384 = 0x180
}

- (void)updateCoreAnalyticsInfo;	// IMP=0x0000000100028dc4
- (void)postDeviceTempMetric;	// IMP=0x0000000100028ca4
- (void)updateAggdInfo;	// IMP=0x0000000100028ab4
- (int *)compute2DGridTemps;	// IMP=0x0000000100028398
- (id)getGridY;	// IMP=0x00000001000282dc
- (id)getGridX;	// IMP=0x0000000100028220
- (void)updateAllThermalLoad:(_Bool)arg1;	// IMP=0x0000000100027ba0
- (int)arcVirtualTemperature;	// IMP=0x0000000100027b98
- (int)arcModuleTemperature;	// IMP=0x0000000100027b88
- (int)gasGaugeBatteryTemperature;	// IMP=0x0000000100027b78
- (void)resetVTFilterState;	// IMP=0x0000000100027b40
- (id)initProduct:(id)arg1;	// IMP=0x0000000100027ae8

@end

