//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CommonProduct.h"

@interface tm76592ae7abfee600e1da3e897fcf94c9 : CommonProduct
{
    int _filteredBacklightCurrentLI2;	// 360 = 0x168
    int TG0B[4];	// 364 = 0x16c
    int packagePower[4];	// 380 = 0x17c
    int predictedTG0B[6];	// 396 = 0x18c
    float predictionError;	// 420 = 0x1a4
}

- (struct __CFString *)copyFieldCurrentValueForIndex:(int)arg1;	// IMP=0x000000010002da04
- (struct __CFString *)copyHeaderForIndex:(int)arg1;	// IMP=0x000000010002d954
- (int)numberOfFields;	// IMP=0x000000010002d91c
- (void)updateCoreAnalyticsInfo;	// IMP=0x000000010002d484
- (void)predictSignal;	// IMP=0x000000010002d1a0
- (void)updateAggdInfo;	// IMP=0x000000010002cfe0
- (int)computeMaxCGTemp;	// IMP=0x000000010002cfc8
- (void)updateAllThermalLoad:(_Bool)arg1;	// IMP=0x000000010002caa0
- (int)arcModuleTemperature;	// IMP=0x000000010002ca90
- (int)gasGaugeBatteryTemperature;	// IMP=0x000000010002ca80
- (void)resetVTFilterState;	// IMP=0x000000010002ca6c
- (id)initProduct:(id)arg1;	// IMP=0x000000010002c9c4

@end

