//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CommonProduct.h"

@interface tma7fd905e57039223285aba8bf3f8241c : CommonProduct
{
}

- (void)updateAggdInfo;	// IMP=0x000000010001060c
- (void)updateAllThermalLoad:(_Bool)arg1;	// IMP=0x0000000100010494

@end

