//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIResponder.h>

@class MISSING_TYPE, NSArray;

__attribute__((visibility("hidden")))
@interface _TtC9Magnifier23MagnifierCommandManager : UIResponder
{
    MISSING_TYPE *nextResponderResolver;	// 8 = 0x8
    MISSING_TYPE *allKeyCommands;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x0000000100063c5c
- (id)init;	// IMP=0x0000000100063bc4
- (void)nextFilter:(id)arg1;	// IMP=0x0000000100063b70
- (void)previousFilter:(id)arg1;	// IMP=0x0000000100063d9c
- (void)increaseContrast:(id)arg1;	// IMP=0x0000000100063d8c
- (void)decreaseContrast:(id)arg1;	// IMP=0x0000000100063d7c
- (void)increaseBrightness:(id)arg1;	// IMP=0x0000000100063d6c
- (void)decreaseBrightness:(id)arg1;	// IMP=0x0000000100063d5c
- (void)increaseZoom:(id)arg1;	// IMP=0x0000000100063d4c
- (void)decreaseZoom:(id)arg1;	// IMP=0x0000000100063d3c
- (void)toggleFocus:(id)arg1;	// IMP=0x0000000100063dac
- (void)toggleTorch:(id)arg1;	// IMP=0x0000000100063d2c
@property(nonatomic, readonly) NSArray *keyCommands;
@property(nonatomic, readonly) UIResponder *nextResponder;

@end

