//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIResponder.h>

#import "UIWindowSceneDelegate-Protocol.h"

@class MISSING_TYPE, UIWindow;

__attribute__((visibility("hidden")))
@interface _TtC9Magnifier13SceneDelegate : UIResponder <UIWindowSceneDelegate>
{
    MISSING_TYPE *window;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00000001000ad7f0
- (id)init;	// IMP=0x00000001000ad80c
- (void)sceneDidEnterBackground:(id)arg1;	// IMP=0x00000001000ad650
- (void)sceneWillEnterForeground:(id)arg1;	// IMP=0x00000001000ad620
- (void)sceneWillResignActive:(id)arg1;	// IMP=0x00000001000ad508
- (void)sceneDidBecomeActive:(id)arg1;	// IMP=0x00000001000ad4e0
- (void)sceneDidDisconnect:(id)arg1;	// IMP=0x00000001000ad4d0
- (void)scene:(id)arg1 willConnectToSession:(id)arg2 options:(id)arg3;	// IMP=0x00000001000ad444
@property(nonatomic, retain) UIWindow *window; // @synthesize window;

@end

