//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "RBSAssertionObserving-Protocol.h"

@class NSString;

@interface _DASAssertion : NSObject <RBSAssertionObserving>
{
    _Bool _isRBSAssertion;	// 8 = 0x8
    int _pid;	// 12 = 0xc
    struct os_unfair_lock_s _lock;	// 16 = 0x10
    id _underlyingAssertion;	// 24 = 0x18
    CDUnknownBlockType _invalidationHandler;	// 32 = 0x20
    CDUnknownBlockType _warningHandler;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x0000000100080068
@property(nonatomic) struct os_unfair_lock_s lock; // @synthesize lock=_lock;
@property _Bool isRBSAssertion; // @synthesize isRBSAssertion=_isRBSAssertion;
@property(copy) CDUnknownBlockType warningHandler; // @synthesize warningHandler=_warningHandler;
@property(copy) CDUnknownBlockType invalidationHandler; // @synthesize invalidationHandler=_invalidationHandler;
@property(readonly) int pid; // @synthesize pid=_pid;
@property(readonly) id underlyingAssertion; // @synthesize underlyingAssertion=_underlyingAssertion;
- (void)dealloc;	// IMP=0x000000010007ff54
@property(readonly, copy) NSString *description;
- (void)assertionWillInvalidate:(id)arg1;	// IMP=0x000000010007fdf4
- (void)assertion:(id)arg1 didInvalidateWithError:(id)arg2;	// IMP=0x000000010007fd04
- (void)_callWarningHandler;	// IMP=0x000000010007fc40
- (void)_callInvalidationHandler:(_Bool)arg1;	// IMP=0x000000010007fa58
@property(readonly, getter=isValid) _Bool valid;
- (_Bool)invalidateAndKillWithExplanation:(id)arg1 code:(unsigned long long)arg2 error:(id *)arg3;	// IMP=0x000000010007f7c0
- (_Bool)_invalidateCallingHandler:(_Bool)arg1 withError:(id *)arg2;	// IMP=0x000000010007f638
- (_Bool)invalidateWithError:(id *)arg1;	// IMP=0x000000010007f624
- (_Bool)acquireWithError:(id *)arg1;	// IMP=0x000000010007f594
- (id)initWithRBSAssertion:(id)arg1 forPid:(int)arg2;	// IMP=0x000000010007f518
- (id)initWithBKSProcessAssertion:(id)arg1 forPid:(int)arg2;	// IMP=0x000000010007f3e8
- (id)_initWithUnderlyingAssertion:(id)arg1 forPid:(int)arg2;	// IMP=0x000000010007f368

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

