//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "_DASActivityPolicy-Protocol.h"

@class NSArray, NSMutableDictionary, NSString;
@protocol OS_dispatch_queue, OS_dispatch_source;

@interface _DASRequiresBuddyCompletePolicy : NSObject <_DASActivityPolicy>
{
    NSString *_policyName;	// 8 = 0x8
    NSArray *_triggers;	// 16 = 0x10
    NSObject<OS_dispatch_source> *_timer;	// 24 = 0x18
    NSObject<OS_dispatch_queue> *_queue;	// 32 = 0x20
    NSMutableDictionary *_buddyCompleteForUserIdentifier;	// 40 = 0x28
}

+ (id)policyInstance;	// IMP=0x000000010002216c
- (void).cxx_destruct;	// IMP=0x000000010002254c
@property(retain, nonatomic) NSMutableDictionary *buddyCompleteForUserIdentifier; // @synthesize buddyCompleteForUserIdentifier=_buddyCompleteForUserIdentifier;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) NSObject<OS_dispatch_source> *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) NSArray *triggers; // @synthesize triggers=_triggers;
@property(retain, nonatomic) NSString *policyName; // @synthesize policyName=_policyName;
- (id)responseForActivity:(id)arg1 withState:(id)arg2;	// IMP=0x000000010002237c
- (_Bool)buddyCompleteWithActivity:(id)arg1 withState:(id)arg2;	// IMP=0x00000001000221fc
- (double)weightForActivity:(id)arg1;	// IMP=0x00000001000221f0
- (_Bool)appliesToActivity:(id)arg1;	// IMP=0x00000001000221e0
- (_Bool)shouldIgnoreTrigger:(id)arg1 withState:(id)arg2;	// IMP=0x00000001000221d8
- (void)_updateCache;	// IMP=0x0000000100021e94
- (id)init;	// IMP=0x0000000100021ddc

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

