//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "_DASDataStore-Protocol.h"

@class NSString, _DASCoreDataStorage;

@interface _DASCoreDataStore : NSObject <_DASDataStore>
{
    _DASCoreDataStorage *_database;	// 8 = 0x8
}

+ (id)storageWithDirectory:(id)arg1 readOnly:(_Bool)arg2;	// IMP=0x0000000100016eb0
- (void).cxx_destruct;	// IMP=0x0000000100019e40
@property(retain, nonatomic) _DASCoreDataStorage *database; // @synthesize database=_database;
- (void)deleteActivitiesIfRequired;	// IMP=0x0000000100019ca0
- (void)deleteOldActivities;	// IMP=0x0000000100019b14
- (void)deleteActivity:(id)arg1;	// IMP=0x000000010001995c
- (_Bool)deleteStorageWithObliterationOption:(_Bool)arg1;	// IMP=0x00000001000198ec
- (void)updateActivityCanceled:(id)arg1;	// IMP=0x0000000100019780
- (void)updateActivityCompleted:(id)arg1;	// IMP=0x0000000100019614
- (void)updateActivityStarted:(id)arg1;	// IMP=0x00000001000194a8
- (void)loadAllGroups:(id)arg1;	// IMP=0x0000000100019208
- (void)loadStartedTasks:(id)arg1;	// IMP=0x0000000100018f24
- (void)loadPendingLaunchTasks:(id)arg1;	// IMP=0x0000000100018b44
- (void)saveActivity:(id)arg1 group:(id)arg2 triggers:(id)arg3 hasStarted:(_Bool)arg4;	// IMP=0x00000001000188e4
- (void)loadAllTasks:(id)arg1 startedTasks:(id)arg2;	// IMP=0x00000001000185dc
- (void)saveGroups:(id)arg1 activitiesArray:(id)arg2;	// IMP=0x00000001000183a4
- (void)saveGroup:(id)arg1 activity:(id)arg2;	// IMP=0x0000000100018198
- (void)saveGroup:(id)arg1;	// IMP=0x0000000100018038
- (void)createMOInMOC:(id)arg1 group:(id)arg2 activities:(id)arg3;	// IMP=0x0000000100017e14
- (void)saveActivities:(id)arg1 groups:(id)arg2 triggersArray:(id)arg3;	// IMP=0x00000001000179c0
- (void)saveActivity:(id)arg1 triggers:(id)arg2;	// IMP=0x0000000100017838
- (void)saveActivities:(id)arg1;	// IMP=0x00000001000175dc
- (void)saveActivity:(id)arg1;	// IMP=0x000000010001747c
- (void)createMOInMOC:(id)arg1 activity:(id)arg2 group:(id)arg3 triggers:(id)arg4;	// IMP=0x000000010001722c
- (void)mocSaveAndReset:(id)arg1;	// IMP=0x00000001000170d0
- (id)initWithDirectory:(id)arg1 readOnly:(_Bool)arg2;	// IMP=0x0000000100016f28
- (id)init;	// IMP=0x0000000100016f10

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

