/*
* This header is generated by classdump-dyld 1.0
* on Sunday, September 27, 2020 at 12:32:52 PM Mountain Standard Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /usr/lib/libAudioIssueDetector.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libAudioIssueDetector.dylib/libAudioIssueDetector.dylib-Structs.h>
#import <libobjc.A.dylib/ADAMServerProtocol.h>

@class NSXPCConnection, NSString, NSMutableDictionary;

@interface ADAMServerDelegate : NSObject <ADAMServerProtocol> {

	NSXPCConnection* _connection;
	NSString* _clientName;
	NSMutableDictionary* _dataTypeStatus;
	NSMutableDictionary* _configs;
	long long _error_code;
	os_unfair_lock_s _lock;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)unregisterDelegate;
-(void)deactivateAll;
-(void)setupConnection:(id)arg1 ;
-(void)stopMeasuringAudioSampleTypeWithIdentifier:(id)arg1 type:(unsigned)arg2 andReply:(/*^block*/id)arg3 ;
-(id)initWithConnection:(id)arg1 andErrorCode:(long long)arg2 ;
-(void)sendAudioSample:(id)arg1 withType:(unsigned)arg2 metadata:(id)arg3 ;
-(void)registerDelegate:(unsigned)arg1 ;
-(void)stopListeningToAudioSampleTypeWithIdentifier:(id)arg1 type:(unsigned)arg2 withReply:(/*^block*/id)arg3 ;
-(BOOL)datatypeSupportsONOFF:(unsigned)arg1 ;
-(void)configureAudioSampleTypeWithIdentifier:(id)arg1 type:(unsigned)arg2 configuration:(id)arg3 withReply:(/*^block*/id)arg4 ;
-(void)isMeasurementOnForAudioSampleType:(unsigned)arg1 withReply:(/*^block*/id)arg2 ;
-(void)sendAudioSample:(id)arg1 ;
-(id)errorWithCode:(long long)arg1 andReason:(id)arg2 ;
-(void)startMeasuringAudioSampleTypeWithIdentifier:(id)arg1 type:(unsigned)arg2 withConfiguration:(id)arg3 andReply:(/*^block*/id)arg4 ;
-(id)describeErrorCode:(long long)arg1 ;
-(void)getCurrentConfigurationForAudioSampleType:(unsigned)arg1 withReply:(/*^block*/id)arg2 ;
-(BOOL)isActive:(unsigned)arg1 ;
-(void)startListeningToAudioSampleWithIdentifier:(id)arg1 type:(unsigned)arg2 withReply:(/*^block*/id)arg3 ;
-(id)DatatypeTo4CC:(unsigned)arg1 ;
-(BOOL)verifyInvariantsWithReply:(/*^block*/id)arg1 ;
@end

