#import <libswiftNetwork.dylib/Network._NWProtocolUDP.h>
#import <libswiftNetwork.dylib/_TtCC7Network14_NWProtocolUDP7Options.h>
#import <libswiftNetwork.dylib/_TtCC7Network14_NWProtocolUDP8Metadata.h>
#import <libswiftNetwork.dylib/Network._NWProtocolTCP.h>
#import <libswiftNetwork.dylib/_TtCC7Network14_NWProtocolTCP7Options.h>
#import <libswiftNetwork.dylib/_TtCC7Network14_NWProtocolTCP8Metadata.h>
#import <libswiftNetwork.dylib/Network._NWProtocolIP.h>
#import <libswiftNetwork.dylib/_TtCC7Network13_NWProtocolIP7Options.h>
#import <libswiftNetwork.dylib/_TtCC7Network13_NWProtocolIP8Metadata.h>
#import <libswiftNetwork.dylib/Network._NWProtocolTLS.h>
#import <libswiftNetwork.dylib/_TtCC7Network14_NWProtocolTLS7Options.h>
#import <libswiftNetwork.dylib/_TtCC7Network14_NWProtocolTLS8Metadata.h>
#import <libswiftNetwork.dylib/Network.NWProtocolWebSocket.h>
#import <libswiftNetwork.dylib/_TtCC7Network19NWProtocolWebSocket7Options.h>
#import <libswiftNetwork.dylib/_TtCC7Network19NWProtocolWebSocket8Metadata.h>
#import <libswiftNetwork.dylib/Network.NWProtocolFramer.h>
#import <libswiftNetwork.dylib/_TtCC7Network16NWProtocolFramer10Definition.h>
#import <libswiftNetwork.dylib/_TtCC7Network16NWProtocolFramer7Options.h>
#import <libswiftNetwork.dylib/_TtCC7Network16NWProtocolFramer7Message.h>
#import <libswiftNetwork.dylib/_TtCC7Network16NWProtocolFramer8Instance.h>
#import <libswiftNetwork.dylib/Network.NWProtocolQUICStream.h>
#import <libswiftNetwork.dylib/_TtCC7Network20NWProtocolQUICStream7Options.h>
#import <libswiftNetwork.dylib/_TtCC7Network20NWProtocolQUICStream8Metadata.h>
#import <libswiftNetwork.dylib/Network.NWProtocolQUICConnection.h>
#import <libswiftNetwork.dylib/_TtCC7Network24NWProtocolQUICConnection7Options.h>
#import <libswiftNetwork.dylib/_TtCC7Network24NWProtocolQUICConnection8Metadata.h>
#import <libswiftNetwork.dylib/Network._NWConnection.h>
#import <libswiftNetwork.dylib/_TtCC7Network13_NWConnection14ContentContext.h>
#import <libswiftNetwork.dylib/_TtCC7Network12NWConnection25PendingDataTransferReport.h>
#import <libswiftNetwork.dylib/Network._NWProtocolDefinition.h>
#import <libswiftNetwork.dylib/Network._NWProtocolOptions.h>
#import <libswiftNetwork.dylib/Network._NWProtocolMetadata.h>
#import <libswiftNetwork.dylib/Network._NWProtocol.h>
#import <libswiftNetwork.dylib/Network._NWPathMonitor.h>
#import <libswiftNetwork.dylib/Network.NWBrowser.h>
#import <libswiftNetwork.dylib/Network.NWMulticastGroup.h>
#import <libswiftNetwork.dylib/Network.NWConnectionGroup.h>
#import <libswiftNetwork.dylib/_TtCC7Network17NWConnectionGroup7Message.h>
#import <libswiftNetwork.dylib/Network._NWListener.h>
#import <libswiftNetwork.dylib/Network._NWParameters.h>
#import <libswiftNetwork.dylib/_TtCC7Network13_NWParameters13ProtocolStack.h>
#import <libswiftNetwork.dylib/_TtCC7Network12NWParameters14PrivacyContext.h>
