//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "PageLoadTestRunner.h"

@interface ContentInteractionTestRunner : PageLoadTestRunner
{
    int _iterations;	// 64 = 0x40
}

@property(nonatomic) int iterations; // @synthesize iterations=_iterations;
- (void)stopSubtest:(id)arg1;	// IMP=0x00000001000ea100
- (void)startSubtest:(id)arg1;	// IMP=0x00000001000ea080
- (void)endTrackingFrameRate;	// IMP=0x00000001000ea02c
- (void)startTrackingFrameRate;	// IMP=0x00000001000e9fd8
- (_Bool)startPageAction:(id)arg1;	// IMP=0x00000001000e9f50
- (id)pageWebView;	// IMP=0x00000001000e9eb4
- (id)initWithTestName:(id)arg1 browserController:(id)arg2;	// IMP=0x00000001000e9e28

@end

