//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, UIAlertAction;

@interface TabLimitCleanupGroup : NSObject
{
    UIAlertAction *_action;	// 8 = 0x8
    NSString *_message;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x0000000100122b18
@property(readonly, copy, nonatomic) NSString *message; // @synthesize message=_message;
@property(readonly, nonatomic) UIAlertAction *action; // @synthesize action=_action;
- (id)initWithAlertMesssage:(id)arg1 actionTitle:(id)arg2 tabs:(id)arg3 browserWindowController:(id)arg4 resultHandler:(CDUnknownBlockType)arg5;	// IMP=0x0000000100122690

@end

