//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "CBCentralManagerDelegate-Protocol.h"
#import "CBCentralManagerPrivateDelegate-Protocol.h"
#import "EPResourceOwnerDelegate-Protocol.h"

@class EPCentralManager, NSString, NSUUID;
@protocol OS_dispatch_source;

@interface EPCheckBluetoothForIRK : NSObject <CBCentralManagerDelegate, CBCentralManagerPrivateDelegate, EPResourceOwnerDelegate>
{
    CDUnknownBlockType _completion;	// 8 = 0x8
    EPCentralManager *_manager;	// 16 = 0x10
    NSUUID *_bluetoothUUID;	// 24 = 0x18
    NSObject<OS_dispatch_source> *_timer;	// 32 = 0x20
    _Bool _scanning;	// 40 = 0x28
    EPCheckBluetoothForIRK *_circularReference;	// 48 = 0x30
}

- (void).cxx_destruct;	// IMP=0x000000010006bed8
- (void)checkForIRK;	// IMP=0x000000010006bb68
- (void)callCompletionWithAvailability:(unsigned long long)arg1;	// IMP=0x000000010006b9d0
- (void)startTimeout;	// IMP=0x000000010006b87c
- (void)centralManagerDidUpdateState:(id)arg1;	// IMP=0x000000010006b870
- (void)resourceAvailabilityDidChange:(id)arg1;	// IMP=0x000000010006b864
- (id)initWithBTUUID:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010006b658

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

