//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "EPSagaOperand-Protocol.h"

@class EPRoutingSlip, NSString;
@protocol NSObject;

@interface EPSagaOperandDynamic : NSObject <EPSagaOperand>
{
    EPRoutingSlip *_routingSlip;	// 8 = 0x8
    NSString *_entryName;	// 16 = 0x10
    NSString *_operandName;	// 24 = 0x18
}

+ (_Bool)supportsSecureCoding;	// IMP=0x00000001000e8f88
- (void).cxx_destruct;	// IMP=0x00000001000e91f4
@property(readonly, nonatomic) NSString *operandName; // @synthesize operandName=_operandName;
@property(readonly, nonatomic) NSString *entryName; // @synthesize entryName=_entryName;
@property(nonatomic) __weak EPRoutingSlip *routingSlip; // @synthesize routingSlip=_routingSlip;
@property(readonly, copy) NSString *description;
- (void)encodeWithCoder:(id)arg1;	// IMP=0x00000001000e9060
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001000e8f90
@property(readonly, nonatomic) id <NSObject> value;
- (id)initWithEntryName:(id)arg1 operandName:(id)arg2;	// IMP=0x00000001000e8e18

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

