//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MTASleepSetupBaseViewController.h"

@class MTABedtimeRepeatControl, OBTrayButton;

@interface MTASleepScheduleViewController : MTASleepSetupBaseViewController
{
    MTABedtimeRepeatControl *_repeatControl;	// 8 = 0x8
    OBTrayButton *_nextButton;	// 16 = 0x10
}

+ (id)setupController;	// IMP=0x0000000100077a18
- (void).cxx_destruct;	// IMP=0x0000000100078f5c
@property(retain, nonatomic) OBTrayButton *nextButton; // @synthesize nextButton=_nextButton;
@property(retain, nonatomic) MTABedtimeRepeatControl *repeatControl; // @synthesize repeatControl=_repeatControl;
- (void)proceedToTracking;	// IMP=0x0000000100078d90
- (void)completeOnboading;	// IMP=0x0000000100078c1c
- (void)nextButtonAction:(id)arg1;	// IMP=0x0000000100078ae8
- (void)repeatControlChanged:(id)arg1;	// IMP=0x00000001000789c8
- (void)setupRepeatControl;	// IMP=0x0000000100078850
- (void)viewWillLayoutSubviews;	// IMP=0x00000001000787a4
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x00000001000786b4
- (void)viewDidLoad;	// IMP=0x000000010007861c
- (void)setupConstraints;	// IMP=0x0000000100077b68

@end

