//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "MTAStateManagement-Protocol.h"
#import "MTAStopwatchControlsTarget-Protocol.h"
#import "MTAStopwatchPagingViewControllerDelegate-Protocol.h"

@class CADisplayLink, MTAAnalogStopwatchView, MTAStopwatchController, MTAStopwatchLapTableHeaderView, MTAStopwatchLapTableViewController, MTAStopwatchPagingViewController, MTUITimeView, NSArray, NSDate, NSLayoutConstraint, NSMutableArray, NSString, NSTimer, NSUserActivity, UIImageView, UIPageControl, UIView;

@interface MTAStopwatchViewController : UIViewController <MTAStopwatchControlsTarget, MTAStopwatchPagingViewControllerDelegate, MTAStateManagement>
{
    CADisplayLink *_displayLink;	// 8 = 0x8
    NSDate *_startTime;	// 16 = 0x10
    double _offset;	// 24 = 0x18
    double _currentInterval;	// 32 = 0x20
    double _previousLapsTotalInterval;	// 40 = 0x28
    NSMutableArray *_laps;	// 48 = 0x30
    _Bool _isTimerRunning;	// 56 = 0x38
    NSTimer *_restoreIdleTimerTimer;	// 64 = 0x40
    unsigned long long _mode;	// 72 = 0x48
    NSUserActivity *_userActivity;	// 80 = 0x50
    MTAStopwatchController *_stopwatchController;	// 88 = 0x58
    MTAStopwatchLapTableViewController *_lapTableController;	// 96 = 0x60
    MTAStopwatchLapTableHeaderView *_tableHeaderView;	// 104 = 0x68
    UIImageView *_lapButtonOccludingView;	// 112 = 0x70
    UIImageView *_startButtonOccludingView;	// 120 = 0x78
    MTAStopwatchPagingViewController *_pagingViewController;	// 128 = 0x80
    UIPageControl *_pageControl;	// 136 = 0x88
    UIView *_analogStopwatchContainer;	// 144 = 0x90
    MTAAnalogStopwatchView *_analogStopwatch;	// 152 = 0x98
    UIView *_digitalStopwatchContainer;	// 160 = 0xa0
    MTUITimeView *_timeView;	// 168 = 0xa8
    NSArray *_constraints;	// 176 = 0xb0
    NSLayoutConstraint *_startButtonTopConstraint;	// 184 = 0xb8
    NSLayoutConstraint *_lapButtonTopConstraint;	// 192 = 0xc0
    NSLayoutConstraint *_startButtonWidthConstraint;	// 200 = 0xc8
    NSLayoutConstraint *_lapButtonWidthConstraint;	// 208 = 0xd0
    NSLayoutConstraint *_timeViewBaselineOffsetConstraint;	// 216 = 0xd8
    struct CGSize _latestLayoutSize;	// 224 = 0xe0
}

- (void).cxx_destruct;	// IMP=0x000000010004bd58
@property(retain, nonatomic) NSLayoutConstraint *timeViewBaselineOffsetConstraint; // @synthesize timeViewBaselineOffsetConstraint=_timeViewBaselineOffsetConstraint;
@property(retain, nonatomic) NSLayoutConstraint *lapButtonWidthConstraint; // @synthesize lapButtonWidthConstraint=_lapButtonWidthConstraint;
@property(retain, nonatomic) NSLayoutConstraint *startButtonWidthConstraint; // @synthesize startButtonWidthConstraint=_startButtonWidthConstraint;
@property(retain, nonatomic) NSLayoutConstraint *lapButtonTopConstraint; // @synthesize lapButtonTopConstraint=_lapButtonTopConstraint;
@property(retain, nonatomic) NSLayoutConstraint *startButtonTopConstraint; // @synthesize startButtonTopConstraint=_startButtonTopConstraint;
@property(nonatomic) struct CGSize latestLayoutSize; // @synthesize latestLayoutSize=_latestLayoutSize;
@property(retain, nonatomic) NSArray *constraints; // @synthesize constraints=_constraints;
@property(retain, nonatomic) MTUITimeView *timeView; // @synthesize timeView=_timeView;
@property(retain, nonatomic) UIView *digitalStopwatchContainer; // @synthesize digitalStopwatchContainer=_digitalStopwatchContainer;
@property(retain, nonatomic) MTAAnalogStopwatchView *analogStopwatch; // @synthesize analogStopwatch=_analogStopwatch;
@property(retain, nonatomic) UIView *analogStopwatchContainer; // @synthesize analogStopwatchContainer=_analogStopwatchContainer;
@property(retain, nonatomic) UIPageControl *pageControl; // @synthesize pageControl=_pageControl;
@property(retain, nonatomic) MTAStopwatchPagingViewController *pagingViewController; // @synthesize pagingViewController=_pagingViewController;
@property(retain, nonatomic) UIImageView *startButtonOccludingView; // @synthesize startButtonOccludingView=_startButtonOccludingView;
@property(retain, nonatomic) UIImageView *lapButtonOccludingView; // @synthesize lapButtonOccludingView=_lapButtonOccludingView;
@property(retain, nonatomic) MTAStopwatchLapTableHeaderView *tableHeaderView; // @synthesize tableHeaderView=_tableHeaderView;
@property(retain, nonatomic) MTAStopwatchLapTableViewController *lapTableController; // @synthesize lapTableController=_lapTableController;
@property(retain, nonatomic) MTAStopwatchController *stopwatchController; // @synthesize stopwatchController=_stopwatchController;
- (void)resumeLapTimer;	// IMP=0x000000010004b9d8
- (void)resetLapTimer;	// IMP=0x000000010004b838
- (void)lapLapTimer;	// IMP=0x000000010004b6ac
- (void)pauseLapTimer;	// IMP=0x000000010004b54c
- (void)startLapTimer;	// IMP=0x000000010004b3cc
- (double)runningTotalForLap:(long long)arg1;	// IMP=0x000000010004b320
- (void)updateTime;	// IMP=0x000000010004b09c
- (void)_tick:(id)arg1;	// IMP=0x000000010004b090
- (double)_timeAdjustedFor30fpsDisplay:(double)arg1;	// IMP=0x000000010004afc8
- (void)_restoreIdleTimer;	// IMP=0x000000010004af54
- (void)_stopTimer;	// IMP=0x000000010004ae68
- (void)_startTimer;	// IMP=0x000000010004ac5c
- (void)_pageControlValueChanged:(id)arg1;	// IMP=0x000000010004abd4
- (void)_clearAllLaps;	// IMP=0x000000010004ab04
- (void)_addLap:(double)arg1;	// IMP=0x000000010004a9e4
- (void)handleStopStopwatchShortcutAction;	// IMP=0x000000010004a9a0
- (void)handleStartStopwatchShortcutAction;	// IMP=0x000000010004a8f0
- (id)defaultShortcutItem;	// IMP=0x000000010004a884
- (id)stopStopwatchShortcutItem;	// IMP=0x000000010004a79c
- (id)startStopwatchShortcutItemForMode:(unsigned long long)arg1;	// IMP=0x000000010004a6a0
- (id)shortcutItemForMode:(unsigned long long)arg1;	// IMP=0x000000010004a660
- (id)shortcutItemForCurrentState;	// IMP=0x000000010004a648
- (void)updateShortcutItemForCurrentState;	// IMP=0x000000010004a43c
- (void)saveState;	// IMP=0x000000010004a1f8
- (void)reloadState;	// IMP=0x0000000100049f00
- (void)stopwatchPagingViewController:(id)arg1 didPage:(unsigned long long)arg2;	// IMP=0x0000000100049eb8
- (_Bool)prefersStatusBarHidden;	// IMP=0x0000000100049dec
- (void)viewDidLayoutSubviews;	// IMP=0x0000000100049c30
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x0000000100049b94
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x0000000100049ab4
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0000000100049a44
- (void)updateViewConstraints;	// IMP=0x00000001000475b0
- (_Bool)shouldUseRegularLayout;	// IMP=0x0000000100047548
- (void)handleContentSizeCategoryChange:(id)arg1;	// IMP=0x00000001000470f0
- (void)viewDidLoad;	// IMP=0x0000000100046f68
- (void)loadView;	// IMP=0x0000000100046094
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;	// IMP=0x0000000100045d54
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x0000000100045cf4
- (void)updateTimeViewFont;	// IMP=0x0000000100045bec
- (void)setMode:(unsigned long long)arg1;	// IMP=0x0000000100045b60
- (Class)tableCellClass;	// IMP=0x0000000100045b54
- (void)handleLocaleChange;	// IMP=0x0000000100045a70
- (void)dealloc;	// IMP=0x0000000100045a00
- (id)init;	// IMP=0x00000001000457b8
- (_Bool)_canShowWhileLocked;	// IMP=0x00000001000457b0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

