//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol TimerControlsTarget <NSObject>
- (void)showSoundPicker:(id)arg1;
- (void)pauseResumeTimer:(id)arg1;
- (void)cancelTimer:(id)arg1;
- (void)startTimer:(id)arg1;
@end

