//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "PTPCameraItem.h"

__attribute__((visibility("hidden")))
@interface PTPCameraFolder : PTPCameraItem
{
}

- (id)newFolderWithObjectInfo:(id)arg1 inFolder:(id)arg2 notify:(_Bool)arg3;	// IMP=0x0000000100022888
- (void)newItemWithObjectInfo:(id)arg1 notify:(_Bool)arg2;	// IMP=0x0000000100022480
- (void)enumerateContent:(id)arg1 withOrder:(long long)arg2;	// IMP=0x0000000100021738
- (void)flushNotifications:(id)arg1;	// IMP=0x00000001000215f8
- (void)refreshInfo;	// IMP=0x00000001000215a4
- (void)dealloc;	// IMP=0x0000000100021550
- (id)initWithStorageID:(unsigned int)arg1 objHandle:(unsigned int)arg2 parent:(id)arg3 initiator:(id)arg4;	// IMP=0x00000001000214f4

@end

