//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MCNewPayloadHandler.h"

@interface MCNewAPNPayloadHandler : MCNewPayloadHandler
{
}

- (void)didRemoveOldGlobalRestrictions:(id)arg1 newGlobalRestrictions:(id)arg2;	// IMP=0x0000000100041fe8
- (void)didInstallOldGlobalRestrictions:(id)arg1 newGlobalRestrictions:(id)arg2;	// IMP=0x0000000100041fdc
- (void)_sendNotifications;	// IMP=0x0000000100041efc
- (void)migrateDefaults;	// IMP=0x0000000100041dd4
- (void)unsetAside;	// IMP=0x0000000100041d60
- (void)setAside;	// IMP=0x0000000100041cec
- (void)remove;	// IMP=0x0000000100041c30
- (void)_remove;	// IMP=0x0000000100041b64
- (_Bool)installWithInstaller:(id)arg1 options:(id)arg2 interactionClient:(id)arg3 outError:(id *)arg4;	// IMP=0x00000001000417f8
- (_Bool)_install;	// IMP=0x0000000100041748
- (void)_notifyCoreTelephonyOfAPNChange;	// IMP=0x0000000100041668

@end

