//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "FMFURLSession-Protocol.h"
#import "NSURLSessionDelegate-Protocol.h"

@class NSString, NSURLSession;
@protocol FMFURLSessionDelegate;

@interface FMFNSURLSession : NSObject <FMFURLSession, NSURLSessionDelegate>
{
    NSURLSession *_session;	// 8 = 0x8
    NSObject<FMFURLSessionDelegate> *_delegate;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x0000000100033e20
@property(nonatomic) __weak NSObject<FMFURLSessionDelegate> *delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSURLSession *session; // @synthesize session=_session;
- (void)URLSession:(id)arg1 didReceiveChallenge:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x0000000100033d44
- (void)URLSession:(id)arg1 didBecomeInvalidWithError:(id)arg2;	// IMP=0x0000000100033cc4
- (void)getAllTasksWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x0000000100033c58
- (id)downloadTaskWithRequest:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0000000100033bbc
- (id)dataTaskWithRequest:(id)arg1;	// IMP=0x0000000100033b3c
- (id)dataTaskWithRequest:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0000000100033aa0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(nonatomic) double requestTimeout;
@property(readonly) Class superclass;

@end

