//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MCMXPCMessageBase.h"

@class NSURL;

@interface MCMXPCMessageRepairUserData : MCMXPCMessageBase
{
    NSURL *_url;	// 8 = 0x8
    const char *_sandboxToken;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x000000010002738c
@property(readonly, nonatomic) const char *sandboxToken; // @synthesize sandboxToken=_sandboxToken;
@property(readonly, nonatomic) NSURL *url; // @synthesize url=_url;
- (_Bool)canBeHandledLocally;	// IMP=0x0000000100027324
- (id)initWithXPCObject:(id)arg1 clientConnection:(id)arg2 error:(unsigned long long *)arg3;	// IMP=0x000000010002720c

@end

