//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import "NSCopying-Protocol.h"

@class NSMutableArray, NSString;

@interface ExposureNotificationDiagnosisInfo : PBCodable <NSCopying>
{
    NSMutableArray *_diagnosisKeys;	// 8 = 0x8
    int _diagnosisStatus;	// 16 = 0x10
    NSString *_platform;	// 24 = 0x18
}

+ (Class)diagnosisKeysType;	// IMP=0x0000000100079b60
- (void).cxx_destruct;	// IMP=0x000000010007a8f4
@property(retain, nonatomic) NSString *platform; // @synthesize platform=_platform;
@property(retain, nonatomic) NSMutableArray *diagnosisKeys; // @synthesize diagnosisKeys=_diagnosisKeys;
@property(nonatomic) int diagnosisStatus; // @synthesize diagnosisStatus=_diagnosisStatus;
- (void)mergeFrom:(id)arg1;	// IMP=0x000000010007a720
- (unsigned long long)hash;	// IMP=0x000000010007a6ac
- (_Bool)isEqual:(id)arg1;	// IMP=0x000000010007a5c0
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x000000010007a404
- (void)copyTo:(id)arg1;	// IMP=0x000000010007a300
- (void)writeTo:(id)arg1;	// IMP=0x000000010007a1a4
- (_Bool)readFrom:(id)arg1;	// IMP=0x000000010007a19c
- (id)dictionaryRepresentation;	// IMP=0x0000000100079c38
- (id)description;	// IMP=0x0000000100079b84
@property(readonly, nonatomic) _Bool hasPlatform;
- (id)diagnosisKeysAtIndex:(unsigned long long)arg1;	// IMP=0x0000000100079b48
- (unsigned long long)diagnosisKeysCount;	// IMP=0x0000000100079b30
- (void)addDiagnosisKeys:(id)arg1;	// IMP=0x0000000100079abc
- (void)clearDiagnosisKeys;	// IMP=0x0000000100079aa4
- (int)StringAsDiagnosisStatus:(id)arg1;	// IMP=0x0000000100079a30
- (id)diagnosisStatusAsString:(int)arg1;	// IMP=0x00000001000799c8

@end

