//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIControl.h>

#import "UIGestureRecognizerDelegate-Protocol.h"

@class MISSING_TYPE, _TtC8AppStore16DynamicTypeLabel;

@interface _TtC8AppStore11OfferButton : UIControl <UIGestureRecognizerDelegate>
{
    MISSING_TYPE *effectShape;	// 8 = 0x8
    MISSING_TYPE *outlineShape;	// 16 = 0x10
    MISSING_TYPE *imageView;	// 24 = 0x18
    MISSING_TYPE *label;	// 32 = 0x20
    MISSING_TYPE *subtitleLabel;	// 40 = 0x28
    MISSING_TYPE *presenter;	// 48 = 0x30
    MISSING_TYPE *layoutDelegate;	// 80 = 0x50
    MISSING_TYPE *isEnabledObserver;	// 88 = 0x58
    MISSING_TYPE *isConfigurationLayoutEnabled;	// 120 = 0x78
    MISSING_TYPE *_configuration;	// 128 = 0x80
    MISSING_TYPE *cachedIntrinsicContentSize;	// 168 = 0xa8
}

- (void).cxx_destruct;	// IMP=0x000000010006ae60
@property(nonatomic, readonly) _TtC8AppStore16DynamicTypeLabel *accessibilityOfferSubtitleLabel;
@property(nonatomic, readonly) _TtC8AppStore16DynamicTypeLabel *accessibilityOfferLabel;
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x000000010006b6e8
- (void)setEnabled:(_Bool)arg1;	// IMP=0x000000010006b4f8
- (void)tintColorDidChange;	// IMP=0x000000010006b2d0
@property(nonatomic) _Bool highlighted;
- (_Bool)isHighlighted;	// IMP=0x000000010006b1ac
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;	// IMP=0x000000010006b164
@property(nonatomic, readonly) struct CGSize intrinsicContentSize;
- (void)invalidateIntrinsicContentSize;	// IMP=0x000000010006afec
- (void)layoutSubviews;	// IMP=0x000000010006af08
- (void)dealloc;	// IMP=0x000000010006adbc
- (id)initWithCoder:(id)arg1;	// IMP=0x000000010006ad10
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x000000010006acf0
@property(nonatomic) struct CGRect frame;
- (void)accessibilityShowProgress:(double)arg1;	// IMP=0x00000001002eb4a4
- (void)accessibilityShowRedownload;	// IMP=0x00000001002eb494
- (void)accessibilityShowText:(id)arg1;	// IMP=0x00000001002eb484
- (void)accessibilityShowLoading;	// IMP=0x00000001002eb474

@end

