//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICollectionReusableView.h>

@class MISSING_TYPE;

@interface _TtC8AppStore22SearchTransparencyView : UICollectionReusableView
{
    MISSING_TYPE *linkedLabel;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0000000100154da4
- (void)prepareForReuse;	// IMP=0x0000000100154d48
- (void)layoutSubviews;	// IMP=0x0000000100154c74
- (id)initWithCoder:(id)arg1;	// IMP=0x0000000100154970
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100154950

@end

