//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class MISSING_TYPE;

@interface _TtC8AppStore12IconGridView : UIView
{
    MISSING_TYPE *configuration;	// 8 = 0x8
    MISSING_TYPE *artworkViews;	// 56 = 0x38
    MISSING_TYPE *viewPool;	// 0 = 0x0
    MISSING_TYPE *impressionableArtworks;	// 2831252477 = 0xa8c17bfd
    MISSING_TYPE *artworkLoader;	// 2852258785 = 0xaa0203e1
}

- (void).cxx_destruct;	// IMP=0x000000010031ca3c
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x000000010031c9dc
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;	// IMP=0x000000010031bf80
- (void)layoutSubviews;	// IMP=0x000000010031bf54
- (id)initWithCoder:(id)arg1;	// IMP=0x000000010031bd00

@end

