//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITableViewHeaderFooterView.h>

@interface _TtC8AppStoreP33_4C3663C3DFD2A515EF9390A728D5E4B110HeaderView : UITableViewHeaderFooterView
{
}

- (id)initWithCoder:(id)arg1;	// IMP=0x00000001002cf008
- (id)initWithReuseIdentifier:(id)arg1;	// IMP=0x00000001002cef80
- (void)layoutSubviews;	// IMP=0x00000001002cef08

@end

