//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITapGestureRecognizer.h>

@class MISSING_TYPE;

@interface _TtC8AppStore26TapActionGestureRecognizer : UITapGestureRecognizer
{
    MISSING_TYPE *action;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00000001001436dc
- (id)initWithTarget:(id)arg1 action:(SEL)arg2;	// IMP=0x00000001001436f8
- (void)execute;	// IMP=0x000000010014367c

@end

