//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC8AppStore31PurchasesCollectionViewDelegate.h"

#import "UICollectionViewDelegateTableLayout-Protocol.h"

@interface _TtC8AppStore31PurchasesCollectionViewDelegate (AppStore) <UICollectionViewDelegateTableLayout>
- (id)collectionView:(id)arg1 tableLayout:(id)arg2 trailingSwipeActionsConfigurationForRowAtIndexPath:(id)arg3;	// IMP=0x000000010014a13c
- (double)collectionView:(id)arg1 tableLayout:(id)arg2 heightForRowAtIndexPath:(id)arg3;	// IMP=0x0000000100149eb4
- (double)collectionView:(id)arg1 tableLayout:(id)arg2 heightForHeaderInSection:(long long)arg3;	// IMP=0x0000000100149dfc
@end

