//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class MISSING_TYPE;

@interface _TtC8AppStore32EditorialQuoteCollectionViewCell : UICollectionViewCell
{
    MISSING_TYPE *quoteLabel;	// 8 = 0x8
    MISSING_TYPE *attributionLabel;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x000000010010fc28
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x000000010010fba4
- (void)layoutSubviews;	// IMP=0x000000010010fa9c
- (id)initWithCoder:(id)arg1;	// IMP=0x000000010010f838
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x000000010010f818

@end

