//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class MISSING_TYPE, _TtC8AppStore16DynamicTypeLabel;

@interface _TtC8AppStore29LargeLockupCollectionViewCell : UICollectionViewCell
{
    MISSING_TYPE *avatarShowcase;	// 8 = 0x8
    MISSING_TYPE *artworkView;	// 16 = 0x10
    MISSING_TYPE *preferredArtworkSize;	// 24 = 0x18
    MISSING_TYPE *headingLabel;	// 40 = 0x28
    MISSING_TYPE *titleLabel;	// 48 = 0x30
    MISSING_TYPE *subtitleLabel;	// 56 = 0x38
    MISSING_TYPE *tertiaryTitleLabel;	// 64 = 0x40
}

- (void).cxx_destruct;	// IMP=0x00000001000e16a0
@property(nonatomic, readonly) _TtC8AppStore16DynamicTypeLabel *accessibilitySubtitleLabel;
@property(nonatomic, readonly) _TtC8AppStore16DynamicTypeLabel *accessibilityTitleLabel;
- (void)layoutSubviews;	// IMP=0x00000001000e1248
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001000e0f58
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001000e0f38

@end

