//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class CDDataMigrator, CDKnowledgeDaemon, CDPeopleDaemon, _CDSpotlightItemRecorder;

@interface CDServiceManager : NSObject
{
    CDKnowledgeDaemon *_knowledgeDaemon;	// 8 = 0x8
    CDPeopleDaemon *_peopleDaemon;	// 16 = 0x10
    _CDSpotlightItemRecorder *_spotlightRecorder;	// 24 = 0x18
    CDDataMigrator *_dataMigrator;	// 32 = 0x20
}

+ (id)sharedInstance;	// IMP=0x0000000100004f4c
- (void).cxx_destruct;	// IMP=0x00000001000053f8
@property(readonly, nonatomic) CDDataMigrator *dataMigrator; // @synthesize dataMigrator=_dataMigrator;
@property(readonly, nonatomic) _CDSpotlightItemRecorder *spotlightRecorder; // @synthesize spotlightRecorder=_spotlightRecorder;
@property(readonly, nonatomic) CDPeopleDaemon *peopleDaemon; // @synthesize peopleDaemon=_peopleDaemon;
@property(readonly, nonatomic) CDKnowledgeDaemon *knowledgeDaemon; // @synthesize knowledgeDaemon=_knowledgeDaemon;
- (void)setupServices;	// IMP=0x0000000100005284
- (id)init;	// IMP=0x0000000100004fb8

@end

