/*
* This header is generated by classdump-dyld 1.0
* on Sunday, September 27, 2020 at 11:52:35 AM Mountain Standard Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/NSPredicateVisitor.h>

@class NSSet;

@interface RTPredicateInspector : NSObject <NSPredicateVisitor> {

	BOOL _predicateContainsSubstitutionVariables;
	NSSet* _substitutionVariables;

}

@property (assign,nonatomic) BOOL predicateContainsSubstitutionVariables;              //@synthesize predicateContainsSubstitutionVariables=_predicateContainsSubstitutionVariables - In the implementation block
@property (nonatomic,retain) NSSet * substitutionVariables;                            //@synthesize substitutionVariables=_substitutionVariables - In the implementation block
-(void)visitPredicateExpression:(id)arg1 ;
-(void)visitPredicate:(id)arg1 ;
-(BOOL)predicateContainsSubstitutionVariables;
-(void)setPredicateContainsSubstitutionVariables:(BOOL)arg1 ;
-(void)setSubstitutionVariables:(NSSet *)arg1 ;
-(void)_inspectExpression:(id)arg1 ;
-(BOOL)predicate:(id)arg1 referencesSubstitutionVariablesFromSet:(id)arg2 ;
-(void)visitPredicateOperator:(id)arg1 ;
-(NSSet *)substitutionVariables;
@end

