//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class RSDRemoteNCMDevice;

@interface RSDNCMInterface : NSObject
{
    unsigned int _index;	// 8 = 0x8
    unsigned int _service;	// 12 = 0xc
    unsigned int _notification;	// 16 = 0x10
    char *_name;	// 24 = 0x18
    RSDRemoteNCMDevice *_device;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x000000010000d03c
@property(retain, nonatomic) RSDRemoteNCMDevice *device; // @synthesize device=_device;
@property(nonatomic) unsigned int notification; // @synthesize notification=_notification;
@property(nonatomic) unsigned int service; // @synthesize service=_service;
@property(nonatomic) char *name; // @synthesize name=_name;
@property(nonatomic) unsigned int index; // @synthesize index=_index;
- (void)dealloc;	// IMP=0x000000010000ceac
- (void)updateOnLinkActive;	// IMP=0x000000010000cb08
- (id)initWithService:(unsigned int)arg1 notification:(struct IONotificationPort *)arg2 callback:(CDUnknownFunctionPointerType)arg3;	// IMP=0x000000010000c9a8

@end

