//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Rapport/RPRemoteDisplaySession.h>

@class MISSING_TYPE, NSString, RPRemoteDisplayDevice;

@interface _TtC12SidecarRelay11TestSession : RPRemoteDisplaySession
{
    MISSING_TYPE *testDevice;	// 8 = 0x8
    MISSING_TYPE *valid;	// 16 = 0x10
    MISSING_TYPE *handlers;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x000000010001d4f0
- (id)init;	// IMP=0x000000010001d554
- (void)sendRequestID:(id)arg1 request:(id)arg2 destinationID:(id)arg3 options:(id)arg4 responseHandler:(CDUnknownBlockType)arg5;	// IMP=0x000000010001d398
- (void)deregisterRequestID:(id)arg1;	// IMP=0x000000010001d2d8
- (void)registerRequestID:(id)arg1 options:(id)arg2 handler:(CDUnknownBlockType)arg3;	// IMP=0x000000010001d234
- (void)invalidate;	// IMP=0x000000010001d200
- (void)activateWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010001cf8c
- (void)sendEventID:(id)arg1 event:(id)arg2 destinationID:(id)arg3 options:(id)arg4 completion:(CDUnknownBlockType)arg5;	// IMP=0x000000010001ce04
- (void)deregisterEventID:(id)arg1;	// IMP=0x000000010001c4b8
- (void)registerEventID:(id)arg1 options:(id)arg2 handler:(CDUnknownBlockType)arg3;	// IMP=0x000000010001c2d8
@property(nonatomic, retain) RPRemoteDisplayDevice *destinationDevice;
@property(nonatomic, readonly) NSString *description;

@end

