//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSXPCListenerDelegate-Protocol.h"

@class MISSING_TYPE;

@interface _TtCC12SidecarRelay5Relay11MachService : NSObject <NSXPCListenerDelegate>
{
    MISSING_TYPE *xpcListener;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0000000100030620
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;	// IMP=0x000000010003059c
- (id)init;	// IMP=0x00000001000301f0

@end

