//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC12searchpartydP33_8F16B571022752B5A0333344EAF60C1619SchedulerTrampoline : NSObject
{
    MISSING_TYPE *implementation;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00000001000f4a1c
- (id)init;	// IMP=0x00000001000f4a38
- (void)publishImmediatelyWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00000001000f494c
- (void)schedulePublishWakeWithInformation:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00000001000f4894

@end

