//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "CoreTelephonyClientSubscriberDelegate-Protocol.h"
#import "TSSIMUnlockDetailViewControllerDelegate-Protocol.h"
#import "TSSIMUnlockListFooterViewDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class CoreTelephonyClient, NSMutableArray, NSMutableDictionary, NSString, TSSIMUnlockListFooterView, TSSIMUnlockListHeaderView, TSSIMUnlockListTableFooterView, UIBarButtonItem, UITableView;
@protocol TSSIMUnlockListViewControllerDelegate;

@interface TSSIMUnlockListViewController : UIViewController <CoreTelephonyClientSubscriberDelegate, UITableViewDataSource, UITableViewDelegate, TSSIMUnlockDetailViewControllerDelegate, TSSIMUnlockListFooterViewDelegate, UIGestureRecognizerDelegate>
{
    _Bool _suppressCancellation;	// 8 = 0x8
    CoreTelephonyClient *_telephonyClient;	// 16 = 0x10
    UIBarButtonItem *_cancelButtonItem;	// 24 = 0x18
    UITableView *_tableView;	// 32 = 0x20
    TSSIMUnlockListHeaderView *_headerView;	// 40 = 0x28
    TSSIMUnlockListFooterView *_footerView;	// 48 = 0x30
    TSSIMUnlockListTableFooterView *_tableFooterView;	// 56 = 0x38
    NSMutableArray *_subscriptionContexts;	// 64 = 0x40
    NSMutableDictionary *_subscriptionActions;	// 72 = 0x48
    id <TSSIMUnlockListViewControllerDelegate> _delegate;	// 80 = 0x50
}

- (void).cxx_destruct;	// IMP=0x000000010000a9a8
@property(nonatomic) __weak id <TSSIMUnlockListViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, copy, nonatomic) NSMutableDictionary *subscriptionActions; // @synthesize subscriptionActions=_subscriptionActions;
@property(readonly, copy, nonatomic) NSMutableArray *subscriptionContexts; // @synthesize subscriptionContexts=_subscriptionContexts;
- (id)_containerView;	// IMP=0x000000010000a948
- (id)_nameForSIMWithSubscriptionContext:(id)arg1;	// IMP=0x000000010000a754
- (_Bool)_anESIMExistsInSubscriptionContexts;	// IMP=0x000000010000a634
- (void)_cancelButtonItemPressed:(id)arg1;	// IMP=0x000000010000a5f0
- (unsigned long long)_numberOfLockedSubscriptionContexts;	// IMP=0x000000010000a4a4
- (void)_configureFooterView;	// IMP=0x000000010000a414
- (void)_configureTableFooterView;	// IMP=0x000000010000a354
- (void)_configureHeaderView;	// IMP=0x000000010000a210
- (void)_configureNavigationItem;	// IMP=0x000000010000a118
- (void)_configureAncillaryViews;	// IMP=0x000000010000a0c4
- (void)removeSubscriptionContextAtIndex:(unsigned long long)arg1;	// IMP=0x0000000100009ef4
- (void)updateSubscriptionContext:(id)arg1 withSubscriptionAction:(id)arg2 atIndex:(unsigned long long)arg3;	// IMP=0x0000000100009d08
- (void)addSubscriptionContext:(id)arg1 withSubscriptionAction:(id)arg2 atIndex:(unsigned long long)arg3;	// IMP=0x0000000100009b1c
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;	// IMP=0x0000000100009b14
- (void)unlockListFooterViewContinueButtonWasPressed:(id)arg1;	// IMP=0x0000000100009ad0
- (void)unlockDetailViewController:(id)arg1 didCompleteWithResult:(long long)arg2;	// IMP=0x0000000100009a18
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;	// IMP=0x00000001000098b0
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;	// IMP=0x00000001000098a4
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;	// IMP=0x000000010000988c
- (_Bool)tableView:(id)arg1 shouldHighlightRowAtIndexPath:(id)arg2;	// IMP=0x00000001000097b8
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x0000000100009404
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x0000000100009370
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0000000100009320
- (void)viewDidLoad;	// IMP=0x0000000100008fc0
- (void)loadView;	// IMP=0x0000000100008edc
- (id)initWithSubscriptionContexts:(id)arg1 subscriptionActions:(id)arg2 suppressCancellation:(_Bool)arg3 delegate:(id)arg4;	// IMP=0x0000000100008d58

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

