//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UITextFieldDelegate-Protocol.h"

@class NSString, UIButton, UILabel, UITextField;
@protocol TSSIMUnlockEntryViewDelegate;

@interface TSSIMUnlockEntryView : UIView <UITextFieldDelegate>
{
    UIView *_containerView;	// 8 = 0x8
    UILabel *_detailLabel;	// 16 = 0x10
    UITextField *_entryField;	// 24 = 0x18
    UIButton *_okButton;	// 32 = 0x20
    _Bool _unlocking;	// 40 = 0x28
    _Bool _pinMismatch;	// 41 = 0x29
    unsigned long long _attemptsRemaining;	// 48 = 0x30
    id <TSSIMUnlockEntryViewDelegate> _delegate;	// 56 = 0x38
    long long _actionType;	// 64 = 0x40
    long long _actionSubtype;	// 72 = 0x48
}

- (void).cxx_destruct;	// IMP=0x0000000100008770
@property(readonly, nonatomic) long long actionSubtype; // @synthesize actionSubtype=_actionSubtype;
@property(readonly, nonatomic) long long actionType; // @synthesize actionType=_actionType;
@property(nonatomic) __weak id <TSSIMUnlockEntryViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) unsigned long long attemptsRemaining; // @synthesize attemptsRemaining=_attemptsRemaining;
@property(nonatomic) _Bool pinMismatch; // @synthesize pinMismatch=_pinMismatch;
@property(nonatomic) _Bool unlocking; // @synthesize unlocking=_unlocking;
- (void)_configureDetailLabelText;	// IMP=0x00000001000084e0
- (void)_configureOKButtonWithEnteredText:(id)arg1;	// IMP=0x0000000100008480
- (void)_okButtonPressed:(id)arg1;	// IMP=0x0000000100008400
@property(readonly, copy, nonatomic) NSString *enteredText;
- (void)resetEnteredTextWithShakeAnimation:(_Bool)arg1;	// IMP=0x0000000100007e74
- (_Bool)isFirstResponder;	// IMP=0x0000000100007e5c
- (_Bool)resignFirstResponder;	// IMP=0x0000000100007e04
- (_Bool)canResignFirstResponder;	// IMP=0x0000000100007dec
- (_Bool)becomeFirstResponder;	// IMP=0x0000000100007dd4
- (_Bool)canBecomeFirstResponder;	// IMP=0x0000000100007dbc
- (_Bool)textFieldShouldReturn:(id)arg1;	// IMP=0x0000000100007d24
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;	// IMP=0x0000000100007b88
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;	// IMP=0x0000000100007b7c
- (void)layoutSubviews;	// IMP=0x00000001000079b8
- (id)initWithActionType:(long long)arg1 actionSubtype:(long long)arg2;	// IMP=0x0000000100007578

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

