//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton;
@protocol TSSIMUnlockListFooterViewDelegate;

@interface TSSIMUnlockListFooterView : UIView
{
    UIButton *_continueButton;	// 8 = 0x8
    long long _mode;	// 16 = 0x10
    id <TSSIMUnlockListFooterViewDelegate> _delegate;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x0000000100007120
@property(nonatomic) __weak id <TSSIMUnlockListFooterViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) long long mode; // @synthesize mode=_mode;
- (void)_continueButtonPressed:(id)arg1;	// IMP=0x0000000100007098
- (void)layoutSubviews;	// IMP=0x0000000100006a98
- (id)initWithDelegate:(id)arg1;	// IMP=0x0000000100006a28

@end

