//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TSSIMUnlockListCell.h"

@class NSString;

@interface TSSIMUnlockListLockedCell : TSSIMUnlockListCell
{
    NSString *_lockedSIMName;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x000000010000f3c8
@property(copy, nonatomic) NSString *lockedSIMName; // @synthesize lockedSIMName=_lockedSIMName;
- (void)prepareForReuse;	// IMP=0x000000010000f2ac
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;	// IMP=0x000000010000f1dc

@end

