//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CLNotifierServiceAdapter.h"

#import "CLCompassDatabaseProtocol-Protocol.h"

@class NSString;

@interface CLCompassDatabaseLocationdAdapter : CLNotifierServiceAdapter <CLCompassDatabaseProtocol>
{
}

+ (_Bool)isSupported;	// IMP=0x0000000100576218
+ (id)getSilo;	// IMP=0x0000000100575ff0
+ (void)performSyncOnSilo:(id)arg1 invoker:(CDUnknownBlockType)arg2;	// IMP=0x0000000100575fcc
+ (void)becameFatallyBlocked:(id)arg1 index:(unsigned long long)arg2;	// IMP=0x0000000100575f48
- (_Bool)syncgetLookupBiasWithMagneticField:(CDStruct_869f9c67)arg1 acceleration:(CDStruct_869f9c67)arg2 bias:(CDStruct_869f9c67 *)arg3 level:(int *)arg4 noResults:(_Bool *)arg5;	// IMP=0x00000001005763e0
- (void)getBiasWithMagneticField:(CDStruct_869f9c67)arg1 acceleration:(CDStruct_869f9c67)arg2;	// IMP=0x0000000100576398
- (int)syncgetPendingSetBiasCount;	// IMP=0x0000000100576334
- (void)setBias:(CDStruct_869f9c67)arg1 withMagneticField:(CDStruct_869f9c67)arg2 level:(int)arg3 magnitude:(float)arg4 inclination:(float)arg5;	// IMP=0x00000001005762c4
- (void)dumpDatabase:(id)arg1 onCompletion:(CDUnknownBlockType)arg2;	// IMP=0x000000010057627c
- (_Bool)syncgetDoSync:(CDUnknownBlockType)arg1;	// IMP=0x00000001005761dc
- (void)doAsync:(CDUnknownBlockType)arg1 withReply:(CDUnknownBlockType)arg2;	// IMP=0x0000000100576198
- (void)doAsync:(CDUnknownBlockType)arg1;	// IMP=0x0000000100576164
- (struct CLCompassDatabase *)adaptee;	// IMP=0x0000000100576128
- (void)endService;	// IMP=0x0000000100576104
- (void)beginService;	// IMP=0x00000001005760ac
- (id)init;	// IMP=0x0000000100576068

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(nonatomic) _Bool valid;

@end

