//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CLIntersiloServiceProtocol-Protocol.h"

@protocol CLDigitalElevationModelPublicProtocol <CLIntersiloServiceProtocol>
- (void)downloadAvailabilityFile:(double)arg1;
- (void)downloadIfNeeded:(struct CLDaemonLocation (^)(void))arg1 signalQuality:(_Bool)arg2 allowCenterOverCellular:(_Bool)arg3;
- (void)updateTunnelBridgeAssistance:(struct TunnelBridgeAssistance)arg1;
- (void)updateAirborneActivity:(_Bool)arg1;
- (void)updateMotion:(int)arg1 conf:(int)arg2;
- (void)clear;
- (_Bool)syncgetAltitude:(struct DaemonLocation *)arg1 rel:(int *)arg2 undulation:(double *)arg3;
@end

