//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface CLFallMslSink : NSObject
{
    struct list<CMMsl::Item *, std::__1::allocator<CMMsl::Item *>> fOrderedSample;	// 8 = 0x8
    struct ImpactEvent fImpactEvent;	// 32 = 0x20
    _Bool fIncludeDerivedFeatures;	// 234 = 0xea
}

- (id).cxx_construct;	// IMP=0x0000000100702714
- (void).cxx_destruct;	// IMP=0x000000010070270c
- (void)cleanUp;	// IMP=0x00000001007026fc
- (void)cleanUpIncludingDerivedFeatures:(_Bool)arg1;	// IMP=0x0000000100702618
- (void)sendData:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100702058
- (void)logSuppressionFeartures:(const FalsePositiveSuppressionFeatures_8c0e6519 *)arg1;	// IMP=0x0000000100701ea8
- (void)logFallStats:(const struct ImpactEvent *)arg1;	// IMP=0x00000001007018f4
- (void)logFallState:(const struct ImpactEvent *)arg1;	// IMP=0x0000000100701784
- (void)logWristState:(const WristState_948f25b1 *)arg1;	// IMP=0x0000000100701658
- (void)logHeartRate:(const struct CLCatherineData *)arg1;	// IMP=0x00000001007014c4
- (void)logPressure:(const Pressure_bceab11c *)arg1;	// IMP=0x0000000100701408
- (void)logFilteredPressure:(const FilteredPressure_54a5c05a *)arg1;	// IMP=0x000000010070134c
- (void)logDeviceMotion:(const struct ImpactData *)arg1;	// IMP=0x000000010070122c
- (void)logGyro200:(const struct ImpactData *)arg1;	// IMP=0x0000000100701138
- (void)logGyro100:(id)arg1 startTime:(double)arg2 timestamp:(unsigned long long)arg3;	// IMP=0x0000000100700f88
- (void)logAccel800:(const struct ImpactData *)arg1;	// IMP=0x0000000100700e94
- (void)logAccel100:(id)arg1 startTime:(double)arg2 timestamp:(unsigned long long)arg3;	// IMP=0x0000000100700ce4
- (void)dealloc;	// IMP=0x0000000100700c98
- (id)initInUniverse:(id)arg1;	// IMP=0x0000000100700c5c
- (void)_insertSample:(struct Item *)arg1;	// IMP=0x0000000100700a2c

@end

