//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "CLATVAirplayMonitorClientProtocol-Protocol.h"
#import "CLDuetMonitorClientProtocol-Protocol.h"
#import "CLRoutineMonitorClientProtocol-Protocol.h"

@class NSString;

@interface CLMicroLocationIntersiloDelegate : NSObject <CLDuetMonitorClientProtocol, CLRoutineMonitorClientProtocol, CLATVAirplayMonitorClientProtocol>
{
    struct CLMicroLocationNotifier *_microLocationNotifier;	// 8 = 0x8
    _Bool _valid;	// 16 = 0x10
}

@property(nonatomic) _Bool valid; // @synthesize valid=_valid;
- (void)duetMonitor:(id)arg1 nowPlayingDidChange:(id)arg2;	// IMP=0x0000000100814e58
- (void)duetMonitor:(id)arg1 homekitAccessoryDidChange:(id)arg2;	// IMP=0x0000000100814b58
- (void)duetMonitor:(id)arg1 homekitSceneDidChange:(id)arg2;	// IMP=0x00000001008148bc
- (void)duetMonitor:(id)arg1 foregroundAppDidLaunch:(id)arg2;	// IMP=0x000000010081484c
- (void)duetMonitorDeviceFirstWakeOfDay:(id)arg1;	// IMP=0x0000000100814824
- (void)onLowConfidenceVisit:(id)arg1;	// IMP=0x00000001008146e0
- (void)onVisit:(id)arg1;	// IMP=0x000000010081442c
- (void)clATVAirplayMonitorService:(id)arg1 didFindDevices:(id)arg2;	// IMP=0x000000010081425c
- (id)initWithMicroLocationNotifier:(struct CLMicroLocationNotifier *)arg1;	// IMP=0x0000000100814200

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

