//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CLNotifierServiceAdapter.h"

#import "CLMotionAlarmNotifierProtocol-Protocol.h"

@class NSString;

@interface CLMotionAlarmNotifierAdapter : CLNotifierServiceAdapter <CLMotionAlarmNotifierProtocol>
{
}

+ (id)getSilo;	// IMP=0x00000001004e2d70
+ (void)performSyncOnSilo:(id)arg1 invoker:(CDUnknownBlockType)arg2;	// IMP=0x00000001004e2d4c
+ (void)becameFatallyBlocked:(id)arg1 index:(unsigned long long)arg2;	// IMP=0x00000001004e2cc8
- (void)onClassATimerActivity:(id)arg1 withAlarmId:(unsigned long long)arg2;	// IMP=0x00000001004e52f0
- (void)launchWatchApplicationForCompanion:(id)arg1;	// IMP=0x00000001004e52e4
- (void)launchRemoteApplication:(id)arg1 withReply:(CDUnknownBlockType)arg2;	// IMP=0x00000001004e50dc
- (void)acknowledgeAlarm:(id)arg1 withReply:(CDUnknownBlockType)arg2;	// IMP=0x00000001004e4984
- (void)unregisterAlarm:(id)arg1 withReply:(CDUnknownBlockType)arg2;	// IMP=0x00000001004e4440
- (void)registerAlarm:(id)arg1 withReply:(CDUnknownBlockType)arg2;	// IMP=0x00000001004e3960
- (void)unregisterClient:(CDUnknownBlockType)arg1;	// IMP=0x00000001004e358c
- (void)registerClient:(CDUnknownBlockType)arg1 adapter:(byref id)arg2;	// IMP=0x00000001004e300c
- (_Bool)syncgetDoSync:(CDUnknownBlockType)arg1;	// IMP=0x00000001004e2fd0
- (void)doAsync:(CDUnknownBlockType)arg1 withReply:(CDUnknownBlockType)arg2;	// IMP=0x00000001004e2f8c
- (void)doAsync:(CDUnknownBlockType)arg1;	// IMP=0x00000001004e2f58
- (struct CLMotionAlarmNotifier *)adaptee;	// IMP=0x00000001004e2f1c
- (void)endService;	// IMP=0x00000001004e2ef8
- (void)beginService;	// IMP=0x00000001004e2e2c
- (id)init;	// IMP=0x00000001004e2de8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(nonatomic) _Bool valid;

@end

