//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@protocol CMStrideCalibrationDatabaseDelegate;

@interface CMStrideCalibrationDatabase : NSObject
{
    struct CMStrideCalRecorderDb fStrideCalDb;	// 8 = 0x8
    id <CMStrideCalibrationDatabaseDelegate> _delegate;	// 480 = 0x1e0
}

- (id).cxx_construct;	// IMP=0x00000001006fc270
- (void).cxx_destruct;	// IMP=0x00000001006fc268
@property(nonatomic) id <CMStrideCalibrationDatabaseDelegate> delegate; // @synthesize delegate=_delegate;
- (id)copyHistory;	// IMP=0x00000001006fc0f0
- (_Bool)isCalibrationConvergedMedianForSpeed:(double)arg1;	// IMP=0x00000001006fbc00
- (_Bool)isCalibrationConvergedStdForBinWithSpeed:(double)arg1;	// IMP=0x00000001006fb9f4
- (void)addEntry:(CDStruct_9878d8f4)arg1;	// IMP=0x00000001006fb638
- (id)initWithSilo:(id)arg1;	// IMP=0x00000001006fb314

@end

