//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSData, NSDictionary, NSError, WPZoneTracker;

@protocol WPZoneTrackerDelegate <NSObject>
- (void)zoneTracker:(WPZoneTracker *)arg1 didFailToRegisterZones:(NSDictionary *)arg2 withError:(NSError *)arg3;
- (void)zoneTracker:(WPZoneTracker *)arg1 exitedZone:(NSData *)arg2;
- (void)zoneTracker:(WPZoneTracker *)arg1 enteredZone:(NSData *)arg2;
- (void)zoneTrackerDidUpdateState:(WPZoneTracker *)arg1;

@optional
- (void)zoneTracker:(WPZoneTracker *)arg1 enteredZoneInfo:(NSDictionary *)arg2;
@end

