//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CLIndoorXPCProvider.h"

#import "CLIndoorXPCProviderImplementation-Protocol.h"

@class NSString;

@interface CLIndoorMaintenance : CLIndoorXPCProvider <CLIndoorXPCProviderImplementation>
{
}

- (void)onQueueNumFloors:(CDUnknownBlockType)arg1;	// IMP=0x0000000100015044
- (void)numFloors:(CDUnknownBlockType)arg1;	// IMP=0x0000000100014e40
- (void)onQueueShutdown;	// IMP=0x0000000100014d14
- (void)shutdown;	// IMP=0x0000000100014bdc
- (void)onQueueEraseEverything:(CDUnknownBlockType)arg1;	// IMP=0x0000000100014a84
- (void)eraseEverything;	// IMP=0x00000001000148b0
- (void)doSynchronousXPC:(CDUnknownBlockType)arg1 description:(const char *)arg2 waitForever:(_Bool)arg3;	// IMP=0x00000001000145f4
- (void)prefetchSynchronous:(id)arg1;	// IMP=0x0000000100014320
- (void)onQueuePrefetch:(id)arg1 callback:(CDUnknownBlockType)arg2 when:(unsigned char)arg3;	// IMP=0x00000001000141f8
- (void)prefetch:(id)arg1;	// IMP=0x0000000100013f24
- (void)retrieveLocationRelevancyDurationWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x0000000100013d4c
- (void)withinQueueReinitializeRemoteState;	// IMP=0x0000000100013d08
- (_Bool)withinQueueCanReinitializeRemoteState;	// IMP=0x0000000100013d00
- (id)withinQueuePermanentShutdownReason;	// IMP=0x0000000100013cf8
- (void)withinQueueReconnectInvalidatedConnectionFailed:(id)arg1;	// IMP=0x0000000100013cdc
- (void)withinQueueInvalidateState;	// IMP=0x0000000100013cd8
- (id)endpointName;	// IMP=0x0000000100013ccc
- (id)remoteObjectProtocol;	// IMP=0x0000000100013cc0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

