//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "IOSAbstractInertialSensor.h"

@interface IOSAccelerometer : IOSAbstractInertialSensor
{
}

+ (void)convertGToAccel:(struct SensorMeasurement *)arg1;	// IMP=0x00000001002c1674
- (id)description;	// IMP=0x00000001002c1bb0
- (void)stop;	// IMP=0x00000001002c1b3c
- (void)start;	// IMP=0x00000001002c16e8
- (void)processAccelSample:(const struct SensorMeasurement *)arg1;	// IMP=0x00000001002c16a0
- (_Bool)sensorPresent;	// IMP=0x00000001002c15f8
- (id)initWithMotionManager:(id)arg1 andHandler:(id)arg2;	// IMP=0x00000001002c1534

@end

