//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableIndexSet, _BKMovingMedian;
@protocol BKHIDEventSenderInfo;

@interface _BKMouseDeviceEventState : NSObject
{
    unsigned long long _previousTimeStamp;	// 8 = 0x8
    _Bool _discreteScroll;	// 16 = 0x10
    _Bool _shouldSwapButtonsWhenRequested;	// 17 = 0x11
    unsigned short _scrollPhase;	// 18 = 0x12
    int _eventSource;	// 20 = 0x14
    id <BKHIDEventSenderInfo> _senderInfo;	// 24 = 0x18
    long long _buttonMask;	// 32 = 0x20
    NSMutableIndexSet *_touchingPaths;	// 40 = 0x28
    NSMutableIndexSet *_touchingPathsAtButtonEvent;	// 48 = 0x30
    NSMutableIndexSet *_restingPaths;	// 56 = 0x38
    _BKMovingMedian *_periodCalculator;	// 64 = 0x40
}

- (void).cxx_destruct;	// IMP=0x0000000100067a10
@property(nonatomic) _Bool shouldSwapButtonsWhenRequested; // @synthesize shouldSwapButtonsWhenRequested=_shouldSwapButtonsWhenRequested;
@property(nonatomic) _Bool discreteScroll; // @synthesize discreteScroll=_discreteScroll;
@property(nonatomic) int eventSource; // @synthesize eventSource=_eventSource;
@property(nonatomic) unsigned short scrollPhase; // @synthesize scrollPhase=_scrollPhase;
@property(retain, nonatomic) _BKMovingMedian *periodCalculator; // @synthesize periodCalculator=_periodCalculator;
@property(retain, nonatomic) NSMutableIndexSet *restingPaths; // @synthesize restingPaths=_restingPaths;
@property(retain, nonatomic) NSMutableIndexSet *touchingPathsAtButtonEvent; // @synthesize touchingPathsAtButtonEvent=_touchingPathsAtButtonEvent;
@property(retain, nonatomic) NSMutableIndexSet *touchingPaths; // @synthesize touchingPaths=_touchingPaths;
@property(nonatomic) long long buttonMask; // @synthesize buttonMask=_buttonMask;
@property(retain, nonatomic) id <BKHIDEventSenderInfo> senderInfo; // @synthesize senderInfo=_senderInfo;
- (_Bool)postsEventsAtHighFrequency;	// IMP=0x0000000100067934
- (void)updatePeriodFromEvent:(struct __IOHIDEvent *)arg1;	// IMP=0x000000010006772c
- (_Bool)updateFromDigitizerEvent:(struct __IOHIDEvent *)arg1;	// IMP=0x00000001000672ac
- (id)initWithSender:(id)arg1;	// IMP=0x0000000100067148

@end

