//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "BKMousePointerGlobalDevicePreferencesObserver-Protocol.h"
#import "BSInvalidatable-Protocol.h"
#import "BSServiceConnectionListenerDelegate-Protocol.h"

@class BKMousePointerController, BSServiceConnectionListener, NSMutableSet, NSString;
@protocol OS_dispatch_queue;

@interface BKMousePointerServiceServer : NSObject <BKMousePointerGlobalDevicePreferencesObserver, BSServiceConnectionListenerDelegate, BSInvalidatable>
{
    BKMousePointerController *_mousePointerController;	// 8 = 0x8
    BSServiceConnectionListener *_connectionListener;	// 16 = 0x10
    NSMutableSet *_deviceObservingConnections;	// 24 = 0x18
    NSMutableSet *_preferenceObservingConnections;	// 32 = 0x20
    NSObject<OS_dispatch_queue> *_queue;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x00000001000076f8
- (_Bool)_accessStateForReason:(id)arg1 entitlement:(id)arg2 logEntitlementOnFailure:(_Bool)arg3 usingBlock:(CDUnknownBlockType)arg4;	// IMP=0x0000000100007498
- (void)_assertModelUpdatesSuppressed:(_Bool)arg1 displayUUID:(id)arg2 clientDisplayInfo:(id)arg3;	// IMP=0x00000001000071c0
- (id)_perDisplayClientInfoForCurrentConnectionWithDisplayUUID:(id)arg1 createIfNeeded:(_Bool)arg2;	// IMP=0x00000001000070d8
- (void)_queue_removeConnection:(id)arg1;	// IMP=0x0000000100006ee0
- (id)_pointerDevicesFromIOHIDServices:(id)arg1;	// IMP=0x0000000100006e70
- (void)listener:(id)arg1 didReceiveConnection:(id)arg2 withContext:(id)arg3;	// IMP=0x0000000100006d44
- (void)mousePointerGlobalDevicePreferencesDidChange:(id)arg1;	// IMP=0x0000000100006cc0
- (oneway void)setGlobalDevicePreferences:(id)arg1;	// IMP=0x0000000100006bf4
- (id)globalDevicePreferences;	// IMP=0x0000000100006ae8
- (oneway void)setPreferences:(id)arg1 forDevice:(id)arg2;	// IMP=0x00000001000069e4
- (id)preferencesForDevice:(id)arg1;	// IMP=0x00000001000068a4
- (oneway void)setMousePointerPreferenceObservationEnabled:(id)arg1;	// IMP=0x00000001000067d8
- (oneway id)setMousePointerDeviceObservationEnabled:(id)arg1;	// IMP=0x00000001000066a0
- (oneway void)getHitTestContextsAtPoint:(id)arg1 withAdditionalContexts:(id)arg2 onDisplay:(id)arg3 withCompletion:(CDUnknownBlockType)arg4;	// IMP=0x0000000100006414
- (oneway void)setGlobalPointerEventContextIDsForDisplay:(id)arg1 targetContextIDs:(id)arg2;	// IMP=0x0000000100006310
- (oneway void)invalidateButtonDownPointerRepositionAssertionWithUniqueIdentifier:(id)arg1 onDisplay:(id)arg2;	// IMP=0x000000010000621c
- (oneway void)acquireButtonDownPointerRepositionAssertionWithUniqueIdentifier:(id)arg1 forReason:(id)arg2 contextRelativePointerPosition:(id)arg3 onDisplay:(id)arg4 restrictingToPID:(id)arg5;	// IMP=0x0000000100005ff0
- (oneway void)applyAssertionParametersOnDisplay:(id)arg1 withOptionsMask:(id)arg2;	// IMP=0x0000000100005f18
- (oneway void)setContextRelativePointerPosition:(id)arg1 withInitialVelocity:(id)arg2 onDisplay:(id)arg3 withDecelerationRate:(id)arg4 restrictingToPID:(id)arg5;	// IMP=0x0000000100005d7c
- (oneway void)setContextRelativePointerPosition:(id)arg1 onDisplay:(id)arg2 withAnimationParameters:(id)arg3 restrictingToPID:(id)arg4;	// IMP=0x0000000100005c10
- (oneway void)setPointerPosition:(id)arg1 onDisplay:(id)arg2 withAnimationParameters:(id)arg3;	// IMP=0x0000000100005adc
- (oneway void)setGlobalPointerPosition:(id)arg1;	// IMP=0x0000000100005a24
- (oneway id)globalPointerPosition;	// IMP=0x0000000100005910
- (void)invalidate;	// IMP=0x000000010000590c
- (void)pointingDevicesDidChange:(id)arg1;	// IMP=0x000000010000588c
- (void)activateWithMousePointerController:(id)arg1;	// IMP=0x00000001000057b0
- (void)dealloc;	// IMP=0x0000000100005708

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

