//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class BKSystemApplication, BKSystemApplicationServer, NSSet;

@protocol BKSystemApplicationServerDelegate <NSObject>
- (void)server:(BKSystemApplicationServer *)arg1 systemApp:(BKSystemApplication *)arg2 hasActions:(NSSet *)arg3;
- (void)server:(BKSystemApplicationServer *)arg1 systemAppFinishBooting:(BKSystemApplication *)arg2;
- (void)server:(BKSystemApplicationServer *)arg1 systemAppDisconnected:(BKSystemApplication *)arg2;
- (void)server:(BKSystemApplicationServer *)arg1 systemAppCheckedIn:(BKSystemApplication *)arg2 completion:(void (^)(void))arg3;
- (void)server:(BKSystemApplicationServer *)arg1 systemAppConnected:(BKSystemApplication *)arg2;
@end

