//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class BKSHIDUISensorMode, BSProcessDeathWatcher;

@interface BKUISensorClient : NSObject
{
    BKSHIDUISensorMode *_mode;	// 8 = 0x8
    BKSHIDUISensorMode *_modeToRestoreAfterEstimatedProx;	// 16 = 0x10
    BSProcessDeathWatcher *_deathWatcher;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x000000010002a180
- (void)dealloc;	// IMP=0x000000010002a130

@end

