//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class AStat;

__attribute__((visibility("hidden")))
@interface ABSFullSyncStats : NSObject
{
    AStat *_abSave;	// 8 = 0x8
    AStat *_vCardParseTime;	// 16 = 0x10
    AStat *_flushTime;	// 24 = 0x18
    double _startTime;	// 32 = 0x20
    double _endTime;	// 40 = 0x28
}

+ (void)start;	// IMP=0x000000010003121c
+ (id)sharedInstance;	// IMP=0x0000000100031210
- (void).cxx_destruct;	// IMP=0x0000000100031438
- (void)recordFlushTime:(double)arg1;	// IMP=0x0000000100031428
- (void)recordVCardParseTime:(double)arg1;	// IMP=0x0000000100031418
- (void)recordABSaveTime:(double)arg1;	// IMP=0x0000000100031408
- (void)stop;	// IMP=0x0000000100031344
- (id)init;	// IMP=0x0000000100031270

@end

