//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class MISSING_TYPE;

@interface _TtC11MobilePhone23FavoritesViewController : UIViewController
{
    MISSING_TYPE *observableFavoritesController;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00000001000e599c
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x00000001000e5a60
- (void)viewDidLoad;	// IMP=0x00000001000e593c
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001000e5658
- (id)init;	// IMP=0x00000001000e5600
- (id)initWithFavoritesController:(id)arg1;	// IMP=0x00000001000e5548

@end

