//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "PhoneApplication.h"

#import "UNUserNotificationCenterDelegate-Protocol.h"

@class NSString, PHRecentsController, UNUserNotificationCenter;

@interface MobilePhoneApplication : PhoneApplication <UNUserNotificationCenterDelegate>
{
    PHRecentsController *_recentsController;	// 48 = 0x30
    UNUserNotificationCenter *_notificationCenter;	// 56 = 0x38
}

- (void).cxx_destruct;	// IMP=0x00000001000bbe70
@property(retain, nonatomic) UNUserNotificationCenter *notificationCenter; // @synthesize notificationCenter=_notificationCenter;
- (_Bool)notificationCategoryIsAllowed:(id)arg1;	// IMP=0x00000001000bbde4
- (void)userNotificationCenter:(id)arg1 willPresentNotification:(id)arg2 withCompletionHandler:(CDUnknownBlockType)arg3;	// IMP=0x00000001000bbcf4
- (void)application:(id)arg1 didFailToContinueUserActivityWithType:(id)arg2 error:(id)arg3;	// IMP=0x00000001000bbc94
- (_Bool)application:(id)arg1 continueUserActivity:(id)arg2 restorationHandler:(CDUnknownBlockType)arg3;	// IMP=0x00000001000bb9c0
- (void)refreshDynamicApplicationShortcuts;	// IMP=0x00000001000bb5bc
- (void)application:(id)arg1 performActionForShortcutItem:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x00000001000bb080
- (void)applicationDidBecomeActive:(id)arg1;	// IMP=0x00000001000098b4
- (long long)headerViewNumberOfCallsToShow;	// IMP=0x00000001000bb078
- (_Bool)headerViewShowsAllRecentCalls;	// IMP=0x00000001000bb070
- (_Bool)audioButtonAllowsPhoneCallsAndFaceTimeAudio;	// IMP=0x00000001000bb048
- (_Bool)hasEnhancedVoicemail;	// IMP=0x000000010000f3a4
- (_Bool)showsPhoneVoicemail;	// IMP=0x0000000100006d2c
- (_Bool)showsPhoneDialer;	// IMP=0x0000000100007e6c
- (_Bool)badgesMissedFaceTimeVideo;	// IMP=0x00000001000bb044
- (_Bool)badgesMissedFaceTimeAudio;	// IMP=0x00000001000bb040
- (_Bool)badgesMissedTelephonyCalls;	// IMP=0x00000001000bb038
- (_Bool)showsThirdPartyRecents;	// IMP=0x00000001000bb030
- (_Bool)showsFaceTimeVideoRecents;	// IMP=0x0000000100008bb0
- (_Bool)showsFaceTimeAudioRecents;	// IMP=0x0000000100008b14
- (_Bool)showsTelephonyRecents;	// IMP=0x0000000100008c4c
- (_Bool)showsFaceTimeVideoFavorites;	// IMP=0x000000010000b224
- (_Bool)showsFaceTimeAudioFavorites;	// IMP=0x000000010000b188
- (_Bool)showsTelephonyFavorites;	// IMP=0x000000010000b154
- (_Bool)showsFaceTimeAudio;	// IMP=0x00000001000bb028
- (_Bool)showsFaceTimeVideo;	// IMP=0x00000001000bb020
- (_Bool)showsTelephonyCalls;	// IMP=0x00000001000bb018
- (int)defaultAction;	// IMP=0x00000001000bafe4
- (_Bool)showSplashScreenOnSignin;	// IMP=0x00000001000bafd8
- (_Bool)tabBarCanSlide;	// IMP=0x0000000100009998
- (_Bool)tabBarFillsScreen;	// IMP=0x00000001000064f0
- (_Bool)contentViewCanRotate;	// IMP=0x0000000100005f74
- (_Bool)alwaysShowLocalVideo;	// IMP=0x0000000100005f54
- (_Bool)usesBlendModes;	// IMP=0x00000001000bafd0
- (unsigned int)userInterfaceStyle;	// IMP=0x0000000100006794
- (id)rootViewController;	// IMP=0x00000001000baf80
- (id)recentsController;	// IMP=0x00000001000bae10
- (void)dealloc;	// IMP=0x00000001000bad74
- (id)init;	// IMP=0x0000000100005550
- (void)applicationDidFinishLaunching:(id)arg1;	// IMP=0x00000001000055ac
- (_Bool)_isIPad;	// IMP=0x00000001000bad1c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

