//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSCharacterSet.h>

@interface NSCharacterSet (PauseCharacterSet)
+ (id)starAndOctothorpeCharacterSet;	// IMP=0x000000010006d794
+ (id)pauseCharacterSet;	// IMP=0x000000010006d778
+ (id)unicodeDirectionalCharactersSet;	// IMP=0x000000010000ff68
@end

