//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "PHCarPlayGenericTableViewController.h"

@class NSMutableArray, NSMutableDictionary, TPFavoritesController, TUCallProviderManager;

@interface PHCarPlayFavoritesViewController : PHCarPlayGenericTableViewController
{
    TPFavoritesController *_favoritesController;	// 8 = 0x8
    NSMutableArray *_favoritesEntries;	// 16 = 0x10
    TUCallProviderManager *_callProviderManager;	// 24 = 0x18
    NSMutableDictionary *_transportNameCache;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x00000001000a564c
@property(readonly, copy, nonatomic) NSMutableDictionary *transportNameCache; // @synthesize transportNameCache=_transportNameCache;
@property(readonly, nonatomic) TUCallProviderManager *callProviderManager; // @synthesize callProviderManager=_callProviderManager;
@property(retain, nonatomic) NSMutableArray *favoritesEntries; // @synthesize favoritesEntries=_favoritesEntries;
@property(readonly, nonatomic) TPFavoritesController *favoritesController; // @synthesize favoritesController=_favoritesController;
- (id)transportNameForFavoritesEntry:(id)arg1;	// IMP=0x00000001000a530c
- (void)reloadDataForFavoritesEntries:(id)arg1;	// IMP=0x00000001000a51a8
- (id)favoritesEntryAtIndex:(long long)arg1;	// IMP=0x00000001000a5124
- (id)avatarViewContactForFavoritesEntry:(id)arg1;	// IMP=0x00000001000a50a4
- (id)audioFavoritesEntryForFavoritesEntry:(id)arg1;	// IMP=0x00000001000a4e30
- (void)viewDidLoad;	// IMP=0x00000001000a4dac
- (double)defaultRowHeight;	// IMP=0x00000001000a4da0
- (id)subtitleForNoContentBanner;	// IMP=0x00000001000a4d98
- (id)titleForNoContentBanner;	// IMP=0x00000001000a4d18
- (void)programmaticallySelectRowAtIndexPath:(id)arg1;	// IMP=0x00000001000a4a60
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;	// IMP=0x00000001000a49e4
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;	// IMP=0x00000001000a4974
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x00000001000a4544
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;	// IMP=0x00000001000a44d4
- (void)handleTPFavoritesControllerFavoritesEntriesDidChangeNotification:(id)arg1;	// IMP=0x00000001000a4454
- (void)setFavoritesEntries:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00000001000a439c
- (void)dealloc;	// IMP=0x00000001000a4314
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x00000001000a4250
- (id)init;	// IMP=0x00000001000a4108

@end

