//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIButton.h>

@interface PHCarPlayVoicemailButton : UIButton
{
}

- (void)didUpdateFocusInContext:(id)arg1 withAnimationCoordinator:(id)arg2;	// IMP=0x0000000100024660
- (id)_externalUnfocusedBorderColor;	// IMP=0x000000010002464c
- (id)initWithSymbolType:(long long)arg1;	// IMP=0x0000000100024548

@end

