//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <TelephonyUI/TPView.h>

@class NSArray, VMPlayerControlButton, VMPlayerControlsView, VMRoundButton;
@protocol VMMessageToolbarDelegate;

@interface VMMessageToolbar : TPView
{
    _Bool _restricted;	// 8 = 0x8
    id <VMMessageToolbarDelegate> _delegate;	// 16 = 0x10
    VMRoundButton *_audioRouteButton;	// 24 = 0x18
    VMRoundButton *_dialRequestButton;	// 32 = 0x20
    VMRoundButton *_trashButton;	// 40 = 0x28
    VMPlayerControlButton *_playerControlButton;	// 48 = 0x30
    VMPlayerControlsView *_playerControlsView;	// 56 = 0x38
    NSArray *_standardConstraints;	// 64 = 0x40
}

- (void).cxx_destruct;	// IMP=0x0000000100025c4c
@property(copy, nonatomic) NSArray *standardConstraints; // @synthesize standardConstraints=_standardConstraints;
@property(nonatomic, getter=isRestricted) _Bool restricted; // @synthesize restricted=_restricted;
@property(nonatomic) __weak VMPlayerControlsView *playerControlsView; // @synthesize playerControlsView=_playerControlsView;
@property(retain, nonatomic) VMPlayerControlButton *playerControlButton; // @synthesize playerControlButton=_playerControlButton;
@property(retain, nonatomic) VMRoundButton *trashButton; // @synthesize trashButton=_trashButton;
@property(retain, nonatomic) VMRoundButton *dialRequestButton; // @synthesize dialRequestButton=_dialRequestButton;
@property(retain, nonatomic) VMRoundButton *audioRouteButton; // @synthesize audioRouteButton=_audioRouteButton;
@property(nonatomic) __weak id <VMMessageToolbarDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) double playerControlButtonWidthLayoutConstraintConstant;
- (void)handleActionForButtonSender:(id)arg1 event:(id)arg2;	// IMP=0x0000000100025938
- (void)handleActionForPlayerControlButtonSender:(id)arg1 event:(id)arg2;	// IMP=0x00000001000257ec
- (void)setPlayerControlState:(long long)arg1;	// IMP=0x000000010002575c
- (void)unloadConstraints;	// IMP=0x00000001000256dc
- (void)loadConstraints;	// IMP=0x0000000100024b64
- (void)loadViews;	// IMP=0x000000010002495c
- (void)commonInit;	// IMP=0x000000010002490c
- (void)updateButtonsState;	// IMP=0x0000000100024838
- (void)updateAudioRouteButtonWithTouchUpInsideEnabled:(_Bool)arg1;	// IMP=0x00000001000247b4
- (void)setButtonType:(unsigned long long)arg1 enabled:(_Bool)arg2;	// IMP=0x000000010002472c

@end

