//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC11Diagnostics18BaseViewController.h"

@class MISSING_TYPE;

@interface _TtC11Diagnostics29FullscreenAlertViewController : _TtC11Diagnostics18BaseViewController
{
    MISSING_TYPE *alert;	// 8 = 0x8
    MISSING_TYPE *privateAlertAction;	// 64 = 0x40
    MISSING_TYPE *contentUnavailableView;	// 72 = 0x48
}

- (void).cxx_destruct;	// IMP=0x000000010004a1c4
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x000000010004a114
- (id)initWithCoder:(id)arg1;	// IMP=0x0000000100049830

@end

