//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC11Diagnostics8BaseView.h"

@class MISSING_TYPE, UIActivityIndicatorView, UILabel, UIProgressView, UIStackView;

@interface _TtC11Diagnostics10PromptView : _TtC11Diagnostics8BaseView
{
    MISSING_TYPE *promptStackView;	// 8 = 0x8
    MISSING_TYPE *titleLabel;	// 16 = 0x10
    MISSING_TYPE *subtitleLabel;	// 24 = 0x18
    MISSING_TYPE *infoVerticalStackView;	// 32 = 0x20
    MISSING_TYPE *infoProgressIndicatorView;	// 40 = 0x28
    MISSING_TYPE *infoActivityIndicatorView;	// 48 = 0x30
    MISSING_TYPE *infoLabelHorizontalStackView;	// 56 = 0x38
    MISSING_TYPE *infoLabel;	// 64 = 0x40
    MISSING_TYPE *buttonStackView;	// 72 = 0x48
    MISSING_TYPE *containerLayoutUpdateHandler;	// 80 = 0x50
    MISSING_TYPE *hasExplicitHeight;	// 96 = 0x60
    MISSING_TYPE *type;	// 97 = 0x61
    MISSING_TYPE *actions;	// 104 = 0x68
}

- (void).cxx_destruct;	// IMP=0x000000010005998c
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100059a58
- (id)initWithCoder:(id)arg1;	// IMP=0x0000000100058030
@property(nonatomic, readonly) UIStackView *buttonStackView; // @synthesize buttonStackView;
@property(nonatomic, retain) UILabel *infoLabel; // @synthesize infoLabel;
@property(nonatomic, retain) UIStackView *infoLabelHorizontalStackView; // @synthesize infoLabelHorizontalStackView;
@property(nonatomic, readonly) UIActivityIndicatorView *infoActivityIndicatorView; // @synthesize infoActivityIndicatorView;
@property(nonatomic, readonly) UIProgressView *infoProgressIndicatorView; // @synthesize infoProgressIndicatorView;
@property(nonatomic, retain) UIStackView *infoVerticalStackView; // @synthesize infoVerticalStackView;
@property(nonatomic, retain) UILabel *subtitleLabel; // @synthesize subtitleLabel;
@property(nonatomic, retain) UILabel *titleLabel; // @synthesize titleLabel;

@end

