//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC11Diagnostics17BaseTableViewCell.h"

@class MISSING_TYPE, _TtC11Diagnostics13CardStackView;

@interface _TtC11Diagnostics12CardViewCell : _TtC11Diagnostics17BaseTableViewCell
{
    MISSING_TYPE *spacing;	// 8 = 0x8
    MISSING_TYPE *pauseStateAnimation;	// 16 = 0x10
    MISSING_TYPE *deviceStateNotificationToken;	// 24 = 0x18
    MISSING_TYPE *cardStateNotificationToken;	// 32 = 0x20
    MISSING_TYPE *stackView;	// 40 = 0x28
    MISSING_TYPE *stackViewContainer;	// 48 = 0x30
    MISSING_TYPE *controller;	// 56 = 0x38
    MISSING_TYPE *layoutUpdateHandler;	// 96 = 0x60
    MISSING_TYPE *cardState;	// 112 = 0x70
}

- (void).cxx_destruct;	// IMP=0x000000010005b738
- (id)initWithCoder:(id)arg1;	// IMP=0x000000010005bfe4
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;	// IMP=0x000000010005bf7c
- (void)layoutSubviews;	// IMP=0x000000010005be10
- (void)_dynamicUserInterfaceTraitDidChange;	// IMP=0x000000010005bb48
- (void)dealloc;	// IMP=0x000000010005b6f0
@property(nonatomic, readonly) _TtC11Diagnostics13CardStackView *stackView; // @synthesize stackView;

@end

