//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UITableViewDataSource-Protocol.h"

@class DeleteAppFontsMainController, NSString, UIButton, UILabel, UITableView, UIView;

@interface DeleteAppFontsViewController : UIViewController <UITableViewDataSource>
{
    DeleteAppFontsMainController *_mainController;	// 8 = 0x8
    UIView *_containerView;	// 16 = 0x10
    UILabel *_deleteLabel;	// 24 = 0x18
    UILabel *_deleteDescriptionLabel;	// 32 = 0x20
    UITableView *_fontsTableView;	// 40 = 0x28
    UIButton *_deleteButton;	// 48 = 0x30
    UIButton *_dontDeleteButton;	// 56 = 0x38
}

- (void).cxx_destruct;	// IMP=0x00000001000058d4
@property(nonatomic) __weak UIButton *dontDeleteButton; // @synthesize dontDeleteButton=_dontDeleteButton;
@property(nonatomic) __weak UIButton *deleteButton; // @synthesize deleteButton=_deleteButton;
@property(nonatomic) __weak UITableView *fontsTableView; // @synthesize fontsTableView=_fontsTableView;
@property(nonatomic) __weak UILabel *deleteDescriptionLabel; // @synthesize deleteDescriptionLabel=_deleteDescriptionLabel;
@property(nonatomic) __weak UILabel *deleteLabel; // @synthesize deleteLabel=_deleteLabel;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(nonatomic) __weak DeleteAppFontsMainController *mainController; // @synthesize mainController=_mainController;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x0000000100005644
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;	// IMP=0x00000001000055d4
- (long long)numberOfSectionsInTableView:(id)arg1;	// IMP=0x00000001000055cc
- (void)dontDelete:(id)arg1;	// IMP=0x000000010000558c
- (void)doDelete:(id)arg1;	// IMP=0x000000010000554c
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x0000000100005518
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0000000100004fbc
- (void)viewDidLoad;	// IMP=0x0000000100004f88

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

