//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITableViewController.h>

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSMutableArray, NSMutableDictionary, NSString;

@interface FontInstallMissingAppViewController : UITableViewController <UITableViewDataSource, UITableViewDelegate>
{
    NSMutableArray *providers;	// 8 = 0x8
    NSMutableDictionary *font;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x000000010000945c
@property(retain, nonatomic) NSMutableDictionary *font; // @synthesize font;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x0000000100009204
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;	// IMP=0x00000001000090ac
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;	// IMP=0x0000000100009094
- (long long)numberOfSectionsInTableView:(id)arg1;	// IMP=0x000000010000908c
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;	// IMP=0x0000000100008f90
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0000000100008dc8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

