//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC6FindMy32FMPlatterImageAndButtonGroupView.h"

@class MISSING_TYPE;

@interface _TtC6FindMy20FMLocationAlertsView : _TtC6FindMy32FMPlatterImageAndButtonGroupView
{
    MISSING_TYPE *fencesRow;	// 88 = 0x58
    MISSING_TYPE *delegate;	// 96 = 0x60
    MISSING_TYPE *maxLocationAlerts;	// 112 = 0x70
    MISSING_TYPE *viewModel;	// 2598384 = 0x27a5f0
    MISSING_TYPE *canSetNotifyMe;	// 0 = 0x0
}

- (void).cxx_destruct;	// IMP=0x0000000100134cbc
- (void)handleAction;	// IMP=0x0000000100134c14
- (void)handleFenceTapWithSender:(id)arg1;	// IMP=0x00000001001346b4
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001001336b8

@end

