//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class MISSING_TYPE;

@interface _TtC6FindMy40FMSectionPlatterSwitchAndButtonGroupView : UIView
{
    MISSING_TYPE *style;	// 8 = 0x8
    MISSING_TYPE *sectionLabel;	// 64 = 0x40
    MISSING_TYPE *contentView;	// 72 = 0x48
    MISSING_TYPE *switchView;	// 80 = 0x50
    MISSING_TYPE *switchViewIsVisible;	// 88 = 0x58
    MISSING_TYPE *separatorView;	// 96 = 0x60
    MISSING_TYPE *actionButton;	// 104 = 0x68
    MISSING_TYPE *actionButtonIsVisible;	// 112 = 0x70
    MISSING_TYPE *delegate;	// 120 = 0x78
    MISSING_TYPE *isActionEnabled;	// 136 = 0x88
}

- (void).cxx_destruct;	// IMP=0x0000000100090e44
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100090ebc
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x0000000100090dc4
- (void)handleActionWithSender:(id)arg1;	// IMP=0x0000000100090c14
- (id)initWithCoder:(id)arg1;	// IMP=0x0000000100090bec

@end

