//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC6FindMy24FMPlatteredTableViewCell.h"

#import "UITextFieldDelegate-Protocol.h"

@class MISSING_TYPE;

@interface _TtC6FindMy26FMPhoneNumberTableViewCell : _TtC6FindMy24FMPlatteredTableViewCell <UITextFieldDelegate>
{
    MISSING_TYPE *textField;	// 8 = 0x8
    MISSING_TYPE *textView;	// 16 = 0x10
    MISSING_TYPE *placeHolderLabel;	// 24 = 0x18
    MISSING_TYPE *delegate;	// 32 = 0x20
    MISSING_TYPE *textViewDelegate;	// 48 = 0x30
    MISSING_TYPE *textFieldIsEnabled;	// 56 = 0x38
    MISSING_TYPE *textViewIsEnabled;	// 57 = 0x39
    MISSING_TYPE *initialPhoneNumber;	// 64 = 0x40
    MISSING_TYPE *placeHolderText;	// 80 = 0x50
}

- (void).cxx_destruct;	// IMP=0x000000010001839c
- (id)initWithCoder:(id)arg1;	// IMP=0x0000000100018494
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;	// IMP=0x000000010001842c
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;	// IMP=0x000000010001822c
- (void)textViewDidChange:(id)arg1;	// IMP=0x000000010001809c
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;	// IMP=0x0000000100017f6c
- (void)textFieldDidEndEditing:(id)arg1 reason:(long long)arg2;	// IMP=0x0000000100017efc
- (void)textFieldDidChangeWithSender:(id)arg1;	// IMP=0x0000000100017e54

@end

