//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIButton.h>

@class MISSING_TYPE;

@interface _TtC6FindMy16FMPlusSignButton : UIButton
{
    MISSING_TYPE *isRTLLanguage;	// 8 = 0x8
}

- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100057f10
- (struct CGRect)imageRectForContentRect:(struct CGRect)arg1;	// IMP=0x0000000100057dec
- (struct CGRect)titleRectForContentRect:(struct CGRect)arg1;	// IMP=0x0000000100057cd0
- (void)layoutSubviews;	// IMP=0x0000000100057ca4
- (id)initWithCoder:(id)arg1;	// IMP=0x0000000100057ba4
- (id)init;	// IMP=0x0000000100057b84

@end

