//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC6FindMy29FMDeviceActionsViewController.h"

@interface _TtC6FindMy26FMDeviceLostViewController : _TtC6FindMy29FMDeviceActionsViewController
{
}

- (id)initWithTitle:(id)arg1 detailText:(id)arg2 icon:(id)arg3 contentLayout:(long long)arg4;	// IMP=0x00000001000a1030

@end

