//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class CAShapeLayer, MKMapView, UIImageView, _TtC6FindMy20FMFenceMapAnnotation;
@protocol FMMapDragRadiusViewDelegate;

@interface FMMapDragRadiusView : UIView
{
    _Bool _isDragging;	// 8 = 0x8
    _Bool _isMinimum;	// 9 = 0x9
    _Bool _isMaximum;	// 10 = 0xa
    MKMapView *_mapView;	// 16 = 0x10
    _TtC6FindMy20FMFenceMapAnnotation *_annotation;	// 24 = 0x18
    id <FMMapDragRadiusViewDelegate> _delegate;	// 32 = 0x20
    UIImageView *_handleImageView;	// 40 = 0x28
    CAShapeLayer *_shapeLayer;	// 48 = 0x30
}

- (void).cxx_destruct;	// IMP=0x00000001000099d4
@property(nonatomic) _Bool isMaximum; // @synthesize isMaximum=_isMaximum;
@property(nonatomic) _Bool isMinimum; // @synthesize isMinimum=_isMinimum;
@property(retain, nonatomic) CAShapeLayer *shapeLayer; // @synthesize shapeLayer=_shapeLayer;
@property(retain, nonatomic) UIImageView *handleImageView; // @synthesize handleImageView=_handleImageView;
@property(nonatomic) id <FMMapDragRadiusViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) _TtC6FindMy20FMFenceMapAnnotation *annotation; // @synthesize annotation=_annotation;
@property(nonatomic) _Bool isDragging; // @synthesize isDragging=_isDragging;
@property(retain, nonatomic) MKMapView *mapView; // @synthesize mapView=_mapView;
- (_Bool)usesMetric;	// IMP=0x000000010000988c
- (double)minimumRadiusNormalized;	// IMP=0x0000000100009858
- (double)maximumRadiusNormalized;	// IMP=0x0000000100009824
- (double)currentHandleDistance;	// IMP=0x0000000100009698
- (double)currentHandleDistanceNormalized;	// IMP=0x0000000100009630
- (struct CGPoint)maxPoint;	// IMP=0x0000000100009500
- (struct CGPoint)minPoint;	// IMP=0x00000001000093d0
- (void)hideCircleAfterDelay;	// IMP=0x0000000100009398
- (double)feetToMeters:(double)arg1;	// IMP=0x0000000100009388
- (double)minimumInMeters;	// IMP=0x0000000100009334
- (void)_axSetCustomRadius:(double)arg1;	// IMP=0x00000001000092e4
- (void)handlePan:(id)arg1;	// IMP=0x0000000100008ef8
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;	// IMP=0x0000000100008dfc
- (void)drawRect:(struct CGRect)arg1;	// IMP=0x0000000100008788
- (void)removeHandle:(_Bool)arg1;	// IMP=0x00000001000086a0
- (void)addHandleForAnnotation:(id)arg1;	// IMP=0x00000001000085ec
- (void)animateHandleIn:(_Bool)arg1;	// IMP=0x0000000100008074
- (id)shapeLayerWithEndPoint:(struct CGPoint)arg1;	// IMP=0x0000000100007f8c
- (id)bezierPathWithEndPoint:(struct CGPoint)arg1;	// IMP=0x0000000100007c78
- (void)popAnimateHandle;	// IMP=0x00000001000076b0
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100007658
- (id)initWithCoder:(id)arg1;	// IMP=0x0000000100007600
- (void)initialize;	// IMP=0x00000001000073e4

@end

