/*
* This header is generated by classdump-dyld 1.0
* on Sunday, September 27, 2020 at 12:32:52 PM Mountain Standard Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /usr/lib/libAWDSupportFramework.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libAWDSupportFramework.dylib/libAWDSupportFramework.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@interface AWDWRMAntSelPolicyStats : PBCodable <NSCopying> {

	unsigned long long _timestamp;
	unsigned _issueBand;
	unsigned _issueType;
	BOOL _hasAntConstraint;
	BOOL _isCoexBand;
	SCD_Struct_AW2 _has;

}

@property (assign,nonatomic) BOOL hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;              //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) BOOL hasIssueBand; 
@property (assign,nonatomic) unsigned issueBand;                        //@synthesize issueBand=_issueBand - In the implementation block
@property (assign,nonatomic) BOOL hasIssueType; 
@property (assign,nonatomic) unsigned issueType;                        //@synthesize issueType=_issueType - In the implementation block
@property (assign,nonatomic) BOOL hasIsCoexBand; 
@property (assign,nonatomic) BOOL isCoexBand;                           //@synthesize isCoexBand=_isCoexBand - In the implementation block
@property (assign,nonatomic) BOOL hasHasAntConstraint; 
@property (assign,nonatomic) BOOL hasAntConstraint;                     //@synthesize hasAntConstraint=_hasAntConstraint - In the implementation block
-(void)setHasTimestamp:(BOOL)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)writeTo:(id)arg1 ;
-(BOOL)readFrom:(id)arg1 ;
-(unsigned long long)timestamp;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(void)mergeFrom:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(BOOL)hasTimestamp;
-(unsigned long long)hash;
-(void)setIssueType:(unsigned)arg1 ;
-(void)setHasIssueType:(BOOL)arg1 ;
-(BOOL)hasIssueType;
-(unsigned)issueType;
-(id)description;
-(id)dictionaryRepresentation;
-(void)setIssueBand:(unsigned)arg1 ;
-(void)setHasIssueBand:(BOOL)arg1 ;
-(BOOL)hasIssueBand;
-(void)setIsCoexBand:(BOOL)arg1 ;
-(void)setHasIsCoexBand:(BOOL)arg1 ;
-(BOOL)hasIsCoexBand;
-(void)setHasAntConstraint:(BOOL)arg1 ;
-(void)setHasHasAntConstraint:(BOOL)arg1 ;
-(BOOL)hasHasAntConstraint;
-(unsigned)issueBand;
-(BOOL)isCoexBand;
-(BOOL)hasAntConstraint;
@end

