#import <libAWDSupportFramework.dylib/AWDAddressBookSyncFullSyncEvent.h>
#import <libAWDSupportFramework.dylib/AWDBltDelayAckFromSecondaryDevice.h>
#import <libAWDSupportFramework.dylib/AWDBltDelayAppReadyToSend.h>
#import <libAWDSupportFramework.dylib/AWDBltDelayReceiveLocal.h>
#import <libAWDSupportFramework.dylib/AWDBltDelayToPrimaryDevice.h>
#import <libAWDSupportFramework.dylib/AWDBltDelayToSecondaryDevice.h>
#import <libAWDSupportFramework.dylib/AWDBltDelayToSync.h>
#import <libAWDSupportFramework.dylib/AWDBltDelayToSyncUnrestricted.h>
#import <libAWDSupportFramework.dylib/AWDBltDelayUIFromFactory.h>
#import <libAWDSupportFramework.dylib/AWDBltPrimaryDevicePublicationToResponseDelay.h>
#import <libAWDSupportFramework.dylib/AWDBltPrimaryDeviceSendAttempt.h>
#import <libAWDSupportFramework.dylib/AWDBltPrimaryDeviceSendInTime.h>
#import <libAWDSupportFramework.dylib/AWDBltPrimaryDeviceSendTimeout.h>
#import <libAWDSupportFramework.dylib/AWDBltRequestToResponseDelay.h>
#import <libAWDSupportFramework.dylib/AWDBltSecondaryConnectedToTransport.h>
#import <libAWDSupportFramework.dylib/AWDBltSecondaryProcessStarted.h>
#import <libAWDSupportFramework.dylib/AWDBltUIBuildAttempt.h>
#import <libAWDSupportFramework.dylib/AWDBltUIBuildFail.h>
#import <libAWDSupportFramework.dylib/AWDBltUIBuildSuccess.h>
#import <libAWDSupportFramework.dylib/AWDCaptiveSession.h>
#import <libAWDSupportFramework.dylib/AWDCFNetworkCacheMetrics.h>
#import <libAWDSupportFramework.dylib/AWDCFNetworkStreamTaskTiming.h>
#import <libAWDSupportFramework.dylib/AWDCFNetworkTaskMetrics.h>
#import <libAWDSupportFramework.dylib/AWDCFNetworkTransactionMetrics.h>
#import <libAWDSupportFramework.dylib/AWDCFNetworkW3CNavigationTiming.h>
#import <libAWDSupportFramework.dylib/AWDCompanionSyncErrorEvent.h>
#import <libAWDSupportFramework.dylib/AWDCompanionSyncErrorNotification.h>
#import <libAWDSupportFramework.dylib/AWDCompanionSyncFullSyncDuration.h>
#import <libAWDSupportFramework.dylib/AWDCompanionSyncReceiveEvent.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineAssetVersion.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineDeletionGroupStats.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineDeletionRecordStats.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineDeletionStats.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineFMCAssistanceInstance.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineFMCCarParkedInstance.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineFMCDailyAssessment.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineFMCDailyAssessments.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineFMCReturnToCarInstance.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineFMCVehicleConnectionEventInstance.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineFMCViewedInstance.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineHeroAppEngagementInstance.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineHeroAppImpressionInstance.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineHeroAppSuggestionInstance.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineHintSourceSubmissionInstance.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineHintSourceSubmissionSet.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineHintSourceUsageInstance.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineHintSourceUsageSet.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineHistogramBin.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineLMPAutofillSelectedInstance.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineLMPDailyAssessment.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineLMPRequestedInstance.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineLMPResponseInstance.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineLMPScoreBoard.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineLMPScoreBoardInstance.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineLearnedLocationReconciliationVisit.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineLearnedLocationReconciliationVisitDensity.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineLearnedLocationTrainingMetrics.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineLearnedRouteInstance.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineLocationAwarenessBasicHistogram.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineLocationAwarenessHeartbeatStatistics.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineLocationAwarenessIntervalHistogram.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineLocationAwarenessLocationTimeHistograms.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineLocationAwarenessStatistics.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineLocationTypeItem.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineMagicMomentsSuggestionInstance.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineMagicalMomentsExpertInstance.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineMagicalMomentsExperts.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineMagicalMomentsFeatureAddon.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineMagicalMomentsIndividualMoment.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineMagicalMomentsRecommendedAppsHistogramInstance.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineMagicalMomentsRecommendedAppsHistogramSet.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineMapItem.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineModelAlgorithmInstance.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineModelAlgorithmSet.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineModelAvailability.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineModelClusterMovementInstance.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineModelClusterMovementNoiseSet.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineModelClusterStandardDeviationInstance.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineModelClusterStandardDeviationSet.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineModelConsistencyReconsolidation.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineModelDominantPlaceCount.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineModelLearnedNonGeocodeableEvents.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineModelLength.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineModelStatus.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineModelTransitionInstance.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineModelTransitionSet.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineModelVisitCount.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutinePersistenceMirroringAccountDevices.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutinePersistenceMirroringDelegate.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutinePersistenceMirroringDeviceProfile.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutinePersistenceMirroringOperations.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutinePersistenceMirroringResetSync.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutinePersistenceMirroringTickleFight.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutinePersistenceStore.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutinePersistenceStoreMigrationDuration.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutinePlace.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineRankRoutesRequestedInstance.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineRoadClassItem.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineSettingsClearAll.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineSettingsClusterLocationView.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineSettingsClusterLocationVisitView.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineSettingsClusterView.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineSettingsDeleteType.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineSettingsEnableDisable.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineSettingsMapInteraction.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineSettingsSessionDuration.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineStateModelConfidence.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineTrafficConditions.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineTransitionMotionType.h>
#import <libAWDSupportFramework.dylib/AWDCoreRoutineVisit.h>
#import <libAWDSupportFramework.dylib/AWDDuetExpertCenterZKWOutcome.h>
#import <libAWDSupportFramework.dylib/AWDEventKitSyncCompletedNightlySync.h>
#import <libAWDSupportFramework.dylib/AWDEventKitSyncIsNotifiableEvent.h>
#import <libAWDSupportFramework.dylib/AWDEventKitSyncSyncedAttendeeResponseFromWatch.h>
#import <libAWDSupportFramework.dylib/AWDEventKitSyncSyncedEventCreatedOnWatch.h>
#import <libAWDSupportFramework.dylib/AWDEventKitSyncSyncedTaskCreatedOnWatch.h>
#import <libAWDSupportFramework.dylib/AWDFaceTimeCallAcceptReceived.h>
#import <libAWDSupportFramework.dylib/AWDFaceTimeCallAcceptSent.h>
#import <libAWDSupportFramework.dylib/AWDFaceTimeCallCancelSent.h>
#import <libAWDSupportFramework.dylib/AWDFaceTimeCallConnected.h>
#import <libAWDSupportFramework.dylib/AWDFaceTimeCallDeclineSent.h>
#import <libAWDSupportFramework.dylib/AWDFaceTimeCallEnded.h>
#import <libAWDSupportFramework.dylib/AWDFaceTimeCallFailed.h>
#import <libAWDSupportFramework.dylib/AWDFaceTimeCallInterruptionBegan.h>
#import <libAWDSupportFramework.dylib/AWDFaceTimeCallInterruptionEnded.h>
#import <libAWDSupportFramework.dylib/AWDFaceTimeCallInvitationReceived.h>
#import <libAWDSupportFramework.dylib/AWDFaceTimeCallInvitationSent.h>
#import <libAWDSupportFramework.dylib/AWDFaceTimeCallRelayInitiateReceived.h>
#import <libAWDSupportFramework.dylib/AWDFaceTimeCallRelayInitiateSent.h>
#import <libAWDSupportFramework.dylib/AWDFaceTimeCallRelayUpdateReceived.h>
#import <libAWDSupportFramework.dylib/AWDFaceTimeCallRelayUpdateSent.h>
#import <libAWDSupportFramework.dylib/AWDFaceTimeCallStarted.h>
#import <libAWDSupportFramework.dylib/AWDHoneybeeSignature.h>
#import <libAWDSupportFramework.dylib/AWDIDSAppDeliveryReceipt.h>
#import <libAWDSupportFramework.dylib/AWDIDSClientProcessReceivedMessage.h>
#import <libAWDSupportFramework.dylib/AWDIDSCloudLinkReEstablished.h>
#import <libAWDSupportFramework.dylib/AWDIDSConnectedAfterPipeConnectedTimeInMs.h>
#import <libAWDSupportFramework.dylib/AWDIDSDeviceConnectionDurationEvent.h>
#import <libAWDSupportFramework.dylib/AWDIDSDuplicatedMessage.h>
#import <libAWDSupportFramework.dylib/AWDIDSExternalIPDetectionTime.h>
#import <libAWDSupportFramework.dylib/AWDIDSGenericConnectionSetupDurationEvent.h>
#import <libAWDSupportFramework.dylib/AWDIDSLocalDeliveryAppLevelAck.h>
#import <libAWDSupportFramework.dylib/AWDIDSLocalDeliveryMessageDelivered.h>
#import <libAWDSupportFramework.dylib/AWDIDSLocalDeliveryMessageReceived.h>
#import <libAWDSupportFramework.dylib/AWDIDSLocalDeliveryMessageSent.h>
#import <libAWDSupportFramework.dylib/AWDIDSLocalDeliverySocketClosed.h>
#import <libAWDSupportFramework.dylib/AWDIDSLocalDeliverySocketOpened.h>
#import <libAWDSupportFramework.dylib/AWDIDSLocalMessageRTT.h>
#import <libAWDSupportFramework.dylib/AWDIDSLocalMessageTimedOut.h>
#import <libAWDSupportFramework.dylib/AWDIDSMagnetCorruption.h>
#import <libAWDSupportFramework.dylib/AWDIDSMagnetCorruptionDetailed.h>
#import <libAWDSupportFramework.dylib/AWDIDSMagnetDataCorruptionRecoveryTimeInMs.h>
#import <libAWDSupportFramework.dylib/AWDIDSMessageDeliveryPath.h>
#import <libAWDSupportFramework.dylib/AWDIDSNoteMessageReceived.h>
#import <libAWDSupportFramework.dylib/AWDIDSOTRSessionNegotiation.h>
#import <libAWDSupportFramework.dylib/AWDIDSOutgoingMessageDurationTrace.h>
#import <libAWDSupportFramework.dylib/AWDIDSQRAllocation.h>
#import <libAWDSupportFramework.dylib/AWDIDSQuickRelay.h>
#import <libAWDSupportFramework.dylib/AWDIDSRealTimeEncryptionFirstReceivedPacketMKMTimeDelta.h>
#import <libAWDSupportFramework.dylib/AWDIDSRealTimeEncryptionMembershipChangeEventFirstMKMTimeDelta.h>
#import <libAWDSupportFramework.dylib/AWDIDSRealTimeEncryptionMissingPrekeys.h>
#import <libAWDSupportFramework.dylib/AWDIDSRegistrationAccountStatus.h>
#import <libAWDSupportFramework.dylib/AWDIDSRegistrationAuthenticate.h>
#import <libAWDSupportFramework.dylib/AWDIDSRegistrationAuthenticationParametersReceived.h>
#import <libAWDSupportFramework.dylib/AWDIDSRegistrationCompleted.h>
#import <libAWDSupportFramework.dylib/AWDIDSRegistrationControlChosen.h>
#import <libAWDSupportFramework.dylib/AWDIDSRegistrationOperation.h>
#import <libAWDSupportFramework.dylib/AWDIDSRegistrationPhoneNumberReceivedSMS.h>
#import <libAWDSupportFramework.dylib/AWDIDSRegistrationPhoneNumberValidationFinished.h>
#import <libAWDSupportFramework.dylib/AWDIDSRegistrationProfileHandleOperation.h>
#import <libAWDSupportFramework.dylib/AWDIDSRegistrationProfileOperation.h>
#import <libAWDSupportFramework.dylib/AWDIDSRegistrationRenewCredentialsCompleted.h>
#import <libAWDSupportFramework.dylib/AWDIDSServerStorageStateMachineCompleted.h>
#import <libAWDSupportFramework.dylib/AWDIDSSessionAcceptReceived.h>
#import <libAWDSupportFramework.dylib/AWDIDSSessionAcceptSent.h>
#import <libAWDSupportFramework.dylib/AWDIDSSessionCancelReceived.h>
#import <libAWDSupportFramework.dylib/AWDIDSSessionCancelSent.h>
#import <libAWDSupportFramework.dylib/AWDIDSSessionCompleted.h>
#import <libAWDSupportFramework.dylib/AWDIDSSessionConnected.h>
#import <libAWDSupportFramework.dylib/AWDIDSSessionDeclineReceived.h>
#import <libAWDSupportFramework.dylib/AWDIDSSessionDeclineSent.h>
#import <libAWDSupportFramework.dylib/AWDIDSSessionEnded.h>
#import <libAWDSupportFramework.dylib/AWDIDSSessionInvitationReceived.h>
#import <libAWDSupportFramework.dylib/AWDIDSSessionInvitationSent.h>
#import <libAWDSupportFramework.dylib/AWDIDSSessionReinitiateConnected.h>
#import <libAWDSupportFramework.dylib/AWDIDSSessionReinitiateRequested.h>
#import <libAWDSupportFramework.dylib/AWDIDSSessionReinitiateStarted.h>
#import <libAWDSupportFramework.dylib/AWDIDSSessionStarted.h>
#import <libAWDSupportFramework.dylib/AWDIDSSocketPairConnectionTCPInfo.h>
#import <libAWDSupportFramework.dylib/AWDIDSStreamingReport.h>
#import <libAWDSupportFramework.dylib/AWDIDSUniqueIncomingStreamIDs.h>
#import <libAWDSupportFramework.dylib/AWDIDSWRMLinkRecommendation.h>
#import <libAWDSupportFramework.dylib/AWDIDSWebTunnelRequestCompleted.h>
#import <libAWDSupportFramework.dylib/AWDIDSWiFiSetupAttempt.h>
#import <libAWDSupportFramework.dylib/AWDIDSWiProxConnectionFailed.h>
#import <libAWDSupportFramework.dylib/AWDIDSWiProxConnectionSuccess.h>
#import <libAWDSupportFramework.dylib/AWDIDSWiProxDidConnectToPeer.h>
#import <libAWDSupportFramework.dylib/AWDIDSWiProxDidDisconnectFromPeer.h>
#import <libAWDSupportFramework.dylib/AWDIDSWiProxDidSendData.h>
#import <libAWDSupportFramework.dylib/AWDIMessageAttachmentDownload.h>
#import <libAWDSupportFramework.dylib/AWDIMessageAttachmentUpload.h>
#import <libAWDSupportFramework.dylib/AWDIMessageCloudKitAttachmentDownloadFailed.h>
#import <libAWDSupportFramework.dylib/AWDIMessageCloudKitSyncFailed.h>
#import <libAWDSupportFramework.dylib/AWDIMessageCloudKitValidatePurgeableAttachment.h>
#import <libAWDSupportFramework.dylib/AWDIMessageDeduplicated.h>
#import <libAWDSupportFramework.dylib/AWDIMessageDeliveredMessage.h>
#import <libAWDSupportFramework.dylib/AWDIMessageDowngrade.h>
#import <libAWDSupportFramework.dylib/AWDIMessageHealthCheckPerformed.h>
#import <libAWDSupportFramework.dylib/AWDIMessageNicknamePublished.h>
#import <libAWDSupportFramework.dylib/AWDIMessageNicknameRetrieved.h>
#import <libAWDSupportFramework.dylib/AWDIMessageQueryFinished.h>
#import <libAWDSupportFramework.dylib/AWDIMessageReceivedMessage.h>
#import <libAWDSupportFramework.dylib/AWDIMessageSentMessage.h>
#import <libAWDSupportFramework.dylib/AWDSMSReceivedMessage.h>
#import <libAWDSupportFramework.dylib/AWDSMSSentMessage.h>
#import <libAWDSupportFramework.dylib/AWDIMRemoteURLLoadCompleted.h>
#import <libAWDSupportFramework.dylib/AWDIMRemoteURLLoadFailed.h>
#import <libAWDSupportFramework.dylib/AWDITesterAppStart.h>
#import <libAWDSupportFramework.dylib/AWDITesterApplicationUUID.h>
#import <libAWDSupportFramework.dylib/AWDITesterApplyCustomInputs.h>
#import <libAWDSupportFramework.dylib/AWDITesterCertApplePayTestFinish.h>
#import <libAWDSupportFramework.dylib/AWDITesterCertApplePayTestStart.h>
#import <libAWDSupportFramework.dylib/AWDITesterCertApplePayTestSubmission.h>
#import <libAWDSupportFramework.dylib/AWDITesterCertHomeKitTestFinish.h>
#import <libAWDSupportFramework.dylib/AWDITesterCertHomeKitTestStart.h>
#import <libAWDSupportFramework.dylib/AWDITesterCertHomeKitTestSubmission.h>
#import <libAWDSupportFramework.dylib/AWDITesterCertTestFinish.h>
#import <libAWDSupportFramework.dylib/AWDITesterCertTestStart.h>
#import <libAWDSupportFramework.dylib/AWDITesterCertTestSubmission.h>
#import <libAWDSupportFramework.dylib/AWDITesterTestFinish.h>
#import <libAWDSupportFramework.dylib/AWDITesterTestLoad.h>
#import <libAWDSupportFramework.dylib/AWDITesterTestShare.h>
#import <libAWDSupportFramework.dylib/AWDITesterTestStart.h>
#import <libAWDSupportFramework.dylib/AWDLBClientConnectionReport.h>
#import <libAWDSupportFramework.dylib/AWDLBConnectionReport.h>
#import <libAWDSupportFramework.dylib/AWDLBEndpointsFetchReport.h>
#import <libAWDSupportFramework.dylib/AWDLibnetcoreCellularFallbackReport.h>
#import <libAWDSupportFramework.dylib/AWDLibnetcoreConnectionDataUsageSnapshot.h>
#import <libAWDSupportFramework.dylib/AWDLibnetcoreConnectionStatisticsReport.h>
#import <libAWDSupportFramework.dylib/AWDLibnetcoreMPTCPStatsReport.h>
#import <libAWDSupportFramework.dylib/AWDLibnetcoreMbufStatsReport.h>
#import <libAWDSupportFramework.dylib/AWDLibnetcoreNetworkdStatsReport.h>
#import <libAWDSupportFramework.dylib/AWDLibnetcoreRNFActivityNotification.h>
#import <libAWDSupportFramework.dylib/AWDLibnetcoreStatsReport.h>
#import <libAWDSupportFramework.dylib/AWDLibnetcoreTCPConnectionReport.h>
#import <libAWDSupportFramework.dylib/AWDLibnetcoreTCPECNInterfaceStatsReport.h>
#import <libAWDSupportFramework.dylib/AWDLibnetcoreTCPECNStatsReport.h>
#import <libAWDSupportFramework.dylib/AWDLibnetcoreTCPKernelStats.h>
#import <libAWDSupportFramework.dylib/AWDLibnetcoreTCPStatsReport.h>
#import <libAWDSupportFramework.dylib/AWDLibnetcoreTCPTFOStatsReport.h>
#import <libAWDSupportFramework.dylib/AWDMPTCPConnectionInterfaceReport.h>
#import <libAWDSupportFramework.dylib/AWDMPTCPConnectionReport.h>
#import <libAWDSupportFramework.dylib/AWDMPTCPSubflowSwitchingReport.h>
#import <libAWDSupportFramework.dylib/AWDNWAPIUsage.h>
#import <libAWDSupportFramework.dylib/AWDNWAccumulator.h>
#import <libAWDSupportFramework.dylib/AWDNWActivity.h>
#import <libAWDSupportFramework.dylib/AWDNWActivityEmptyTrigger.h>
#import <libAWDSupportFramework.dylib/AWDNWActivityEpilogue.h>
#import <libAWDSupportFramework.dylib/AWDNWConnectionReport.h>
#import <libAWDSupportFramework.dylib/AWDNWDeviceReport.h>
#import <libAWDSupportFramework.dylib/AWDNWDurationAccumulation.h>
#import <libAWDSupportFramework.dylib/AWDNWDurationAccumulationState.h>
#import <libAWDSupportFramework.dylib/AWDNWL2Report.h>
#import <libAWDSupportFramework.dylib/AWDDNSDomainStats.h>
#import <libAWDSupportFramework.dylib/AWDMDNSResponderDNSMessageSizeStats.h>
#import <libAWDSupportFramework.dylib/AWDMDNSResponderDNSStatistics.h>
#import <libAWDSupportFramework.dylib/AWDMDNSResponderResolveStats.h>
#import <libAWDSupportFramework.dylib/AWDMDNSResponderResolveStatsDNSServer.h>
#import <libAWDSupportFramework.dylib/AWDMDNSResponderResolveStatsDomain.h>
#import <libAWDSupportFramework.dylib/AWDMDNSResponderResolveStatsHostname.h>
#import <libAWDSupportFramework.dylib/AWDMDNSResponderResolveStatsResult.h>
#import <libAWDSupportFramework.dylib/AWDMDNSResponderServicesStats.h>
#import <libAWDSupportFramework.dylib/AWDMMCSChunkingInfo.h>
#import <libAWDSupportFramework.dylib/AWDMMCSError.h>
#import <libAWDSupportFramework.dylib/AWDMMCSGetRequestInfo.h>
#import <libAWDSupportFramework.dylib/AWDMMCSHttpInfo.h>
#import <libAWDSupportFramework.dylib/AWDMMCSPutRequestInfo.h>
#import <libAWDSupportFramework.dylib/AWDMMCSTcpInfo.h>
#import <libAWDSupportFramework.dylib/AWDNanoPhoneEmergencyCallEnded.h>
#import <libAWDSupportFramework.dylib/AWDNanoPhoneIncomingCallConnected.h>
#import <libAWDSupportFramework.dylib/AWDNanoPhoneIncomingCallPresented.h>
#import <libAWDSupportFramework.dylib/AWDNetworkServiceProxyConnectionStatistics.h>
#import <libAWDSupportFramework.dylib/AWDNetworkServiceProxyControlRequestStatistics.h>
#import <libAWDSupportFramework.dylib/AWDNetworkServiceProxyProbeStatistics.h>
#import <libAWDSupportFramework.dylib/AWDNetworkServiceProxyRequestStatistics.h>
#import <libAWDSupportFramework.dylib/AWDOSAnalyticsSubmissions.h>
#import <libAWDSupportFramework.dylib/AWDPairedSyncSyncReport.h>
#import <libAWDSupportFramework.dylib/AWDAppBBPower.h>
#import <libAWDSupportFramework.dylib/AWDAppRRCConnectionStats.h>
#import <libAWDSupportFramework.dylib/AWDBacklightLuxMicroAmpsBucket.h>
#import <libAWDSupportFramework.dylib/AWDBasebandPowerToolKPIs.h>
#import <libAWDSupportFramework.dylib/AWDCpuLoad.h>
#import <libAWDSupportFramework.dylib/AWDLQMDataTransfer.h>
#import <libAWDSupportFramework.dylib/AWDNetworkUsage.h>
#import <libAWDSupportFramework.dylib/AWDPowerApMetrics.h>
#import <libAWDSupportFramework.dylib/AWDPowerAppBBMetrics.h>
#import <libAWDSupportFramework.dylib/AWDPowerAudioMetrics.h>
#import <libAWDSupportFramework.dylib/AWDPowerBBAppRRCMetrics.h>
#import <libAWDSupportFramework.dylib/AWDPowerBBCallMetricInfo.h>
#import <libAWDSupportFramework.dylib/AWDPowerBBCallMetrics.h>
#import <libAWDSupportFramework.dylib/AWDPowerBBLQMDataTransferMetrics.h>
#import <libAWDSupportFramework.dylib/AWDPowerBBNonDataMetrics.h>
#import <libAWDSupportFramework.dylib/AWDPowerBBRATConnectedMetrics.h>
#import <libAWDSupportFramework.dylib/AWDPowerBatteryMetrics.h>
#import <libAWDSupportFramework.dylib/AWDPowerBluetoothMetrics.h>
#import <libAWDSupportFramework.dylib/AWDPowerCameraMetrics.h>
#import <libAWDSupportFramework.dylib/AWDPowerDisplayBacklightMetrics.h>
#import <libAWDSupportFramework.dylib/AWDPowerNetworkUsageMetrics.h>
#import <libAWDSupportFramework.dylib/AWDPowerPerProcessCPULoadMetrics.h>
#import <libAWDSupportFramework.dylib/AWDPowerStateResidencyAndWeight.h>
#import <libAWDSupportFramework.dylib/AWDPowerTouchMetrics.h>
#import <libAWDSupportFramework.dylib/AWDPowerWifiMetrics.h>
#import <libAWDSupportFramework.dylib/AWDRATConnectedPower.h>
#import <libAWDSupportFramework.dylib/AWDPushConnectionConnected.h>
#import <libAWDSupportFramework.dylib/AWDPushConnectionDisconnected.h>
#import <libAWDSupportFramework.dylib/AWDPushFilterChanged.h>
#import <libAWDSupportFramework.dylib/AWDPushFilterSent.h>
#import <libAWDSupportFramework.dylib/AWDPushKeepAliveFailed.h>
#import <libAWDSupportFramework.dylib/AWDPushKeepAliveSent.h>
#import <libAWDSupportFramework.dylib/AWDPushProxyManagerReceive.h>
#import <libAWDSupportFramework.dylib/AWDPushProxyManagerSend.h>
#import <libAWDSupportFramework.dylib/AWDPushReceived.h>
#import <libAWDSupportFramework.dylib/AWDPushReceivedDropped.h>
#import <libAWDSupportFramework.dylib/AWDPushReceivedSlow.h>
#import <libAWDSupportFramework.dylib/AWDPushSent.h>
#import <libAWDSupportFramework.dylib/AWDPushTopicPolicyChange.h>
#import <libAWDSupportFramework.dylib/AWDSafariActivatedHomeScreenQuickActionEvent.h>
#import <libAWDSupportFramework.dylib/AWDSafariAutoFillAuthenticationEvent.h>
#import <libAWDSupportFramework.dylib/AWDSafariAutoFillAuthenticationPreferenceEvent.h>
#import <libAWDSupportFramework.dylib/AWDSafariCKBookmarksMigrationFinishedEvent.h>
#import <libAWDSupportFramework.dylib/AWDSafariCKBookmarksMigrationStartedEvent.h>
#import <libAWDSupportFramework.dylib/AWDSafariCKBookmarksSyncEvent.h>
#import <libAWDSupportFramework.dylib/AWDSafariContactAutoFillDidFillCustomContactSetEvent.h>
#import <libAWDSupportFramework.dylib/AWDSafariContactAutoFillDidSelectSetEvent.h>
#import <libAWDSupportFramework.dylib/AWDSafariContactAutoFillDidShowSetsEvent.h>
#import <libAWDSupportFramework.dylib/AWDSafariDedupedDAVBookmarksEvent.h>
#import <libAWDSupportFramework.dylib/AWDSafariDidReceiveInvalidMessageFromWebProcessEvent.h>
#import <libAWDSupportFramework.dylib/AWDSafariDidTerminateWebProcessBeforeNavigation.h>
#import <libAWDSupportFramework.dylib/AWDSafariDuplicatedPasswordsWarningEvent.h>
#import <libAWDSupportFramework.dylib/AWDSafariEnterPasswordsPreferencesEvent.h>
#import <libAWDSupportFramework.dylib/AWDSafariEnterTwoUpEvent.h>
#import <libAWDSupportFramework.dylib/AWDSafariInteractedWithGeneratedPasswordEvent.h>
#import <libAWDSupportFramework.dylib/AWDSafariPageLoadCompleteEvent.h>
#import <libAWDSupportFramework.dylib/AWDSafariPageLoadStartedEvent.h>
#import <libAWDSupportFramework.dylib/AWDSafariParticipatedInPasswordAutoFill.h>
#import <libAWDSupportFramework.dylib/AWDSafariReaderActiveOptInOutEvent.h>
#import <libAWDSupportFramework.dylib/AWDSafariReaderChangedOptInOutEvent.h>
#import <libAWDSupportFramework.dylib/AWDSafariSafeBrowsingUserActionAfterSeeingWarningEvent.h>
#import <libAWDSupportFramework.dylib/AWDSafariSafeBrowsingWarningShownEvent.h>
#import <libAWDSupportFramework.dylib/AWDSafariSelectedFavoritesGridItemEvent.h>
#import <libAWDSupportFramework.dylib/AWDSafariSetAutoFillQuickTypeSuggestionEvent.h>
#import <libAWDSupportFramework.dylib/AWDSafariSharedPasswordEvent.h>
#import <libAWDSupportFramework.dylib/AWDSafariTappedAutoFillQuickTypeSuggestionEvent.h>
#import <libAWDSupportFramework.dylib/AWDSafariTappedOnToolbarButtonEvent.h>
#import <libAWDSupportFramework.dylib/AWDSafariTwoFingerTappedOnLinkEvent.h>
#import <libAWDSupportFramework.dylib/AWDSafariUnableToSilentlyMigrateToCKBookmarksEvent.h>
#import <libAWDSupportFramework.dylib/AWDSafariUsingPrivateBrowsingEvent.h>
#import <libAWDSupportFramework.dylib/AWDSafariVersioningEvent.h>
#import <libAWDSupportFramework.dylib/AWDSafariViewControllerDismissedEvent.h>
#import <libAWDSupportFramework.dylib/AWDSafariViewControllerPresentedFromHostAppEvent.h>
#import <libAWDSupportFramework.dylib/AWDSafariViewControllerTappedOnToolbarButtonEvent.h>
#import <libAWDSupportFramework.dylib/AWDSiriNetworkAnalyzerRun.h>
#import <libAWDSupportFramework.dylib/AWDSiriRequestRecord.h>
#import <libAWDSupportFramework.dylib/AWDSiriServerConnectionFailed.h>
#import <libAWDSupportFramework.dylib/AWDSiriServerConnectionOpen.h>
#import <libAWDSupportFramework.dylib/AWDSiriServerConnectionStart.h>
#import <libAWDSupportFramework.dylib/AWDSiriSession.h>
#import <libAWDSupportFramework.dylib/AWDSiriSessionLoadTimeout.h>
#import <libAWDSupportFramework.dylib/AWDSiriSpeechRecognized.h>
#import <libAWDSupportFramework.dylib/AWDSiriVoiceRecordingEnd.h>
#import <libAWDSupportFramework.dylib/AWDSiriVoiceRecordingStart.h>
#import <libAWDSupportFramework.dylib/AWDSiriVoiceSendEnd.h>
#import <libAWDSupportFramework.dylib/AWDSiriVoiceSendStart.h>
#import <libAWDSupportFramework.dylib/AWDTCPConnectionInfo.h>
#import <libAWDSupportFramework.dylib/AWDTransportHistoryRecord.h>
#import <libAWDSupportFramework.dylib/AWDSOSAutomaticCallCountdownEnabled.h>
#import <libAWDSupportFramework.dylib/AWDSOSAutomaticNewtonEnabled.h>
#import <libAWDSupportFramework.dylib/AWDSOSLongPressTriggersEmergencySOS.h>
#import <libAWDSupportFramework.dylib/AWDSOSNumberOfVoiceLoops.h>
#import <libAWDSupportFramework.dylib/AWDSOSShouldPlayAudioDuringCountdown.h>
#import <libAWDSupportFramework.dylib/AWDSOSTriggered.h>
#import <libAWDSupportFramework.dylib/AWDSpringBoardAppBrightness.h>
#import <libAWDSupportFramework.dylib/AWDSpringBoardBiometricUnlock.h>
#import <libAWDSupportFramework.dylib/AWDSpringBoardBreadcrumb.h>
#import <libAWDSupportFramework.dylib/AWDSpringBoardClawGesture.h>
#import <libAWDSupportFramework.dylib/AWDSpringBoardDoNotDisturbChange.h>
#import <libAWDSupportFramework.dylib/AWDSpringBoardFolderStats.h>
#import <libAWDSupportFramework.dylib/AWDSpringBoardIconLaunch.h>
#import <libAWDSupportFramework.dylib/AWDSpringBoardPressSequence.h>
#import <libAWDSupportFramework.dylib/AWDSpringBoardSOSAlertResponse.h>
#import <libAWDSupportFramework.dylib/AWDSpringBoardSwitcherPresentationInteraction.h>
#import <libAWDSupportFramework.dylib/AWDSpringBoardSwitcherToAppTransition.h>
#import <libAWDSupportFramework.dylib/AWDSpringBoardSystemGesture.h>
#import <libAWDSupportFramework.dylib/AWDTuple.h>
#import <libAWDSupportFramework.dylib/AWDVPNSession.h>
#import <libAWDSupportFramework.dylib/AWDChipCountersRx.h>
#import <libAWDSupportFramework.dylib/AWDChipCountersTx.h>
#import <libAWDSupportFramework.dylib/AWDChipErrorCountersTx.h>
#import <libAWDSupportFramework.dylib/AWDControlFrames.h>
#import <libAWDSupportFramework.dylib/AWDDataFrames.h>
#import <libAWDSupportFramework.dylib/AWDHEStats.h>
#import <libAWDSupportFramework.dylib/AWDLinkQualityMeasurements.h>
#import <libAWDSupportFramework.dylib/AWDMacCountersRx.h>
#import <libAWDSupportFramework.dylib/AWDMacCountersRxErrors.h>
#import <libAWDSupportFramework.dylib/AWDManagementFrames.h>
#import <libAWDSupportFramework.dylib/AWDNwExclusionCount.h>
#import <libAWDSupportFramework.dylib/AWDOMICntrs.h>
#import <libAWDSupportFramework.dylib/AWDRxPhyErrors.h>
#import <libAWDSupportFramework.dylib/AWDScanStatsPerSlice.h>
#import <libAWDSupportFramework.dylib/AWDSidecarBssSteering.h>
#import <libAWDSupportFramework.dylib/AWDSidecarHistogramBin.h>
#import <libAWDSupportFramework.dylib/AWDSidecarPeerTraffic.h>
#import <libAWDSupportFramework.dylib/AWDSlowWiFiNotification.h>
#import <libAWDSupportFramework.dylib/AWDSlowWiFiReport.h>
#import <libAWDSupportFramework.dylib/AWDWADiagnosisActionAssociationDifferences.h>
#import <libAWDSupportFramework.dylib/AWDWAQuickDpsStats.h>
#import <libAWDSupportFramework.dylib/AWDWPA2Counters.h>
#import <libAWDSupportFramework.dylib/AWDWiFiActionFrameEvent.h>
#import <libAWDSupportFramework.dylib/AWDWiFiAwdlSidecar.h>
#import <libAWDSupportFramework.dylib/AWDWiFiAwdlSidecarCoalesced.h>
#import <libAWDSupportFramework.dylib/AWDWiFiBlacklistingEvent.h>
#import <libAWDSupportFramework.dylib/AWDWiFiCLTM.h>
#import <libAWDSupportFramework.dylib/AWDWiFiCLTMSliceSpecific.h>
#import <libAWDSupportFramework.dylib/AWDWiFiConnectionQuality.h>
#import <libAWDSupportFramework.dylib/AWDWiFiDPSAWDLSnapshot.h>
#import <libAWDSupportFramework.dylib/AWDWiFiDPSActiveProbeStats.h>
#import <libAWDSupportFramework.dylib/AWDWiFiDPSBTSnapshot.h>
#import <libAWDSupportFramework.dylib/AWDWiFiDPSCountersSample.h>
#import <libAWDSupportFramework.dylib/AWDWiFiDPSEpilogue.h>
#import <libAWDSupportFramework.dylib/AWDWiFiDPSNotification.h>
#import <libAWDSupportFramework.dylib/AWDWiFiDPSPerACTxCompletionSnapshot.h>
#import <libAWDSupportFramework.dylib/AWDWiFiDPSReport.h>
#import <libAWDSupportFramework.dylib/AWDWiFiDPSSnapshot.h>
#import <libAWDSupportFramework.dylib/AWDWiFiLPMReport.h>
#import <libAWDSupportFramework.dylib/AWDWiFiLTECoexBin.h>
#import <libAWDSupportFramework.dylib/AWDWiFiLTECoexCounters.h>
#import <libAWDSupportFramework.dylib/AWDWiFiLTECoexTxBlanking.h>
#import <libAWDSupportFramework.dylib/AWDWiFiLTEWCI2Counters.h>
#import <libAWDSupportFramework.dylib/AWDWiFiLTEWCI2CountersSliceSpecific.h>
#import <libAWDSupportFramework.dylib/AWDWiFiLprxStats.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetric11axLinkChangeData.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetric11axStats.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricActiveProbeStats.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricCustomNetworkSetting.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricExtendedTrapInfo.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricHotspotTransportType.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricIPv4DHCPLatency.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricInterfaceStats.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricJoinTimeout.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricLinkChangeData.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricNetworkPrefs.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricRssiHistory.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricScanStats.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricWiFiStats.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricWowState.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsAssociationHistory.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsAutoJoinNwExclusion.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsHealthUIEvent.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsKnownNetworksEvent.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsManagerAssociationEvent.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsManagerAutoJoinCumulative.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsManagerAutoJoinRecord.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsManagerAutoJoinSession.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsManagerAwdlUsage.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsManagerBGScanBlacklistedNetworks.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsManagerBTCoexModeChange.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsManagerBTCoexStats.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsManagerBlacklistedNetworkInfo.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsManagerBlacklistingInstanceInfo.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsManagerChipCounters.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsManagerChipMemory.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsManagerDeviceCount.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsManagerEvent.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsManagerFrameCounterStats.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsManagerInfraInterface.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsManagerLastSSIDInfo.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsManagerLeakyAPStats.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsManagerLinkQualityStats.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsManagerNetworkTransitionCumulative.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsManagerNetworkTransitionRecord.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsManagerNetworkTransitionSession.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsManagerOneStatsAssociationInfo.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsManagerP2pLegacyUsageReport.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsManagerPowerStatsUpdateEvent.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsManagerPowerStickiness.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsManagerRCU1CoexModeChange.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsManagerRangingReport.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsManagerRoamStatus.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsManagerSoftError.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsManagerSoftErrorUserFeedback.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsManagerStateMachine.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsManagerUserBlacklistEvent.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsManagerWatchdogEvent.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsManagerWifidAvailability.h>
#import <libAWDSupportFramework.dylib/AWDWiFiMetricsScanObj.h>
#import <libAWDSupportFramework.dylib/AWDWiFiNWActivity.h>
#import <libAWDSupportFramework.dylib/AWDWiFiNWActivityAggregateMetrics.h>
#import <libAWDSupportFramework.dylib/AWDWiFiNWActivityAssoc.h>
#import <libAWDSupportFramework.dylib/AWDWiFiNWActivityBtCoex.h>
#import <libAWDSupportFramework.dylib/AWDWiFiNWActivityBtCoexReqestReason.h>
#import <libAWDSupportFramework.dylib/AWDWiFiNWActivityControllerStats.h>
#import <libAWDSupportFramework.dylib/AWDWiFiNWActivityHistogramBin.h>
#import <libAWDSupportFramework.dylib/AWDWiFiNWActivityImpedingFunctions.h>
#import <libAWDSupportFramework.dylib/AWDWiFiNWActivityInterfaceStats.h>
#import <libAWDSupportFramework.dylib/AWDWiFiNWActivityPeerStats.h>
#import <libAWDSupportFramework.dylib/AWDWiFiNWActivityPerACTxCompletions.h>
#import <libAWDSupportFramework.dylib/AWDWiFiNWActivityPowerPStats.h>
#import <libAWDSupportFramework.dylib/AWDWiFiNWActivityPowerStats.h>
#import <libAWDSupportFramework.dylib/AWDWiFiNWActivityRateAndAggregation.h>
#import <libAWDSupportFramework.dylib/AWDWiFiNWActivityScanActivity.h>
#import <libAWDSupportFramework.dylib/AWDWiFiNWActivityStateBin.h>
#import <libAWDSupportFramework.dylib/AWDWiFiNWActivityTraffic.h>
#import <libAWDSupportFramework.dylib/AWDWiFiNWActivityTxCompletions.h>
#import <libAWDSupportFramework.dylib/AWDWiFiOtaSystemInfo.h>
#import <libAWDSupportFramework.dylib/AWDWiFiP2PAirplayMetrics.h>
#import <libAWDSupportFramework.dylib/AWDWiFiRangingRttData.h>
#import <libAWDSupportFramework.dylib/AWDWiFiRetStats.h>
#import <libAWDSupportFramework.dylib/AWDWiFiSDB.h>
#import <libAWDSupportFramework.dylib/AWDWiFiSDBSliceSpecific.h>
#import <libAWDSupportFramework.dylib/AWDWiFiSlowWiFiReport.h>
#import <libAWDSupportFramework.dylib/AWDWiFiSoftAP.h>
#import <libAWDSupportFramework.dylib/AWDWiFiSoftAPClient.h>
#import <libAWDSupportFramework.dylib/AWDWiFiTxInhibitEvent.h>
#import <libAWDSupportFramework.dylib/AWDWiFiUIConfigureEvent.h>
#import <libAWDSupportFramework.dylib/AWDWiFiUIEvent.h>
#import <libAWDSupportFramework.dylib/AWDWiFiUIJoinEvent.h>
#import <libAWDSupportFramework.dylib/AWDWiFiUIScanCount.h>
#import <libAWDSupportFramework.dylib/AWDWiFiUIScanSession.h>
#import <libAWDSupportFramework.dylib/AWDWiFiWcpsStats.h>
#import <libAWDSupportFramework.dylib/AWDWifiAssociation.h>
#import <libAWDSupportFramework.dylib/AWDWifiAwdlD2dMigrationStats.h>
#import <libAWDSupportFramework.dylib/AWDWifiAwdlHistogramBin.h>
#import <libAWDSupportFramework.dylib/AWDWifiAwdlServiceRecord.h>
#import <libAWDSupportFramework.dylib/AWDWifiAwdlStateInfo.h>
#import <libAWDSupportFramework.dylib/AWDWifiHardwareVersion.h>
#import <libAWDSupportFramework.dylib/AWDWifiLinkQualityRecord.h>
#import <libAWDSupportFramework.dylib/AWDWifiMetricWiFiTetheredDeviceOUI.h>
#import <libAWDSupportFramework.dylib/AWDWifiMostUsedNetworks.h>
#import <libAWDSupportFramework.dylib/AWDWifiP2PAirplayHistogramBin.h>
#import <libAWDSupportFramework.dylib/AWDWifiPowerState.h>
#import <libAWDSupportFramework.dylib/AWDWifiStats.h>
#import <libAWDSupportFramework.dylib/AWDWifiCallingCallEndReport.h>
#import <libAWDSupportFramework.dylib/AWDThroughputEvaluation.h>
#import <libAWDSupportFramework.dylib/AWDWRMAntSelPolicyStats.h>
#import <libAWDSupportFramework.dylib/AWDWRMFacetimeRecommendation.h>
#import <libAWDSupportFramework.dylib/AWDWRMLinkPrefChange1.h>
#import <libAWDSupportFramework.dylib/AWDWRMLinkPrefChange2.h>
#import <libAWDSupportFramework.dylib/AWDWRMLinkPrefChangeEvent.h>
#import <libAWDSupportFramework.dylib/AWDWRMLinkPrefInit.h>
#import <libAWDSupportFramework.dylib/AWDWRMLinkStateChange.h>
#import <libAWDSupportFramework.dylib/AWDWRMStreamingReport.h>
#import <libAWDSupportFramework.dylib/AWDWRMULCACoexStats.h>
#import <libAWDSupportFramework.dylib/AWDWRMWiFiCallingEnd.h>
#import <libAWDSupportFramework.dylib/AWDWRMWiFiCell5GData.h>
