//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"
#import "NSSecureCoding-Protocol.h"

@class NSUUID;

@interface BackendXPC : NSObject <NSSecureCoding, NSCoding>
{
    unique_ptr_e7519619 _cryptoHeader;	// 8 = 0x8
    shared_ptr_90e31b53 _backend;	// 16 = 0x10
}

+ (_Bool)supportsSecureCoding;	// IMP=0x0000000100023d6c
- (id).cxx_construct;	// IMP=0x00000001000241e4
- (void).cxx_destruct;	// IMP=0x00000001000241b8
@property(nonatomic) shared_ptr_90e31b53 backend; // @synthesize backend=_backend;
- (id)description;	// IMP=0x0000000100024100
- (unique_ptr_e7519619 *)getCryptoHeader;	// IMP=0x00000001000240f8
- (_Bool)checkIfEncrypted;	// IMP=0x0000000100023fb0
@property(readonly, nonatomic) NSUUID *instanceID;
- (id)initWithBackend:(shared_ptr_90e31b53)arg1;	// IMP=0x0000000100023e14
- (void)encodeWithCoder:(id)arg1;	// IMP=0x0000000100023da8
- (id)initWithCoder:(id)arg1;	// IMP=0x0000000100023d74

@end

