//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtCC7remindd12RDDebouncing10LoadFactor : _TtCs12_SwiftObject
{
    MISSING_TYPE *windowSize;	// 16 = 0x10
    MISSING_TYPE *thresholdForNewWindow;	// 24 = 0x18
    MISSING_TYPE *averageInterval;	// 32 = 0x20
    MISSING_TYPE *numOfSamples;	// 40 = 0x28
    MISSING_TYPE *measurements;	// 48 = 0x30
    MISSING_TYPE *lastFire;	// 1163157343 = 0x45545f5f
}

@end

