//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC7remindd28RDXPCActivityTimeEventStream : _TtCs12_SwiftObject
{
    MISSING_TYPE *queue;	// 16 = 0x10
    MISSING_TYPE *name;	// 24 = 0x18
    MISSING_TYPE *xpcEventStream;	// 40 = 0x28
    MISSING_TYPE *xpcEventStreamToken;	// 0 = 0x0
    MISSING_TYPE *eventHandler;	// 1852404340 = 0x6e697274
}

@end

