//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC15InvernessClient20InvernessClientLocal : _TtCs12_SwiftObject
{
    MISSING_TYPE *containerName;	// 16 = 0x10
    MISSING_TYPE *databaseType;	// 32 = 0x20
    MISSING_TYPE *apiToken;	// 40 = 0x28
    MISSING_TYPE *localServer;	// 0 = 0x0
}

@end

