//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <CoreData/NSManagedObjectContext.h>

@class NSString;

@interface NSManagedObjectContext (IC)
- (void)ic_performBlockAndWait:(CDUnknownBlockType)arg1 andPerformBlockAndWaitOnMainThread:(CDUnknownBlockType)arg2;	// IMP=0x000000010006a318
- (void)ic_performBlock:(CDUnknownBlockType)arg1 andPerformBlockOnMainThread:(CDUnknownBlockType)arg2;	// IMP=0x000000010006a1dc
- (_Bool)ic_saveWithLogDescription:(id)arg1;	// IMP=0x000000010006a00c
- (_Bool)ic_save;	// IMP=0x0000000100069ffc
@property(retain, nonatomic) NSString *ic_debugName;
@end

