//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "REMCDObject.h"

@class NSDate, NSString, NSUUID, REMCDSmartList;

@interface REMCDSmartListOrder : REMCDObject
{
}

+ (id)cdEntityName;	// IMP=0x000000010006b808
+ (id)fetchRequest;	// IMP=0x0000000100004b48
- (_Bool)isConnectedToAccountObject:(id)arg1;	// IMP=0x00000001000677e4

// Remaining properties
@property(nonatomic) double end; // @dynamic end;
@property(copy, nonatomic) NSDate *lastModifiedDate; // @dynamic lastModifiedDate;
@property(copy, nonatomic) NSUUID *reminderID; // @dynamic reminderID;
@property(retain, nonatomic) REMCDSmartList *smartList; // @dynamic smartList;
@property(copy, nonatomic) NSString *smartListTag; // @dynamic smartListTag;
@property(nonatomic) double start; // @dynamic start;

@end

