/*
* This header is generated by classdump-dyld 1.0
* on Sunday, September 27, 2020 at 11:38:33 AM Mountain Standard Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /usr/lib/libnetwork.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/OS_nw_interface_status_monitor.h>

@protocol OS_nw_interface, OS_nw_channel, OS_dispatch_queue;
@class NSObject, NSString;

@interface NWConcrete_nw_interface_status_monitor : NSObject <OS_nw_interface_status_monitor> {

	NSObject*<OS_nw_interface> interface;
	NSObject*<OS_nw_channel> channel;
	/*^block*/id packet_handler;
	NSObject*<OS_dispatch_queue> packet_handler_queue;
	/*^block*/id update_handler;
	NSObject*<OS_dispatch_queue> update_handler_queue;
	void* channel_event_source;
	void* interface_advisory_source;
	unsigned cancelled : 1;
	unsigned __pad_bits : 7;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)dealloc;
-(id)init;
-(NSString *)description;
@end

