/*
* This header is generated by classdump-dyld 1.0
* on Sunday, September 27, 2020 at 11:38:33 AM Mountain Standard Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /usr/lib/libnetwork.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libnetwork.dylib/libnetwork.dylib-Structs.h>
#import <libnetwork.dylib/NWConcrete_nw_endpoint.h>

@interface NWOSAddressEndpoint : NWConcrete_nw_endpoint {

	sockaddr_storage address;
	ether_addr ethernet_address;
	char* hostname;
	int original_fd;
	unsigned short priority;
	unsigned calculated_hostname : 1;

}
-(unsigned short)port;
-(id)copyDictionary;
-(char*)createDescription:(BOOL)arg1 ;
-(id)copyEndpoint;
-(void)setPriority:(unsigned short)arg1 ;
-(void)dealloc;
-(BOOL)isEqualToEndpoint:(id)arg1 matchInterface:(BOOL)arg2 matchParent:(BOOL)arg3 ;
-(const char*)hostname;
-(unsigned)type;
-(unsigned short)priority;
-(unsigned long long)getHash;
@end

