//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "AVCaptureMetadataOutputObjectsDelegate-Protocol.h"

@class AVCaptureDeviceInput, AVCaptureMetadataOutput, AVCaptureSession, AVCaptureVideoDataOutput, CMMediaSession, NSMutableDictionary, NSString, NSUserDefaults;
@protocol OS_dispatch_queue;

@interface RMAudioListenerPoseEngine : NSObject <AVCaptureMetadataOutputObjectsDelegate>
{
    _Bool _faceKitEnabled;	// 8 = 0x8
    _Bool _facePoseVerboseLoggingEnabled;	// 9 = 0x9
    NSMutableDictionary *_clients;	// 16 = 0x10
    NSObject<OS_dispatch_queue> *_producerQueue;	// 24 = 0x18
    NSObject<OS_dispatch_queue> *_captureQueue;	// 32 = 0x20
    unsigned long long _interval;	// 40 = 0x28
    CMMediaSession *_mediaSession;	// 48 = 0x30
    NSUserDefaults *_defaults;	// 56 = 0x38
    AVCaptureSession *_captureSession;	// 64 = 0x40
    AVCaptureDeviceInput *_captureDeviceInput;	// 72 = 0x48
    AVCaptureVideoDataOutput *_videoDataOutput;	// 80 = 0x50
    AVCaptureMetadataOutput *_metadataOutput;	// 88 = 0x58
}

+ (id)sharedInstance;	// IMP=0x0000000100004fb4
- (void).cxx_destruct;	// IMP=0x0000000100007394
- (void)captureOutput:(id)arg1 didOutputMetadataObjects:(id)arg2 fromConnection:(id)arg3;	// IMP=0x0000000100006ba8
- (void)stopProducingDataForObject:(id)arg1;	// IMP=0x0000000100005d1c
- (id)startProducingDataForObject:(id)arg1 updateInterval:(unsigned long long)arg2 callback:(CDUnknownBlockType)arg3;	// IMP=0x0000000100005198
- (id)init;	// IMP=0x0000000100005020

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

