//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <CloudKit/CKRecordZoneID.h>

@interface CKRecordZoneID (FMF)
- (id)fmf_withCurrentUserDefaultName;	// IMP=0x0000000100005820
@end

