//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "FMFBaseCmd.h"

@class NSString;

@interface FMFImportCommand : FMFBaseCmd
{
    NSString *_responseId;	// 16 = 0x10
    NSString *_mappingPacketToken;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x000000010002a650
@property(retain, nonatomic) NSString *mappingPacketToken; // @synthesize mappingPacketToken=_mappingPacketToken;
@property(copy, nonatomic) NSString *responseId; // @synthesize responseId=_responseId;
- (void)processCommandResponse:(id)arg1;	// IMP=0x000000010002a390
- (id)jsonBodyDictionary;	// IMP=0x000000010002a300
- (id)pathSuffix;	// IMP=0x000000010002a2f4
- (id)initWithClientSession:(id)arg1 mappingPacketToken:(id)arg2;	// IMP=0x000000010002a238

@end

