//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface FMFSystemInfo : NSObject
{
}

+ (id)sharedInstance;	// IMP=0x0000000100021364
- (_Bool)isAudioAccessory;	// IMP=0x0000000100021e38
- (_Bool)isFMFAppRemoved;	// IMP=0x0000000100021e30
- (id)iCloudAccountName;	// IMP=0x0000000100021dac
- (_Bool)isBuddyDone;	// IMP=0x0000000100021da4
- (_Bool)isInMultiUserMode;	// IMP=0x0000000100021d9c
- (int)processId;	// IMP=0x0000000100021d48
- (unsigned long long)unlockState;	// IMP=0x0000000100021cf8
- (_Bool)isLocked;	// IMP=0x0000000100021ccc
- (id)regionCode;	// IMP=0x0000000100021cc4
- (_Bool)e928760c5fbc1719e59c427e2be01ce6;	// IMP=0x0000000100021cbc
- (id)deviceModelName;	// IMP=0x0000000100021cb4
- (id)deviceName;	// IMP=0x0000000100021cac
- (id)appName;	// IMP=0x0000000100021c24
- (id)osVersion;	// IMP=0x0000000100021c1c
- (id)osName;	// IMP=0x0000000100021c14
- (id)deviceUDID;	// IMP=0x0000000100021c0c
- (id)longVersionString;	// IMP=0x0000000100021b68
- (id)osBuildVersion;	// IMP=0x0000000100021aac
- (id)clientInfoVersionTagString;	// IMP=0x00000001000217f4
- (id)sourceVersionFromVersionFile;	// IMP=0x0000000100021688
- (id)buildVersion;	// IMP=0x0000000100021534
- (id)sourceVersion;	// IMP=0x000000010002152c
- (id)bundleIdentifier;	// IMP=0x00000001000214c8
- (long long)bundleVersion;	// IMP=0x0000000100021444
- (id)appVersion;	// IMP=0x00000001000213e0
- (id)deviceClass;	// IMP=0x00000001000213d8
- (id)productType;	// IMP=0x00000001000213d0

@end

