//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, NSString;

@interface MBAnalyticsEvent : NSObject
{
    NSMutableDictionary *_metrics;	// 8 = 0x8
    NSString *_eventName;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x00000001000098d4
- (_Bool)submit;	// IMP=0x0000000100009608
- (void)addFileSize:(unsigned long long)arg1 containerID:(id)arg2 aggregateDictionaryGroup:(id)arg3;	// IMP=0x0000000100009310
- (void)accumulateMetric:(id)arg1 value:(unsigned long long)arg2;	// IMP=0x0000000100009144
- (void)setMetric:(id)arg1 value:(unsigned long long)arg2;	// IMP=0x0000000100008fc4
- (id)initWithEventName:(id)arg1;	// IMP=0x0000000100008f20

@end

