//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MBEngine;

@interface MBRetryStrategy : NSObject
{
    MBEngine *_engine;	// 8 = 0x8
    double _lastAttemptStartTime;	// 16 = 0x10
    double _consecutiveRetryStartTime;	// 24 = 0x18
    unsigned long long _totalRetryCount;	// 32 = 0x20
    unsigned long long _consecutiveRetryCount;	// 40 = 0x28
    unsigned long long _softConsecutiveRetryLimit;	// 48 = 0x30
    unsigned long long _hardConsecutiveRetryLimit;	// 56 = 0x38
    double _resetConsecutiveRetriesTimeInterval;	// 64 = 0x40
    double _forcedRetryTimeInterval;	// 72 = 0x48
    double _networkRetryTimeInterval;	// 80 = 0x50
    double _maximumServiceUnavailableRetryInterval;	// 88 = 0x58
}

@property(nonatomic) double maximumServiceUnavailableRetryInterval; // @synthesize maximumServiceUnavailableRetryInterval=_maximumServiceUnavailableRetryInterval;
@property(nonatomic) double networkRetryTimeInterval; // @synthesize networkRetryTimeInterval=_networkRetryTimeInterval;
@property(nonatomic) double forcedRetryTimeInterval; // @synthesize forcedRetryTimeInterval=_forcedRetryTimeInterval;
@property(nonatomic) double resetConsecutiveRetriesTimeInterval; // @synthesize resetConsecutiveRetriesTimeInterval=_resetConsecutiveRetriesTimeInterval;
@property(nonatomic) unsigned long long hardConsecutiveRetryLimit; // @synthesize hardConsecutiveRetryLimit=_hardConsecutiveRetryLimit;
@property(nonatomic) unsigned long long softConsecutiveRetryLimit; // @synthesize softConsecutiveRetryLimit=_softConsecutiveRetryLimit;
@property(nonatomic) unsigned long long consecutiveRetryCount; // @synthesize consecutiveRetryCount=_consecutiveRetryCount;
- (_Bool)shouldRetryAfterError:(id)arg1 hard:(_Bool)arg2;	// IMP=0x0000000100037064
- (_Bool)canRetryAfterError:(id)arg1;	// IMP=0x0000000100037040
- (_Bool)wouldRetry;	// IMP=0x000000010003702c
- (id)initWithEngine:(id)arg1;	// IMP=0x0000000100036fb4

@end

