//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import "NSCopying-Protocol.h"

@class NSData;

@interface NRGPBDataHeader : PBCodable <NSCopying>
{
    NSData *_checksumData;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0000000100008d74
@property(retain, nonatomic) NSData *checksumData; // @synthesize checksumData=_checksumData;
- (void)mergeFrom:(id)arg1;	// IMP=0x0000000100008d30
- (unsigned long long)hash;	// IMP=0x0000000100008d18
- (_Bool)isEqual:(id)arg1;	// IMP=0x0000000100008c78
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0000000100008bfc
- (void)copyTo:(id)arg1;	// IMP=0x0000000100008bdc
- (void)writeTo:(id)arg1;	// IMP=0x0000000100008b94
- (_Bool)readFrom:(id)arg1;	// IMP=0x0000000100008b8c
- (id)dictionaryRepresentation;	// IMP=0x0000000100008990
- (id)description;	// IMP=0x00000001000088dc

@end

