//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MLModel;

@interface iRATBW : NSObject
{
    MLModel *_model;	// 8 = 0x8
}

+ (id)urlOfModelInThisBundle;	// IMP=0x00000001000fe71c
@property(readonly, nonatomic) MLModel *model; // @synthesize model=_model;
- (id)predictionsFromInputs:(id)arg1 options:(id)arg2 error:(id *)arg3;	// IMP=0x00000001000fee7c
- (id)predictionFromCca:(double)arg1 wifiRssi_raw:(double)arg2 rx_retry:(double)arg3 weighted_average_phyrate_rx:(double)arg4 weighted_average_rssi:(double)arg5 weighted_average_snr:(double)arg6 maxOfActualLowBandwidth_ARCHIVE_20200212_REMOVE:(double)arg7 device_point_of_interest:(double)arg8 txber:(double)arg9 error:(id *)arg10;	// IMP=0x00000001000fedc4
- (id)predictionFromFeatures:(id)arg1 options:(id)arg2 error:(id *)arg3;	// IMP=0x00000001000fed18
- (id)predictionFromFeatures:(id)arg1 error:(id *)arg2;	// IMP=0x00000001000feca4
- (id)initWithModelCollectionEntry:(id)arg1 configuration:(id)arg2 error:(id *)arg3;	// IMP=0x00000001000febb4
- (id)initWithModelCollectionEntry:(id)arg1 error:(id *)arg2;	// IMP=0x00000001000feacc
- (id)initWithContentsOfURL:(id)arg1 configuration:(id)arg2 error:(id *)arg3;	// IMP=0x00000001000fea04
- (id)initWithConfiguration:(id)arg1 error:(id *)arg2;	// IMP=0x00000001000fe990
- (id)initWithContentsOfURL:(id)arg1 error:(id *)arg2;	// IMP=0x00000001000fe8d0
- (id)init;	// IMP=0x00000001000fe864

@end

