//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WCM_CoexMonitor : NSObject
{
}

+ (id)create;	// IMP=0x000000010005ab3c
- (unsigned long long)getCoexBandErrorCountFor:(int)arg1;	// IMP=0x000000010005ab1c
- (unsigned long long)getCoexErrorCountFor:(int)arg1;	// IMP=0x000000010005aafc
- (unsigned long long)getCoexCountDurationFor:(int)arg1;	// IMP=0x000000010005aadc
- (unsigned long long)getCoexCountFor:(int)arg1;	// IMP=0x000000010005aabc
- (void)updateCoexErrorFor:(int)arg1 inBand:(int)arg2;	// IMP=0x000000010005aaa0
- (void)updateCoexCondition:(int)arg1 inBand:(int)arg2 state:(_Bool)arg3;	// IMP=0x000000010005aa7c
- (id)init;	// IMP=0x000000010005aa2c

@end

