//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WCM_Logging : NSObject
{
}

+ (void)setiRATSettingsToPreferences:(_Bool)arg1;	// IMP=0x00000001000938c4
+ (void)reloadiRATSettingsFromPreferences;	// IMP=0x0000000100093738
+ (void)logLevel:(int)arg1 message:(id)arg2;	// IMP=0x0000000100093038
+ (void)logToFile:(id)arg1;	// IMP=0x0000000100092b24
+ (int)getNumberOfSavedLogFiles:(int *)arg1 new:(int *)arg2;	// IMP=0x0000000100092788
+ (void)reloadLogSettingsFromPreferences;	// IMP=0x000000010009251c
+ (void)setLogSettingsToPreferences;	// IMP=0x000000010009236c
+ (void)initSettingsFromPreferences;	// IMP=0x0000000100091dd8
+ (_Bool)isLogLevelEnabled:(int)arg1;	// IMP=0x0000000100091d98
+ (void)setCurrentLogLevel:(unsigned int)arg1;	// IMP=0x0000000100091d70
+ (_Bool)getLogToFile;	// IMP=0x0000000100091d48
+ (void)setLogToFile:(_Bool)arg1;	// IMP=0x0000000100091d14

@end

