//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WRM_Mobility_Context.h"

@interface WRM_TerminusContext : WRM_Mobility_Context
{
    _Bool _mTerminusIsRegistered;	// 136 = 0x88
    _Bool _mForceUpdateNeeded;	// 137 = 0x89
    _Bool _mClientSubscriptionValid;	// 138 = 0x8a
    _Bool _mIsRetry;	// 139 = 0x8b
    _Bool _mBtLinkRecommendationUpdateNeeded;	// 140 = 0x8c
    _Bool _mCompanionWifiLinkRecommendationUpdateNeeded;	// 141 = 0x8d
    _Bool _mDirectWifiLinkRecommendationUpdateNeeded;	// 142 = 0x8e
    _Bool _mBtLinkIsRecommended;	// 143 = 0x8f
    _Bool _mCompanionWifiLinkIsRecommended;	// 144 = 0x90
    _Bool _mDirectWifiLinkIsRecommended;	// 145 = 0x91
    _Bool _isGizmoNearbyOverBt;	// 146 = 0x92
    BOOL _nwType;	// 147 = 0x93
    int _mAppLinkPreference;	// 148 = 0x94
    int _mCurrentActiveLink;	// 152 = 0x98
    int _beaconPER;	// 156 = 0x9c
    unsigned long long _btMovingAvgRSSI;	// 160 = 0xa0
    long long _wifiRSSI;	// 168 = 0xa8
    long long _wifiSNR;	// 176 = 0xb0
    long long _wifiCCA;	// 184 = 0xb8
    long long _lsmRecommendationBe;	// 192 = 0xc0
    long long _expectedThroughputVIBE;	// 200 = 0xc8
    long long _packetLifetimeVIBE;	// 208 = 0xd0
    long long _packetLossRateVIBE;	// 216 = 0xd8
    long long _btRetransmissionRateTx;	// 224 = 0xe0
    long long _btRetransmissionRateRx;	// 232 = 0xe8
    long long _btTech;	// 240 = 0xf0
}

@property(nonatomic) long long btTech; // @synthesize btTech=_btTech;
@property(nonatomic) long long btRetransmissionRateRx; // @synthesize btRetransmissionRateRx=_btRetransmissionRateRx;
@property(nonatomic) long long btRetransmissionRateTx; // @synthesize btRetransmissionRateTx=_btRetransmissionRateTx;
@property(nonatomic) long long packetLossRateVIBE; // @synthesize packetLossRateVIBE=_packetLossRateVIBE;
@property(nonatomic) long long packetLifetimeVIBE; // @synthesize packetLifetimeVIBE=_packetLifetimeVIBE;
@property(nonatomic) long long expectedThroughputVIBE; // @synthesize expectedThroughputVIBE=_expectedThroughputVIBE;
@property(nonatomic) long long lsmRecommendationBe; // @synthesize lsmRecommendationBe=_lsmRecommendationBe;
@property(nonatomic) long long wifiCCA; // @synthesize wifiCCA=_wifiCCA;
@property(nonatomic) BOOL nwType; // @synthesize nwType=_nwType;
@property(nonatomic) int beaconPER; // @synthesize beaconPER=_beaconPER;
@property(nonatomic) long long wifiSNR; // @synthesize wifiSNR=_wifiSNR;
@property(nonatomic) long long wifiRSSI; // @synthesize wifiRSSI=_wifiRSSI;
@property(nonatomic) unsigned long long btMovingAvgRSSI; // @synthesize btMovingAvgRSSI=_btMovingAvgRSSI;
@property(nonatomic) _Bool isGizmoNearbyOverBt; // @synthesize isGizmoNearbyOverBt=_isGizmoNearbyOverBt;
@property(nonatomic) _Bool mDirectWifiLinkIsRecommended; // @synthesize mDirectWifiLinkIsRecommended=_mDirectWifiLinkIsRecommended;
@property(nonatomic) _Bool mCompanionWifiLinkIsRecommended; // @synthesize mCompanionWifiLinkIsRecommended=_mCompanionWifiLinkIsRecommended;
@property(nonatomic) _Bool mBtLinkIsRecommended; // @synthesize mBtLinkIsRecommended=_mBtLinkIsRecommended;
@property(nonatomic) _Bool mDirectWifiLinkRecommendationUpdateNeeded; // @synthesize mDirectWifiLinkRecommendationUpdateNeeded=_mDirectWifiLinkRecommendationUpdateNeeded;
@property(nonatomic) _Bool mCompanionWifiLinkRecommendationUpdateNeeded; // @synthesize mCompanionWifiLinkRecommendationUpdateNeeded=_mCompanionWifiLinkRecommendationUpdateNeeded;
@property(nonatomic) _Bool mBtLinkRecommendationUpdateNeeded; // @synthesize mBtLinkRecommendationUpdateNeeded=_mBtLinkRecommendationUpdateNeeded;
@property(nonatomic) _Bool mIsRetry; // @synthesize mIsRetry=_mIsRetry;
@property(nonatomic) _Bool mClientSubscriptionValid; // @synthesize mClientSubscriptionValid=_mClientSubscriptionValid;
@property(nonatomic) _Bool mForceUpdateNeeded; // @synthesize mForceUpdateNeeded=_mForceUpdateNeeded;
@property(nonatomic) _Bool mTerminusIsRegistered; // @synthesize mTerminusIsRegistered=_mTerminusIsRegistered;
@property(nonatomic) int mCurrentActiveLink; // @synthesize mCurrentActiveLink=_mCurrentActiveLink;
@property(nonatomic) int mAppLinkPreference; // @synthesize mAppLinkPreference=_mAppLinkPreference;
- (void)dealloc;	// IMP=0x00000001000685cc
- (id)init;	// IMP=0x00000001000682c8

@end

