//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "BFFFlowItem-Protocol.h"
#import "VTUIEnrollTrainingViewControllerDelegate-Protocol.h"

@class NSString, VTUIEnrollTrainingViewController;
@protocol BFFFlowItemDelegate;

@interface AssistantOptInController : NSObject <VTUIEnrollTrainingViewControllerDelegate, BFFFlowItem>
{
    _Bool _didOfferVoiceTrigger;	// 8 = 0x8
    id <BFFFlowItemDelegate> _delegate;	// 16 = 0x10
    VTUIEnrollTrainingViewController *_enrollmentController;	// 24 = 0x18
}

+ (void)_enableAssistantLocation;	// IMP=0x000000010005d494
+ (void)setAssistantEnabled:(_Bool)arg1;	// IMP=0x000000010005d3f0
+ (void)skippedByCloudConfig;	// IMP=0x000000010005c548
+ (id)cloudConfigSkipKey;	// IMP=0x000000010005c538
- (void).cxx_destruct;	// IMP=0x000000010005db18
@property(nonatomic) _Bool didOfferVoiceTrigger; // @synthesize didOfferVoiceTrigger=_didOfferVoiceTrigger;
@property(retain, nonatomic) VTUIEnrollTrainingViewController *enrollmentController; // @synthesize enrollmentController=_enrollmentController;
@property(nonatomic) __weak id <BFFFlowItemDelegate> delegate; // @synthesize delegate=_delegate;
- (void)showLearnMore;	// IMP=0x000000010005da64
- (void)skipSetup;	// IMP=0x000000010005d83c
- (void)continueSetup;	// IMP=0x000000010005d4f8
- (void)_removeSiriPanesFromNavHierarchy;	// IMP=0x000000010005d224
- (_Bool)controllerAllowsNavigatingBack;	// IMP=0x000000010005d21c
- (id)viewController;	// IMP=0x000000010005d0bc
- (void)controllerWasPopped;	// IMP=0x000000010005d068
- (void)performExtendedInitializationWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010005c678

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

