//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSMutableArray, NSString, UITableView;

@interface BuddyMultilingualContentAdditionController : UIViewController <UITableViewDelegate, UITableViewDataSource>
{
    NSMutableArray *_dataStore;	// 8 = 0x8
    UITableView *_tableView;	// 16 = 0x10
    CDUnknownBlockType _selectionCallBack;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00000001000d5448
@property(copy, nonatomic) CDUnknownBlockType selectionCallBack; // @synthesize selectionCallBack=_selectionCallBack;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) NSMutableArray *dataStore; // @synthesize dataStore=_dataStore;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;	// IMP=0x00000001000d5278
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x00000001000d5098
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;	// IMP=0x00000001000d504c
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x00000001000d4fdc
- (id)initWithChoseableDataStore:(id)arg1 selectionCallback:(CDUnknownBlockType)arg2;	// IMP=0x00000001000d4ddc

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

