//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface BuddyMenuController : NSObject
{
    NSArray *_consumers;	// 8 = 0x8
}

+ (id)menuButtonConsumerWithHandler:(CDUnknownBlockType)arg1;	// IMP=0x00000001000a1c7c
+ (_Bool)_useSideButton;	// IMP=0x00000001000a1c28
+ (_Bool)supportsHomeGesture;	// IMP=0x00000001000a1c1c
- (void).cxx_destruct;	// IMP=0x00000001000a1fcc
- (_Bool)includeShutDown;	// IMP=0x00000001000a1fb0
- (void)dealloc;	// IMP=0x00000001000a1f64
- (void)invalidate;	// IMP=0x00000001000a1e14
- (id)initWithHandler:(CDUnknownBlockType)arg1;	// IMP=0x00000001000a1cd0

@end

