//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "BFFPasscodeInputViewDelegate-Protocol.h"

@class DevicePINController, NSString, NSTimer, UILabel;
@protocol BuddyPasscodeEntryDelegate;

@interface BuddyPasscodeEntryController : UIViewController <BFFPasscodeInputViewDelegate>
{
    DevicePINController *_pinController;	// 8 = 0x8
    UILabel *_statusLabel;	// 16 = 0x10
    NSTimer *_statusTimer;	// 24 = 0x18
    _Bool _numeric;	// 32 = 0x20
    unsigned long long _numericLength;	// 40 = 0x28
    id <BuddyPasscodeEntryDelegate> _delegate;	// 48 = 0x30
    NSString *_titleText;	// 56 = 0x38
    NSString *_instructions;	// 64 = 0x40
}

- (void).cxx_destruct;	// IMP=0x0000000100014720
@property(copy, nonatomic) NSString *instructions; // @synthesize instructions=_instructions;
@property(copy, nonatomic) NSString *titleText; // @synthesize titleText=_titleText;
@property(nonatomic) __weak id <BuddyPasscodeEntryDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) unsigned long long numericLength; // @synthesize numericLength=_numericLength;
@property(nonatomic, getter=isNumeric) _Bool numeric; // @synthesize numeric=_numeric;
- (void)configurePasscodeTypeUsingAnimations:(_Bool)arg1;	// IMP=0x000000010001452c
- (void)clear;	// IMP=0x00000001000144c4
- (void)passcodeInput:(id)arg1 enteredPasscode:(id)arg2;	// IMP=0x00000001000143b8
- (void)passcodeInput:(id)arg1 willChangeContents:(id)arg2;	// IMP=0x0000000100014310
- (void)updateStatusMessage;	// IMP=0x0000000100013f44
- (void)nextButtonPressed;	// IMP=0x0000000100013eac
- (void)_finishedWithPasscode:(id)arg1;	// IMP=0x0000000100013e04
- (void)viewDidLayoutSubviews;	// IMP=0x0000000100013b98
- (void)viewDidDisappear:(_Bool)arg1;	// IMP=0x0000000100013b48
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x0000000100013ab4
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0000000100013974
- (void)viewDidLoad;	// IMP=0x0000000100013910
- (void)_setupFirstEntry;	// IMP=0x0000000100013684
- (_Bool)usesSimplePasscodeEntry;	// IMP=0x0000000100013620
- (id)passcodeView;	// IMP=0x00000001000135e4
- (void)dealloc;	// IMP=0x0000000100013554
- (void)loadView;	// IMP=0x00000001000132d4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

