//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface BuddyRestoreHelpers : NSObject
{
}

+ (id)alertForBackupError:(id)arg1 forBackup:(_Bool)arg2 okButtonAction:(CDUnknownBlockType)arg3;	// IMP=0x00000001000dfc7c
+ (id)alertForBackupError:(id)arg1 okButtonAction:(CDUnknownBlockType)arg2;	// IMP=0x00000001000dfbfc

@end

