//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "BuddyWelcomeController.h"

#import "BYEnvironmentDependencyReceiver-Protocol.h"
#import "BuddyPosedDeviceSelectionDelegate-Protocol.h"

@class BuddyInternalSkipInfoProvider, BuddyPosedDeviceSelectionView, DBSDeviceDisplayZoomAnimationView, NSString;
@protocol BYDeviceProvider;

@interface BuddyMagnifyController : BuddyWelcomeController <BuddyPosedDeviceSelectionDelegate, BYEnvironmentDependencyReceiver>
{
    id <BYDeviceProvider> _deviceProvider;	// 8 = 0x8
    BuddyPosedDeviceSelectionView *_composed;	// 16 = 0x10
    DBSDeviceDisplayZoomAnimationView *_standardAnimatedZoomView;	// 24 = 0x18
    DBSDeviceDisplayZoomAnimationView *_zoomedAnimatedZoomView;	// 32 = 0x20
}

+ (id)cloudConfigSkipKey;	// IMP=0x0000000100042d70
+ (_Bool)controllerNeedsToRun;	// IMP=0x0000000100042b84
+ (_Bool)commitMagnifyModeIfNeeded;	// IMP=0x00000001000427d8
- (void).cxx_destruct;	// IMP=0x0000000100042e10
@property(retain, nonatomic) DBSDeviceDisplayZoomAnimationView *zoomedAnimatedZoomView; // @synthesize zoomedAnimatedZoomView=_zoomedAnimatedZoomView;
@property(retain, nonatomic) DBSDeviceDisplayZoomAnimationView *standardAnimatedZoomView; // @synthesize standardAnimatedZoomView=_standardAnimatedZoomView;
@property(retain, nonatomic) BuddyPosedDeviceSelectionView *composed; // @synthesize composed=_composed;
@property(retain, nonatomic) id <BYDeviceProvider> deviceProvider; // @synthesize deviceProvider=_deviceProvider;
- (void)performExtendedInitializationWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0000000100042c94
- (void)didSelectSegment:(long long)arg1;	// IMP=0x0000000100042b70
- (void)_controllerDone;	// IMP=0x0000000100042b28
- (void)_showMagnifyControllerWithZoomedSelected:(_Bool)arg1;	// IMP=0x0000000100042a74
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x0000000100042730
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x0000000100042688
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0000000100042608
- (void)loadView;	// IMP=0x0000000100041ef8
- (id)init;	// IMP=0x0000000100041bc0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) BuddyInternalSkipInfoProvider *internalSkipInfoProvider;
@property(readonly) Class superclass;

@end

