//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SetupAssistantUI/BFFMigrationTimeRemainingController.h>

#import "BYDeviceMigrationDelegate-Protocol.h"

@class NSString;

@interface BuddyMigrationLockscreenProgressController : BFFMigrationTimeRemainingController <BYDeviceMigrationDelegate>
{
    NSString *_titleText;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00000001000fa280
@property(retain, nonatomic) NSString *titleText; // @synthesize titleText=_titleText;
- (void)deviceMigrationManager:(id)arg1 didCompleteWithError:(id)arg2;	// IMP=0x00000001000fa258
- (void)deviceMigrationManager:(id)arg1 didUpdateProgress:(id)arg2;	// IMP=0x00000001000fa1c0
- (void)deviceMigrationManager:(id)arg1 didChangeConnectionInformation:(id)arg2;	// IMP=0x00000001000f9fdc
- (void)setTitle:(id)arg1;	// IMP=0x00000001000f9f60
- (void)loadView;	// IMP=0x00000001000f9e78
- (_Bool)_canShowWhileLocked;	// IMP=0x00000001000f9e70

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

