//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface BuddyMigrationCapability : NSObject
{
}

+ (long long)_compareProductVersion:(id)arg1 toProductVersion:(id)arg2;	// IMP=0x00000001000515b8
+ (_Bool)_supportsMigrationFromProductVersion:(id)arg1 toProductVersion:(id)arg2;	// IMP=0x0000000100051558
+ (id)_allowedDeviceClasses;	// IMP=0x000000010005154c
+ (_Bool)_currentHardwareSupportsMigration;	// IMP=0x00000001000514d0
+ (_Bool)sourceDeviceSupportsMigration:(id)arg1 productVersion:(id)arg2 deviceClass:(id)arg3 softwareUpdateRequired:(_Bool *)arg4 reason:(id *)arg5;	// IMP=0x000000010005101c
+ (_Bool)currentDeviceShouldOfferMigration;	// IMP=0x0000000100050df4

@end

