//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIActivityIndicatorView;

@interface SpinnerTableCell : UITableViewCell
{
    UIActivityIndicatorView *_spinner;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x000000010003838c
- (void)layoutSubviews;	// IMP=0x00000001000382b8
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;	// IMP=0x00000001000381f0

@end

