/*
* This header is generated by classdump-dyld 1.0
* on Sunday, September 27, 2020 at 11:41:33 AM Mountain Standard Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /usr/lib/libobjc.A.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol CARenderValue <NSObject>
@optional
-(void)CA_prepareRenderValue;
-(Object*)CA_copyRenderValue;
-(unsigned long long)CA_copyNumericValue:(double)arg1;

@end

