//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "DMDConfigurationSourceTaskOperation.h"

@protocol DMDRemoteAssetResolutionContext;

@interface DMDConfigurationSourceAssetResolveOperation : DMDConfigurationSourceTaskOperation
{
    id <DMDRemoteAssetResolutionContext> _context;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0000000100037300
@property(retain, nonatomic) id <DMDRemoteAssetResolutionContext> context; // @synthesize context=_context;
- (void)main;	// IMP=0x0000000100036f44
- (_Bool)isAsynchronous;	// IMP=0x0000000100036f3c

@end

