//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "DMDTaskOperation.h"

@interface DMDFetchConfigurationSourceSyncTokenOperation : DMDTaskOperation
{
}

+ (_Bool)validateRequest:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100051124
+ (id)requiredEntitlements;	// IMP=0x00000001000510c4
+ (id)whitelistedClassesForRequest;	// IMP=0x0000000100051088
- (void)runWithRequest:(id)arg1;	// IMP=0x00000001000510e0
- (unsigned long long)queueGroup;	// IMP=0x00000001000510d8
- (_Bool)runOnMainThread;	// IMP=0x00000001000510d0

@end

