//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "DMDAppOperation.h"

@interface DMDSetAppAssociatedDomainsOperation : DMDAppOperation
{
}

+ (id)requiredEntitlements;	// IMP=0x0000000100075800
+ (id)whitelistedClassesForRequest;	// IMP=0x00000001000757c4
- (void)runWithRequest:(id)arg1 bundleIdentifier:(id)arg2;	// IMP=0x000000010007580c

@end

