/*
* This header is generated by classdump-dyld 1.0
* on Sunday, September 27, 2020 at 11:52:46 AM Mountain Standard Time
* Operating System: Version 14.0 (Build 18A373)
* Image Source: /usr/lib/libBKDM1.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libBKDM1.dylib/MesaCoreAnalyticsEvent.h>

@class NSNumber, BiometricMatchOperationMesa;

@interface MesaCoreAnalyticsMatchEvent : MesaCoreAnalyticsEvent {

	BOOL _valid;
	BOOL _waitingForMatchResult;
	unsigned char _lastAcceptCondFeedback;
	NSNumber* _matcherResult;
	NSNumber* _matchMode;
	NSNumber* _matchUseCase;
	NSNumber* _matchType;
	NSNumber* _tidButtonState;
	NSNumber* _imageProblemClass;
	NSNumber* _deviceWakeReason;
	NSNumber* _sensorModulationRatio;
	NSNumber* _imagePixelOutlierCount;
	NSNumber* _imageContrast;
	NSNumber* _imageBrightness;
	NSNumber* _imageFeatureStrength;
	NSNumber* _imageContrastNorm;
	NSNumber* _imageBrightnessNorm;
	NSNumber* _imageFeatureStrengthNorm;
	NSNumber* _sensorRecoveryReason;
	NSNumber* _drxStrengthPctCol2Bin;
	NSNumber* _drxStrengthPctCol7Bin;
	NSNumber* _temperatureBin;
	NSNumber* _maxFingerToProbeAttenuationBin;
	NSNumber* _overallResult;
	NSNumber* _wakeOnMenuPinUsed;
	NSNumber* _templateUpdated;
	NSNumber* _dirtOnSensor;
	NSNumber* _pressureMitigationUsed;
	NSNumber* _desenseMitigationPause;
	NSNumber* _bioLockout;
	NSNumber* _requestFingerOff;
	NSNumber* _preArmedMatch;
	NSNumber* _captureRestartCount;
	NSNumber* _capturedImageCount;
	NSNumber* _acceptedImageCount;
	NSNumber* _rejectedImageCount;
	NSNumber* _rejectedImageUnknownCount;
	NSNumber* _rejectedImageBadBlocksCount;
	NSNumber* _rejectedImageChFPNCount;
	NSNumber* _rejectedImageCaFPNCount;
	NSNumber* _rejectedImageMovementCount;
	NSNumber* _enrolledUsersCount;
	NSNumber* _matchIdentityCount;
	NSNumber* _failedUnlockAttempts;
	NSNumber* _failedMatchAttempts;
	NSNumber* _quickTapsCount;
	NSNumber* _sensorResetCount;
	NSNumber* _overallTime;
	NSNumber* _operationStartTime;
	NSNumber* _fingerDetectEndTime;
	NSNumber* _firstCaptureEndTime;
	NSNumber* _imageProcessingEndTime;
	NSNumber* _matcherEndTime;
	NSNumber* _captureTime;
	NSNumber* _imageProcessingTime;
	NSNumber* _matcherTime;
	NSNumber* _timeSinceSleep;
	NSNumber* _requestFingerOffEndTime;
	NSNumber* _overallTimeFingerOn;
	BiometricMatchOperationMesa* _matchOperation;
	NSNumber* _imageAbsoluteTimeId;
	NSNumber* _FMRBin;
	NSNumber* _BSRBin;
	NSNumber* _fitDiffBin;
	NSNumber* _carrierAttenBin;
	NSNumber* _DRXAmpMinBin;
	NSNumber* _DRXAmpMaxBin;
	NSNumber* _fitResEdge6SigmaBin;
	NSNumber* _maxFingerToProbeAttenuation;

}

@property (retain) NSNumber * matcherResult;                                  //@synthesize matcherResult=_matcherResult - In the implementation block
@property (retain) NSNumber * matchMode;                                      //@synthesize matchMode=_matchMode - In the implementation block
@property (retain) NSNumber * matchUseCase;                                   //@synthesize matchUseCase=_matchUseCase - In the implementation block
@property (retain) NSNumber * matchType;                                      //@synthesize matchType=_matchType - In the implementation block
@property (retain) NSNumber * tidButtonState;                                 //@synthesize tidButtonState=_tidButtonState - In the implementation block
@property (retain) NSNumber * imageProblemClass;                              //@synthesize imageProblemClass=_imageProblemClass - In the implementation block
@property (retain) NSNumber * deviceWakeReason;                               //@synthesize deviceWakeReason=_deviceWakeReason - In the implementation block
@property (retain) NSNumber * sensorModulationRatio;                          //@synthesize sensorModulationRatio=_sensorModulationRatio - In the implementation block
@property (retain) NSNumber * imagePixelOutlierCount;                         //@synthesize imagePixelOutlierCount=_imagePixelOutlierCount - In the implementation block
@property (retain) NSNumber * imageContrast;                                  //@synthesize imageContrast=_imageContrast - In the implementation block
@property (retain) NSNumber * imageBrightness;                                //@synthesize imageBrightness=_imageBrightness - In the implementation block
@property (retain) NSNumber * imageFeatureStrength;                           //@synthesize imageFeatureStrength=_imageFeatureStrength - In the implementation block
@property (retain) NSNumber * imageContrastNorm;                              //@synthesize imageContrastNorm=_imageContrastNorm - In the implementation block
@property (retain) NSNumber * imageBrightnessNorm;                            //@synthesize imageBrightnessNorm=_imageBrightnessNorm - In the implementation block
@property (retain) NSNumber * imageFeatureStrengthNorm;                       //@synthesize imageFeatureStrengthNorm=_imageFeatureStrengthNorm - In the implementation block
@property (nonatomic,retain) NSNumber * sensorRecoveryReason;                 //@synthesize sensorRecoveryReason=_sensorRecoveryReason - In the implementation block
@property (retain) NSNumber * drxStrengthPctCol2Bin;                          //@synthesize drxStrengthPctCol2Bin=_drxStrengthPctCol2Bin - In the implementation block
@property (retain) NSNumber * drxStrengthPctCol7Bin;                          //@synthesize drxStrengthPctCol7Bin=_drxStrengthPctCol7Bin - In the implementation block
@property (retain) NSNumber * temperatureBin;                                 //@synthesize temperatureBin=_temperatureBin - In the implementation block
@property (retain) NSNumber * maxFingerToProbeAttenuationBin;                 //@synthesize maxFingerToProbeAttenuationBin=_maxFingerToProbeAttenuationBin - In the implementation block
@property (retain) NSNumber * overallResult;                                  //@synthesize overallResult=_overallResult - In the implementation block
@property (retain) NSNumber * wakeOnMenuPinUsed;                              //@synthesize wakeOnMenuPinUsed=_wakeOnMenuPinUsed - In the implementation block
@property (retain) NSNumber * templateUpdated;                                //@synthesize templateUpdated=_templateUpdated - In the implementation block
@property (retain) NSNumber * dirtOnSensor;                                   //@synthesize dirtOnSensor=_dirtOnSensor - In the implementation block
@property (retain) NSNumber * pressureMitigationUsed;                         //@synthesize pressureMitigationUsed=_pressureMitigationUsed - In the implementation block
@property (retain) NSNumber * desenseMitigationPause;                         //@synthesize desenseMitigationPause=_desenseMitigationPause - In the implementation block
@property (retain) NSNumber * bioLockout;                                     //@synthesize bioLockout=_bioLockout - In the implementation block
@property (retain) NSNumber * requestFingerOff;                               //@synthesize requestFingerOff=_requestFingerOff - In the implementation block
@property (retain) NSNumber * preArmedMatch;                                  //@synthesize preArmedMatch=_preArmedMatch - In the implementation block
@property (retain) NSNumber * captureRestartCount;                            //@synthesize captureRestartCount=_captureRestartCount - In the implementation block
@property (retain) NSNumber * capturedImageCount;                             //@synthesize capturedImageCount=_capturedImageCount - In the implementation block
@property (retain) NSNumber * acceptedImageCount;                             //@synthesize acceptedImageCount=_acceptedImageCount - In the implementation block
@property (retain) NSNumber * rejectedImageCount;                             //@synthesize rejectedImageCount=_rejectedImageCount - In the implementation block
@property (retain) NSNumber * rejectedImageUnknownCount;                      //@synthesize rejectedImageUnknownCount=_rejectedImageUnknownCount - In the implementation block
@property (retain) NSNumber * rejectedImageBadBlocksCount;                    //@synthesize rejectedImageBadBlocksCount=_rejectedImageBadBlocksCount - In the implementation block
@property (retain) NSNumber * rejectedImageChFPNCount;                        //@synthesize rejectedImageChFPNCount=_rejectedImageChFPNCount - In the implementation block
@property (retain) NSNumber * rejectedImageCaFPNCount;                        //@synthesize rejectedImageCaFPNCount=_rejectedImageCaFPNCount - In the implementation block
@property (retain) NSNumber * rejectedImageMovementCount;                     //@synthesize rejectedImageMovementCount=_rejectedImageMovementCount - In the implementation block
@property (retain) NSNumber * enrolledUsersCount;                             //@synthesize enrolledUsersCount=_enrolledUsersCount - In the implementation block
@property (retain) NSNumber * matchIdentityCount;                             //@synthesize matchIdentityCount=_matchIdentityCount - In the implementation block
@property (retain) NSNumber * failedUnlockAttempts;                           //@synthesize failedUnlockAttempts=_failedUnlockAttempts - In the implementation block
@property (retain) NSNumber * failedMatchAttempts;                            //@synthesize failedMatchAttempts=_failedMatchAttempts - In the implementation block
@property (retain) NSNumber * quickTapsCount;                                 //@synthesize quickTapsCount=_quickTapsCount - In the implementation block
@property (retain) NSNumber * sensorResetCount;                               //@synthesize sensorResetCount=_sensorResetCount - In the implementation block
@property (retain) NSNumber * overallTime;                                    //@synthesize overallTime=_overallTime - In the implementation block
@property (retain) NSNumber * operationStartTime;                             //@synthesize operationStartTime=_operationStartTime - In the implementation block
@property (retain) NSNumber * fingerDetectEndTime;                            //@synthesize fingerDetectEndTime=_fingerDetectEndTime - In the implementation block
@property (retain) NSNumber * firstCaptureEndTime;                            //@synthesize firstCaptureEndTime=_firstCaptureEndTime - In the implementation block
@property (retain) NSNumber * imageProcessingEndTime;                         //@synthesize imageProcessingEndTime=_imageProcessingEndTime - In the implementation block
@property (retain) NSNumber * matcherEndTime;                                 //@synthesize matcherEndTime=_matcherEndTime - In the implementation block
@property (retain) NSNumber * captureTime;                                    //@synthesize captureTime=_captureTime - In the implementation block
@property (retain) NSNumber * imageProcessingTime;                            //@synthesize imageProcessingTime=_imageProcessingTime - In the implementation block
@property (retain) NSNumber * matcherTime;                                    //@synthesize matcherTime=_matcherTime - In the implementation block
@property (retain) NSNumber * timeSinceSleep;                                 //@synthesize timeSinceSleep=_timeSinceSleep - In the implementation block
@property (retain) NSNumber * requestFingerOffEndTime;                        //@synthesize requestFingerOffEndTime=_requestFingerOffEndTime - In the implementation block
@property (retain) NSNumber * overallTimeFingerOn;                            //@synthesize overallTimeFingerOn=_overallTimeFingerOn - In the implementation block
@property (retain) BiometricMatchOperationMesa * matchOperation;              //@synthesize matchOperation=_matchOperation - In the implementation block
@property (retain) NSNumber * imageAbsoluteTimeId;                            //@synthesize imageAbsoluteTimeId=_imageAbsoluteTimeId - In the implementation block
@property (retain) NSNumber * FMRBin;                                         //@synthesize FMRBin=_FMRBin - In the implementation block
@property (retain) NSNumber * BSRBin;                                         //@synthesize BSRBin=_BSRBin - In the implementation block
@property (retain) NSNumber * fitDiffBin;                                     //@synthesize fitDiffBin=_fitDiffBin - In the implementation block
@property (retain) NSNumber * carrierAttenBin;                                //@synthesize carrierAttenBin=_carrierAttenBin - In the implementation block
@property (retain) NSNumber * DRXAmpMinBin;                                   //@synthesize DRXAmpMinBin=_DRXAmpMinBin - In the implementation block
@property (retain) NSNumber * DRXAmpMaxBin;                                   //@synthesize DRXAmpMaxBin=_DRXAmpMaxBin - In the implementation block
@property (retain) NSNumber * fitResEdge6SigmaBin;                            //@synthesize fitResEdge6SigmaBin=_fitResEdge6SigmaBin - In the implementation block
@property (retain) NSNumber * maxFingerToProbeAttenuation;                    //@synthesize maxFingerToProbeAttenuation=_maxFingerToProbeAttenuation - In the implementation block
-(void)setFailedUnlockAttempts:(NSNumber *)arg1 ;
-(NSNumber *)failedUnlockAttempts;
-(NSNumber *)BSRBin;
-(void)setQuickTapsCount:(NSNumber *)arg1 ;
-(NSNumber *)matcherResult;
-(NSNumber *)matchType;
-(void)setImageFeatureStrengthNorm:(NSNumber *)arg1 ;
-(void)setOverallTime:(NSNumber *)arg1 ;
-(NSNumber *)overallResult;
-(void)setImageBrightness:(NSNumber *)arg1 ;
-(void)setMaxFingerToProbeAttenuationBin:(NSNumber *)arg1 ;
-(void)setOverallResult:(NSNumber *)arg1 ;
-(NSNumber *)templateUpdated;
-(void)setMatchMode:(NSNumber *)arg1 ;
-(void)setFitDiffBin:(NSNumber *)arg1 ;
-(NSNumber *)dirtOnSensor;
-(NSNumber *)rejectedImageBadBlocksCount;
-(void)setImagePixelOutlierCount:(NSNumber *)arg1 ;
-(void)acceptPreviousImage;
-(void)setImageProblemClass:(NSNumber *)arg1 ;
-(void)setEnrolledUsersCount:(NSNumber *)arg1 ;
-(NSNumber *)pressureMitigationUsed;
-(NSNumber *)imageBrightness;
-(NSNumber *)fingerDetectEndTime;
-(void)setDrxStrengthPctCol2Bin:(NSNumber *)arg1 ;
-(NSNumber *)matchUseCase;
-(BiometricMatchOperationMesa *)matchOperation;
-(NSNumber *)enrolledUsersCount;
-(NSNumber *)overallTime;
-(NSNumber *)captureRestartCount;
-(void)setImageProcessingTime:(NSNumber *)arg1 ;
-(NSNumber *)acceptedImageCount;
-(void)setEventCanceled:(id)arg1 ;
-(void)setPressureMitigationUsed:(NSNumber *)arg1 ;
-(void)handleStatusMessage:(unsigned)arg1 withData:(id)arg2 ;
-(void)setBioLockout:(NSNumber *)arg1 ;
-(NSNumber *)imageProblemClass;
-(NSNumber *)drxStrengthPctCol7Bin;
-(void)setTimeSinceSleep:(NSNumber *)arg1 ;
-(NSNumber *)rejectedImageMovementCount;
-(void)setMatcherResult:(NSNumber *)arg1 ;
-(void)setMatchResult:(id)arg1 withDetails:(id)arg2 ;
-(NSNumber *)maxFingerToProbeAttenuationBin;
-(void)setCapturedImageCount:(NSNumber *)arg1 ;
-(NSNumber *)failedMatchAttempts;
-(void)setMatchUseCase:(NSNumber *)arg1 ;
-(NSNumber *)capturedImageCount;
-(void)setTidButtonState:(NSNumber *)arg1 ;
-(void)setMatchIdentityCount:(NSNumber *)arg1 ;
-(void)setWakeOnMenuPinUsed:(NSNumber *)arg1 ;
-(NSNumber *)imagePixelOutlierCount;
-(void)setRejectedImageChFPNCount:(NSNumber *)arg1 ;
-(void)setSensorModulationRatio:(NSNumber *)arg1 ;
-(void)reset;
-(void)setMatcherEndTime:(NSNumber *)arg1 ;
-(void)setDRXAmpMaxBin:(NSNumber *)arg1 ;
-(void)setRequestFingerOffEndTime:(NSNumber *)arg1 ;
-(void)setImageContrastNorm:(NSNumber *)arg1 ;
-(void)setFailedMatchAttempts:(NSNumber *)arg1 ;
-(void)setRejectedImageBadBlocksCount:(NSNumber *)arg1 ;
-(NSNumber *)fitResEdge6SigmaBin;
-(NSNumber *)imageProcessingEndTime;
-(NSNumber *)maxFingerToProbeAttenuation;
-(void)setCaptureTime:(NSNumber *)arg1 ;
-(NSNumber *)DRXAmpMaxBin;
-(BOOL)postEventAndUpdateDailyValues:(id)arg1 ;
-(NSNumber *)operationStartTime;
-(NSNumber *)imageFeatureStrength;
-(void)setDeviceWakeReason:(NSNumber *)arg1 ;
-(NSNumber *)desenseMitigationPause;
-(NSNumber *)requestFingerOff;
-(void)setAcceptedImageCount:(NSNumber *)arg1 ;
-(void)setImageFeatureStrength:(NSNumber *)arg1 ;
-(void)setFirstCaptureEndTime:(NSNumber *)arg1 ;
-(id)init;
-(NSNumber *)imageBrightnessNorm;
-(NSNumber *)imageProcessingTime;
-(void)setMatchModeWith:(long long)arg1 ;
-(NSNumber *)matchMode;
-(NSNumber *)bioLockout;
-(NSNumber *)captureTime;
-(NSNumber *)rejectedImageUnknownCount;
-(void)setImageContrast:(NSNumber *)arg1 ;
-(void)setFMRBin:(NSNumber *)arg1 ;
-(void)updateDailyValuesAfterMatch:(id)arg1 ;
-(NSNumber *)rejectedImageChFPNCount;
-(void)setCarrierAttenBin:(NSNumber *)arg1 ;
-(void)setMatchOperation:(BiometricMatchOperationMesa *)arg1 ;
-(void)setRejectedImageUnknownCount:(NSNumber *)arg1 ;
-(void)setDesenseMitigationPause:(NSNumber *)arg1 ;
-(NSNumber *)FMRBin;
-(void)setDrxStrengthPctCol7Bin:(NSNumber *)arg1 ;
-(void)setTemperatureBin:(NSNumber *)arg1 ;
-(NSNumber *)overallTimeFingerOn;
-(void)setFitResEdge6SigmaBin:(NSNumber *)arg1 ;
-(void)setTemplateUpdated:(NSNumber *)arg1 ;
-(NSNumber *)imageContrastNorm;
-(NSNumber *)timeSinceSleep;
-(void)setRejectedImageCount:(NSNumber *)arg1 ;
-(void)setSensorResetCount:(NSNumber *)arg1 ;
-(void)setMaxFingerToProbeAttenuation:(NSNumber *)arg1 ;
-(NSNumber *)imageFeatureStrengthNorm;
-(NSNumber *)sensorRecoveryReason;
-(void)setOverallTimeFingerOn:(NSNumber *)arg1 ;
-(void)setDirtOnSensor:(NSNumber *)arg1 ;
-(void)setImageBrightnessNorm:(NSNumber *)arg1 ;
-(void)setImageProcessingEndTime:(NSNumber *)arg1 ;
-(NSNumber *)rejectedImageCount;
-(NSNumber *)tidButtonState;
-(void)setDRXAmpMinBin:(NSNumber *)arg1 ;
-(void)setImageAbsoluteTimeId:(NSNumber *)arg1 ;
-(NSNumber *)carrierAttenBin;
-(NSNumber *)deviceWakeReason;
-(NSNumber *)temperatureBin;
-(NSNumber *)quickTapsCount;
-(NSNumber *)matchIdentityCount;
-(void)setCaptureRestartCount:(NSNumber *)arg1 ;
-(NSNumber *)matcherEndTime;
-(void)setFingerDetectEndTime:(NSNumber *)arg1 ;
-(void)setRejectedImageMovementCount:(NSNumber *)arg1 ;
-(NSNumber *)requestFingerOffEndTime;
-(id)initWithDictionary:(id)arg1 ;
-(void)setBSRBin:(NSNumber *)arg1 ;
-(NSNumber *)imageAbsoluteTimeId;
-(NSNumber *)wakeOnMenuPinUsed;
-(NSNumber *)DRXAmpMinBin;
-(NSNumber *)matcherTime;
-(void)setSensorRecoveryReason:(NSNumber *)arg1 ;
-(void)setRejectedImageCaFPNCount:(NSNumber *)arg1 ;
-(NSNumber *)fitDiffBin;
-(NSNumber *)drxStrengthPctCol2Bin;
-(void)setPreArmedMatch:(NSNumber *)arg1 ;
-(void)setRequestFingerOff:(NSNumber *)arg1 ;
-(NSNumber *)imageContrast;
-(NSNumber *)firstCaptureEndTime;
-(void)setOperationStartTime:(NSNumber *)arg1 ;
-(NSNumber *)sensorModulationRatio;
-(void)setMatcherTime:(NSNumber *)arg1 ;
-(void)setMatchTypeWith:(id)arg1 ;
-(NSNumber *)sensorResetCount;
-(NSNumber *)rejectedImageCaFPNCount;
-(void)setMatchType:(NSNumber *)arg1 ;
-(NSNumber *)preArmedMatch;
@end

