//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSExtension.h>

@interface NSExtension (RPExtensions)
+ (void)extensionsWithMatchingPointName:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010001d3d8
+ (void)extensionsWithMatchingPointName:(id)arg1 unwantedActivationRule:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x000000010001d364
+ (void)extensionsWithMatchingPointName:(id)arg1 activationRule:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x000000010001d2f0
+ (void)extensionsWithMatchingPointName:(id)arg1 baseIdentifier:(id)arg2 unwantedActivationRule:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x000000010001d264
+ (void)extensionsWithMatchingPointName:(id)arg1 baseIdentifier:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x000000010001d1f0
+ (void)extensionsWithMatchingPointName:(id)arg1 baseIdentifier:(id)arg2 activationRule:(id)arg3 unwantedActivationRule:(id)arg4 completion:(CDUnknownBlockType)arg5;	// IMP=0x000000010001cb78
- (long long)processMode;	// IMP=0x000000010001d42c
@end

