//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface RPHardwareUtility : NSObject
{
}

+ (struct CGSize)limitRecordingWindowSizeFromSize:(struct CGSize)arg1;	// IMP=0x0000000100036994
+ (_Bool)isVoiceOverRunning;	// IMP=0x0000000100036978
+ (_Bool)supportsShutterSound;	// IMP=0x0000000100036928
+ (unsigned long long)chipId;	// IMP=0x0000000100036918
+ (_Bool)isIPad;	// IMP=0x00000001000368d0
+ (_Bool)isNativeScreenOrientationPortrait;	// IMP=0x000000010003686c

@end

