//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface GKEventTuple : NSObject
{
    unsigned long long _eventType;	// 8 = 0x8
    id _context;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x0000000100136204
@property(copy, nonatomic) id context; // @synthesize context=_context;
@property(nonatomic) unsigned long long eventType; // @synthesize eventType=_eventType;

@end

