//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface GKIMToolController : NSObject
{
    unsigned int _caps;	// 8 = 0x8
}

+ (id)sharedInstance;	// IMP=0x000000010008132c
- (void)removeListenerCapabilities:(unsigned int)arg1;	// IMP=0x00000001000815c4
- (void)addListenerCapabilities:(unsigned int)arg1;	// IMP=0x0000000100081518
- (void)disconnect;	// IMP=0x00000001000814e4
- (void)connect;	// IMP=0x0000000100081438
- (void)daemonConnectionLost;	// IMP=0x0000000100081434
- (void)daemonControllerDidDisconnect;	// IMP=0x0000000100081430
- (void)daemonControllerDidConnect;	// IMP=0x000000010008142c
- (void)daemonControllerWillConnect;	// IMP=0x0000000100081400
- (id)init;	// IMP=0x0000000100081360

@end

