//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GKInternalRepresentation.h"

@class NSDictionary, NSString;

@interface GKLeaderboardSetInternal : GKInternalRepresentation
{
    NSString *_identifier;	// 8 = 0x8
    NSString *_groupIdentifier;	// 16 = 0x10
    NSString *_title;	// 24 = 0x18
    NSDictionary *_leaderboardIdentifiers;	// 32 = 0x20
    NSDictionary *_icons;	// 40 = 0x28
}

+ (id)secureCodedPropertyKeys;	// IMP=0x00000001001250c4
- (void).cxx_destruct;	// IMP=0x00000001001254a8
@property(retain, nonatomic) NSDictionary *icons; // @synthesize icons=_icons;
@property(retain, nonatomic) NSDictionary *leaderboardIdentifiers; // @synthesize leaderboardIdentifiers=_leaderboardIdentifiers;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *groupIdentifier; // @synthesize groupIdentifier=_groupIdentifier;
@property(retain, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (unsigned long long)hash;	// IMP=0x00000001001253a8
- (_Bool)isEqual:(id)arg1;	// IMP=0x00000001001252c0
@property(retain, nonatomic) NSString *setIdentifier;

@end

