//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <CoreData/NSManagedObject.h>

@interface NSManagedObject (GKCache)
+ (id)_gkFetchRequest;	// IMP=0x000000010006d738
- (_Bool)_gkIsExpired:(id)arg1;	// IMP=0x000000010006d704
@end

