//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CCDValidationInfo.h"

@class NSArray;

@interface CCDValidationGroupInfo : CCDValidationInfo
{
    NSArray *_keyInfo;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00000001000027a0
@property(retain, nonatomic) NSArray *keyInfo; // @synthesize keyInfo=_keyInfo;
- (_Bool)validateSelfUsingValidationInfoWithDictionary:(id)arg1 resultsDictionary:(id)arg2;	// IMP=0x00000001000024fc
- (id)_mutableKeyInfoArrayFromValidationInfo:(id)arg1;	// IMP=0x0000000100002340
- (id)initWithName:(id)arg1 validationInfo:(id)arg2;	// IMP=0x0000000100002284

@end

