//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDictionary, NSObject, NSXPCConnection;
@protocol OS_dispatch_queue;

@protocol PRClientProxy <NSObject>
@property(readonly, copy) NSDictionary *clientInfo;
- (void)terminate;
- (void)activate;
- (id)initWithConnection:(NSXPCConnection *)arg1 queue:(NSObject<OS_dispatch_queue> *)arg2;
@end

