//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "PRAppStateMonitorObserver-Protocol.h"
#import "PRBLEDiscoveryConsuming-Protocol.h"
#import "PRInterruptable-Protocol.h"
#import "PRNearbyObjectUpdatesAggregatorDataSource-Protocol.h"
#import "PRRangingManagerClientRelayTarget-Protocol.h"
#import "UWBSessionServerProtocol-Protocol.h"

@class CBDeviceCache, NINearbyPeerConfiguration, NSData, NSMutableDictionary, NSString, NSUUID, NSXPCConnection, PRAppStateMonitor, PRAuthorizationManager, PRNearbyObjectUpdatesAggregator, PRSessionLifeCycleManager;
@protocol OS_dispatch_queue, PRBLEDiscoveryProviding, PRSessionActivationGuard, PRUWBServiceProviding, UWBSessionDelegateProxyProtocol;

@interface PRNearbyInteractionSession : NSObject <PRRangingManagerClientRelayTarget, PRNearbyObjectUpdatesAggregatorDataSource, PRAppStateMonitorObserver, PRBLEDiscoveryConsuming, UWBSessionServerProtocol, PRInterruptable>
{
    struct os_unfair_lock_s _lock;	// 8 = 0x8
    shared_ptr_55175bc8 _uwbClientReference;	// 16 = 0x10
    NSData *_localDiscoveryToken;	// 32 = 0x20
    PRNearbyObjectUpdatesAggregator *_aggregator;	// 40 = 0x28
    PRSessionLifeCycleManager *_lifeCycleManager;	// 48 = 0x30
    PRAppStateMonitor *_appStateMonitor;	// 56 = 0x38
    CBDeviceCache *_deviceCache;	// 64 = 0x40
    unsigned long long _ticket;	// 72 = 0x48
    struct optional<rose::RoseServiceRequest> _serviceRequest;	// 80 = 0x50
    struct optional<rose::RoseStartRangingOptions> _triggerOptions;	// 352 = 0x160
    struct unordered_map<UWBSessionInterruptionReasonInternal, UWBSessionInterruptionBookkeeping, std::__1::hash<UWBSessionInterruptionReasonInternal>, std::__1::equal_to<UWBSessionInterruptionReasonInternal>, std::__1::allocator<std::__1::pair<const UWBSessionInterruptionReasonInternal, UWBSessionInterruptionBookkeeping>>> _interruptions;	// 432 = 0x1b0
    NSMutableDictionary *_clientEntitlements;	// 472 = 0x1d8
    _Bool _sentHangupSignal;	// 480 = 0x1e0
    PRAuthorizationManager *_authManager;	// 488 = 0x1e8
    _Bool _shouldDeliverUpdates;	// 496 = 0x1f0
    int _pid;	// 500 = 0x1f4
    int _currentServiceRequestStatus;	// 504 = 0x1f8
    int _currentUWBProviderState;	// 508 = 0x1fc
    int _latestAppState;	// 512 = 0x200
    id <UWBSessionDelegateProxyProtocol> _delegate;	// 520 = 0x208
    NSXPCConnection *_connection;	// 528 = 0x210
    NSObject<OS_dispatch_queue> *_connectionQueue;	// 536 = 0x218
    NSString *_signingIdentity;	// 544 = 0x220
    NSUUID *_sessionIdentifier;	// 552 = 0x228
    id <PRBLEDiscoveryProviding> _bleProvider;	// 560 = 0x230
    id <PRUWBServiceProviding> _uwbProvider;	// 568 = 0x238
    id <PRSessionActivationGuard> _activationGuard;	// 576 = 0x240
    NINearbyPeerConfiguration *_singlePeerConfiguration;	// 584 = 0x248
    long long _latestBluetoothState;	// 592 = 0x250
}

- (id).cxx_construct;	// IMP=0x0000000100021318
- (void).cxx_destruct;	// IMP=0x0000000100021224
@property int latestAppState; // @synthesize latestAppState=_latestAppState;
@property long long latestBluetoothState; // @synthesize latestBluetoothState=_latestBluetoothState;
@property _Bool shouldDeliverUpdates; // @synthesize shouldDeliverUpdates=_shouldDeliverUpdates;
@property int currentUWBProviderState; // @synthesize currentUWBProviderState=_currentUWBProviderState;
@property int currentServiceRequestStatus; // @synthesize currentServiceRequestStatus=_currentServiceRequestStatus;
@property(retain) NINearbyPeerConfiguration *singlePeerConfiguration; // @synthesize singlePeerConfiguration=_singlePeerConfiguration;
@property(nonatomic) __weak id <PRSessionActivationGuard> activationGuard; // @synthesize activationGuard=_activationGuard;
@property(retain, nonatomic) PRAppStateMonitor *appStateMonitor; // @synthesize appStateMonitor=_appStateMonitor;
@property(retain) id <PRUWBServiceProviding> uwbProvider; // @synthesize uwbProvider=_uwbProvider;
@property(retain) id <PRBLEDiscoveryProviding> bleProvider; // @synthesize bleProvider=_bleProvider;
@property(readonly) NSUUID *sessionIdentifier; // @synthesize sessionIdentifier=_sessionIdentifier;
@property(readonly) int pid; // @synthesize pid=_pid;
@property(readonly, copy) NSString *signingIdentity; // @synthesize signingIdentity=_signingIdentity;
@property(readonly) NSObject<OS_dispatch_queue> *connectionQueue; // @synthesize connectionQueue=_connectionQueue;
@property(readonly) NSXPCConnection *connection; // @synthesize connection=_connection;
@property(retain) id <UWBSessionDelegateProxyProtocol> delegate; // @synthesize delegate=_delegate;
- (id)updatesQueue;	// IMP=0x0000000100021114
- (void)monitoredApp:(int)arg1 didChangeState:(int)arg2;	// IMP=0x0000000100020f40
- (void)_didUpdateNearbyObjects:(id)arg1;	// IMP=0x0000000100020e28
- (id)discoveryTokenFromLongUWBAddress:(unsigned long long)arg1;	// IMP=0x0000000100020c44
- (void)_handleClientAppStoppedBeingVisible;	// IMP=0x0000000100020bf4
- (void)_handleClientAppBecameVisible;	// IMP=0x0000000100020ba0
- (void)_handleBluetoothBecameUnavailable;	// IMP=0x0000000100020b70
- (void)_handleBluetoothBecameAvailable;	// IMP=0x0000000100020b0c
- (void)_handleUWBSystemError;	// IMP=0x0000000100020adc
- (void)_handleUWBSystemOffWithCause:(int)arg1;	// IMP=0x0000000100020a74
- (void)_handleUWBSystemReady;	// IMP=0x0000000100020a64
- (_Bool)_shouldInitiate:(id)arg1 peerDiscoveryToken:(id)arg2;	// IMP=0x0000000100020880
- (id)_getUWBConfig:(const struct RoseServiceRequest *)arg1;	// IMP=0x0000000100020714
- (_Bool)_validateNearbyPeerConfiguration:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100020560
- (_Bool)_validateConfiguration:(id)arg1 withError:(id *)arg2;	// IMP=0x0000000100020314
- (void)invalidate;	// IMP=0x000000010001fe24
- (void)systemStateChanged:(unsigned long long)arg1;	// IMP=0x000000010001fd88
- (void)interruptionReasonEnded:(long long)arg1 timestamp:(double)arg2;	// IMP=0x000000010001fa60
- (void)interruptSessionWithReason:(long long)arg1 timestamp:(double)arg2;	// IMP=0x000000010001f6e8
@property(readonly) duration_34584d68 nominalCycleRate;
- (void)bluetoothDidChangeState:(long long)arg1;	// IMP=0x000000010001f614
- (void)triggerRanging;	// IMP=0x000000010001f320
- (void)handleDeviceRediscovery:(id)arg1 cachedDevice:(id)arg2 shouldCache:(_Bool)arg3;	// IMP=0x000000010001f0b8
- (void)handleNewDeviceDiscovery:(id)arg1 shouldCache:(_Bool)arg2;	// IMP=0x000000010001f008
- (void)didLoseDevice:(id)arg1;	// IMP=0x000000010001ebc4
- (void)didDiscoverDevice:(id)arg1;	// IMP=0x000000010001e7dc
- (void)rangingServiceDidUpdateState:(int)arg1 cause:(int)arg2;	// IMP=0x000000010001e4d0
- (void)serviceRequestDidUpdateStatus:(struct ServiceRequestStatusUpdate)arg1;	// IMP=0x000000010001e210
- (void)didReceiveRemoteSessionData:(const struct RemoteSessionData *)arg1;	// IMP=0x000000010001df78
- (void)didReceiveSessionStartNotification:(const struct SessionStartNotification *)arg1;	// IMP=0x000000010001df74
- (void)didReceiveNewSolution:(const struct RoseSolution *)arg1;	// IMP=0x000000010001dd00
- (void)didFailWithErrorCode:(long long)arg1 errorString:(const basic_string_7c0a1c0b *)arg2;	// IMP=0x000000010001db58
- (void)_sessionCycleUpdated;	// IMP=0x000000010001da0c
- (void)_peerInactivityPeriodExceeded:(id)arg1;	// IMP=0x000000010001d804
- (id)_disableAllServicesAndReturnError;	// IMP=0x000000010001d030
- (void)_handleFailedToAddPeer;	// IMP=0x000000010001cfbc
- (id)_addPeers:(id)arg1;	// IMP=0x000000010001cdc4
- (id)_configureSymmetricalSinglePeerSession:(id)arg1;	// IMP=0x000000010001c460
- (id)_pauseAndReturnError;	// IMP=0x000000010001c428
- (void)pause:(CDUnknownBlockType)arg1;	// IMP=0x000000010001c1fc
- (void)runWithConfiguration:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x000000010001b8e0
- (void)activate:(CDUnknownBlockType)arg1;	// IMP=0x000000010001ada4
@property(readonly, copy) NSString *displayName;
- (void)queryDeviceCapabilities:(CDUnknownBlockType)arg1;	// IMP=0x000000010001abf4
- (_Bool)_supportedPlatform;	// IMP=0x000000010001ab40
- (id)_getCapabilities;	// IMP=0x000000010001a9fc
- (void)_populateClientEntitlements;	// IMP=0x000000010001a798
- (_Bool)_privilegedClient;	// IMP=0x000000010001a6e4
- (_Bool)_backgroundOperationAllowed;	// IMP=0x000000010001a630
- (id)initWithClientInfo:(const struct PRNearbyInteractionClientInfo *)arg1 connection:(id)arg2 authorizationManager:(id)arg3;	// IMP=0x000000010001a144
- (id)init;	// IMP=0x000000010001a0f8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

