//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSObject, NSString, NSXPCConnection;
@protocol OS_dispatch_queue;

@protocol PRService <NSObject>
@property(readonly) NSString *machServiceName;
- (_Bool)shouldAcceptNewConnection:(NSXPCConnection *)arg1;

@optional
+ (id)serviceWithQueue:(NSObject<OS_dispatch_queue> *)arg1;
@end

