//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface SystemDiagnosticLogAgent : NSObject
{
}

+ (_Bool)_runBlock:(CDUnknownBlockType)arg1 withTimeout:(double)arg2;	// IMP=0x00000001000096d4
+ (id)sharedInstance;	// IMP=0x00000001000070c4
- (id)stringForReqType:(long long)arg1;	// IMP=0x000000010000983c
- (_Bool)getPreferences:(const char *)arg1 withTimeout:(double)arg2;	// IMP=0x0000000100009530
- (void)writePreferenceInDomain:(id)arg1 withKey:(id)arg2 toDirectory:(const char *)arg3 currentUser:(_Bool)arg4;	// IMP=0x0000000100009258
- (id)getPreferencesforDomain:(id)arg1 withKeys:(id)arg2 currentUser:(_Bool)arg3;	// IMP=0x000000010000908c
- (void)revertToRootMode:(_Bool)arg1;	// IMP=0x0000000100009070
- (void)setUserMode:(_Bool)arg1;	// IMP=0x000000010000903c
- (_Bool)_libNotifyTaskAtLocation:(const char *)arg1 andTimeout:(long long)arg2;	// IMP=0x0000000100008f10
- (id)_memoryExceptionsTaskWithTimeout:(long long)arg1;	// IMP=0x0000000100008d98
- (id)_powerTaskWithTimeout:(long long)arg1;	// IMP=0x00000001000089a4
- (_Bool)coreCaptureTaskWithDir:(const char *)arg1 WithTimeout:(double)arg2 ofType:(int)arg3;	// IMP=0x0000000100008314
- (long long)_logItemForType:(int)arg1;	// IMP=0x00000001000082f8
- (_Bool)runningBoardTaskWithDir:(const char *)arg1 WithTimeout:(double)arg2;	// IMP=0x00000001000080f4
- (_Bool)timezoneTaskWithDir:(const char *)arg1 WithTimeout:(double)arg2;	// IMP=0x0000000100007e10
- (_Bool)batteryHealthTaskWithDir:(const char *)arg1 WithTimeout:(double)arg2;	// IMP=0x00000001000078ac
- (_Bool)batteryUITaskWithDir:(const char *)arg1 WithTimeout:(double)arg2;	// IMP=0x0000000100007630
- (_Bool)PersonalizationTaskWithDir:(const char *)arg1 WithTimeout:(double)arg2;	// IMP=0x00000001000072a4
- (_Bool)DSCSYMTaskForDir:(const char *)arg1 WithTimeout:(double)arg2;	// IMP=0x0000000100007170
- (void)processMessage:(id)arg1 replyWith:(id)arg2;	// IMP=0x0000000100007130

@end

