//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SignpostSupport/SignpostObject.h>

@interface SignpostObject (CoreAnalyticsReporting)
- (id)coreAnalyticsPayload;	// IMP=0x0000000100004ca4
- (id)signpostType;	// IMP=0x0000000100004c98
@end

