//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NPTOSyncContentProvider-Protocol.h"

@class NSString, PHFetchResult;
@protocol NPTOSyncContentProviderDelegate, OS_dispatch_queue, OS_dispatch_source;

@interface NPTOSupergreenMemoriesContentProvider : NSObject <NPTOSyncContentProvider>
{
    PHFetchResult *_assetCollections;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_workQ;	// 16 = 0x10
    NSObject<OS_dispatch_source> *_updateMemoryTimer;	// 24 = 0x18
    id <NPTOSyncContentProviderDelegate> _delegate;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x0000000100010648
@property(nonatomic) __weak id <NPTOSyncContentProviderDelegate> delegate; // @synthesize delegate=_delegate;
- (void)_invalidateContentIfNeeded;	// IMP=0x0000000100010418
- (id)_assetCollections;	// IMP=0x00000001000101ec
- (id)_defaultAssetFetchOptions;	// IMP=0x00000001000100e4
- (long long)targetForAssetCollection:(id)arg1;	// IMP=0x00000001000100dc
- (id)keyAssetsForAssetCollection:(id)arg1;	// IMP=0x000000010000ff88
- (id)assetsForAssetCollection:(id)arg1;	// IMP=0x000000010000fd64
- (id)assetCollections;	// IMP=0x000000010000fd14
- (id)initWithDevice:(id)arg1;	// IMP=0x000000010000fac4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

