//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSURL;

@interface NPTOTemporaryFile : NSObject
{
    NSURL *_URL;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0000000100022588
@property(readonly, nonatomic) NSURL *URL; // @synthesize URL=_URL;
- (void)dealloc;	// IMP=0x0000000100022504
- (id)initWithPathExtension:(id)arg1;	// IMP=0x00000001000223ac

@end

