//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CKKSGroupOperation.h"

#import "OctagonStateTransitionOperationProtocol-Protocol.h"

@class CKKSKeychainView, CKKSOperationDependencies, NSBlockOperation, NSString;
@protocol OctagonStateString;

__attribute__((visibility("hidden")))
@interface CKKSHealKeyHierarchyOperation : CKKSGroupOperation <OctagonStateTransitionOperationProtocol>
{
    NSString<OctagonStateString> *_intendedState;	// 16 = 0x10
    CKKSOperationDependencies *_deps;	// 24 = 0x18
    CKKSKeychainView *_ckks;	// 32 = 0x20
    NSString<OctagonStateString> *_nextState;	// 40 = 0x28
    NSBlockOperation *_cloudkitModifyOperationFinished;	// 48 = 0x30
}

- (void).cxx_destruct;	// IMP=0x0000000100080bb0
@property(retain) NSBlockOperation *cloudkitModifyOperationFinished; // @synthesize cloudkitModifyOperationFinished=_cloudkitModifyOperationFinished;
@property(retain) NSString<OctagonStateString> *nextState; // @synthesize nextState=_nextState;
@property __weak CKKSKeychainView *ckks; // @synthesize ckks=_ckks;
@property(retain) CKKSOperationDependencies *deps; // @synthesize deps=_deps;
@property(readonly) NSString<OctagonStateString> *intendedState; // @synthesize intendedState=_intendedState;
- (void)cancel;	// IMP=0x0000000100080aa4
- (_Bool)ensureKeyPresent:(id)arg1;	// IMP=0x00000001000805c0
- (void)groupStart;	// IMP=0x000000010008033c
- (id)initWithDependencies:(id)arg1 ckks:(id)arg2 intending:(id)arg3 errorState:(id)arg4;	// IMP=0x0000000100080228
- (id)init;	// IMP=0x0000000100080210

@end

