//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSManagedObjectContext, NSMutableDictionary, NSPersistentStoreCoordinator, NSURL;
@protocol OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface SecCDKeychain : NSObject
{
    NSURL *_persistentStoreBaseURL;	// 8 = 0x8
    NSPersistentStoreCoordinator *_persistentStoreCoordinator;	// 16 = 0x10
    NSManagedObjectContext *_managedObjectContext;	// 24 = 0x18
    NSMutableDictionary *_managedItemTypeDict;	// 32 = 0x20
    NSMutableDictionary *_itemTypeDict;	// 40 = 0x28
    _Bool _encryptDatabase;	// 48 = 0x30
    NSObject<OS_dispatch_queue> *_queue;	// 56 = 0x38
    NSArray *_classAPersistentStores;	// 64 = 0x40
}

+ (id)lookupValueTypeForObject:(id)arg1;	// IMP=0x0000000100045340
- (void).cxx_destruct;	// IMP=0x000000010003f4fc
- (id)managedItemWithItem:(id)arg1 withManagedObjectContext:(id)arg2 error:(id *)arg3;	// IMP=0x000000010003f0d0
- (id)itemTypeForItemTypeName:(id)arg1;	// IMP=0x000000010003f0c0
- (void)_registerItemTypeForTesting:(id)arg1;	// IMP=0x000000010003f02c
- (void)registerItemType:(id)arg1 withManagedObjectContext:(id)arg2;	// IMP=0x000000010003ed08
- (void)deleteItemWithPersistentID:(id)arg1 withConnection:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x000000010003ebb0
- (void)fetchItemsWithValue:(id)arg1 forLookupKey:(id)arg2 ofType:(id)arg3 withConnection:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;	// IMP=0x000000010003e9f0
- (void)fetchItemForPersistentID:(id)arg1 withConnection:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x000000010003e898
- (id)fetchManagedItemForPersistentID:(id)arg1 withManagedObjectContext:(id)arg2 error:(id *)arg3;	// IMP=0x000000010003e74c
- (void)insertItems:(id)arg1 withConnection:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x000000010003e5f4
- (_Bool)validateItemOwner:(id)arg1 withConnection:(id)arg2 withError:(id *)arg3;	// IMP=0x000000010003e300
- (id)primaryKeyNameForItemTypeName:(id)arg1;	// IMP=0x000000010003e2c8
- (void)performOnManagedObjectQueueAndWait:(CDUnknownBlockType)arg1;	// IMP=0x000000010003e248
- (void)performOnManagedObjectQueue:(CDUnknownBlockType)arg1;	// IMP=0x000000010003e17c
- (id)_queue;	// IMP=0x000000010003e174
- (void)_onQueueDropClassAPersistentStore;	// IMP=0x000000010003df9c
- (id)_onQueueGetManagedObjectContextWithError:(id *)arg1;	// IMP=0x000000010003dbe4
- (id)_onQueueGetDatabaseKeyDataWithError:(id *)arg1;	// IMP=0x000000010003d5c4
- (id)initWithStorageURL:(id)arg1 modelURL:(id)arg2 encryptDatabase:(_Bool)arg3;	// IMP=0x000000010003d3c8

@end

