//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@protocol OS_os_transaction;

__attribute__((visibility("hidden")))
@interface SecOSTransactionHolder : NSObject
{
    NSObject<OS_os_transaction> *_transaction;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x000000010001313c
@property(retain) NSObject<OS_os_transaction> *transaction; // @synthesize transaction=_transaction;
- (id)init:(id)arg1;	// IMP=0x00000001000130b0

@end

