//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "Base.h"

@interface BLER : Base
{
}

- (void)updateWithData:(id)arg1 logCode:(int)arg2;	// IMP=0x00000001000141f8
- (id)getSectionName;	// IMP=0x00000001000141ec
- (id)getLogCodeArray;	// IMP=0x000000010001418c
- (id)initWithDict:(id)arg1 codeDict:(id)arg2;	// IMP=0x00000001000140f8

@end

