//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "RDLaunchEventsDelegate-Protocol.h"
#import "SRSensorWriterDelegate-Protocol.h"

@class NSString, RDLaunchEvents, RTRoutineManager, SRSensorWriter;
@protocol OS_dispatch_queue;

@interface VisitCollector : NSObject <SRSensorWriterDelegate, RDLaunchEventsDelegate>
{
    NSObject<OS_dispatch_queue> *_queue;	// 8 = 0x8
    RDLaunchEvents *_launchEvents;	// 16 = 0x10
    SRSensorWriter *_sensorWriter;	// 24 = 0x18
    RTRoutineManager *_rtManager;	// 32 = 0x20
}

+ (void)initialize;	// IMP=0x00000001000020d0
- (void)launchEventRunActivity:(id)arg1;	// IMP=0x000000010000311c
- (void)sensorWriterDidStopMonitoring:(id)arg1;	// IMP=0x0000000100003038
- (void)sensorWriterWillStartMonitoring:(id)arg1;	// IMP=0x0000000100002ed0
- (void)dealloc;	// IMP=0x00000001000021f0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

