//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "ABMWrapperDelegate-Protocol.h"

@class MISSING_TYPE;

@interface _TtC13FTMInternal_415MetricValidator : NSObject <ABMWrapperDelegate>
{
    MISSING_TYPE *K_LTE_CDRX_CONFIG;	// 8 = 0x8
    MISSING_TYPE *K_LTE_RRC_STATE;	// 16 = 0x10
    MISSING_TYPE *K_LTE_SCELL_INFO;	// 24 = 0x18
    MISSING_TYPE *K_LTE_RLF;	// 32 = 0x20
    MISSING_TYPE *K_LTE_SEL_RESEL_INFO;	// 40 = 0x28
    MISSING_TYPE *K_LTE_SCELL_MEAS;	// 48 = 0x30
    MISSING_TYPE *K_LTE_TX_POWER;	// 56 = 0x38
    MISSING_TYPE *K_LTE_RSRP_RSRQ_SINR;	// 64 = 0x40
    MISSING_TYPE *K_LTE_COMPCARR_INFO;	// 72 = 0x48
    MISSING_TYPE *K_LTE_CA_STATUS;	// 80 = 0x50
    MISSING_TYPE *K_LTE_INTERRAT_MEAS;	// 88 = 0x58
    MISSING_TYPE *K_LTE_INTRARAT_MEAS;	// 96 = 0x60
    MISSING_TYPE *K_CELLULAR_MM_INFO;	// 104 = 0x68
    MISSING_TYPE *K_CELLULAR_ACTIVE_BEARER;	// 112 = 0x70
    MISSING_TYPE *K_LTE_EMM_CTXT;	// 120 = 0x78
    MISSING_TYPE *K_CELLULAR_MM_CTXT;	// 128 = 0x80
    MISSING_TYPE *K_CELLULAR_GMM_CTXT;	// 136 = 0x88
    MISSING_TYPE *K_UMTS_RRC_STATE;	// 144 = 0x90
    MISSING_TYPE *K_UMTS_RRC_CONFIG;	// 152 = 0x98
    MISSING_TYPE *K_UMTS_SCELL_INFO;	// 160 = 0xa0
    MISSING_TYPE *K_UMTS_SCELL_MEAS;	// 168 = 0xa8
    MISSING_TYPE *K_UMTS_TX_POWER;	// 176 = 0xb0
    MISSING_TYPE *K_UMTS_SEL_RESEL_INFO;	// 184 = 0xb8
    MISSING_TYPE *K_UMTS_NCELL_MEAS;	// 192 = 0xc0
    MISSING_TYPE *K_GSM_SCELL_INFO;	// 200 = 0xc8
    MISSING_TYPE *K_GSM_IDLE_CONFIG;	// 208 = 0xd0
    MISSING_TYPE *K_GSM_IDLE_SCELL_MEAS;	// 216 = 0xd8
    MISSING_TYPE *K_GSM_CS_RF_MEAS;	// 224 = 0xe0
    MISSING_TYPE *K_GSM_NCELL_MEAS;	// 232 = 0xe8
    MISSING_TYPE *K_GSM_GPRS_CONFIG;	// 240 = 0xf0
    MISSING_TYPE *K_SIM_FILE_INFO;	// 248 = 0xf8
    MISSING_TYPE *M_CellularLteScellInfo;	// 256 = 0x100
    MISSING_TYPE *M_CellularLteOtaMsg;	// 264 = 0x108
    MISSING_TYPE *M_CellularLteRsrpRsrqSinrHist;	// 272 = 0x110
    MISSING_TYPE *M_CellularLteRachAttempt;	// 280 = 0x118
    MISSING_TYPE *M_CellularServiceStatus;	// 288 = 0x120
    MISSING_TYPE *mySharedABMInstance;	// 296 = 0x128
    MISSING_TYPE *metricIDKey;	// 304 = 0x130
    MISSING_TYPE *payloadKey;	// 320 = 0x140
    MISSING_TYPE *profileIDKey;	// 336 = 0x150
    MISSING_TYPE *metricID;	// 352 = 0x160
    MISSING_TYPE *myLTE;	// 368 = 0x170
    MISSING_TYPE *myUMTS;	// 472 = 0x1d8
    MISSING_TYPE *myGSM;	// 544 = 0x220
    MISSING_TYPE *myCommon;	// 568 = 0x238
    MISSING_TYPE *mainDict;	// 584 = 0x248
    MISSING_TYPE *mavDict;	// 592 = 0x250
    MISSING_TYPE *myLTESCellMeasDict;	// 600 = 0x258
    MISSING_TYPE *myLTESelReselDict;	// 608 = 0x260
    MISSING_TYPE *myLTETxPowerDict;	// 616 = 0x268
    MISSING_TYPE *myLTEInterRatMeasDict;	// 624 = 0x270
    MISSING_TYPE *myLTEIntraRatMeasDict;	// 632 = 0x278
    MISSING_TYPE *myLTEEMMContextDict;	// 640 = 0x280
    MISSING_TYPE *myCellularMMCommonInfoDict;	// 648 = 0x288
    MISSING_TYPE *myCellularActiveBearerDict;	// 656 = 0x290
    MISSING_TYPE *myGMMContextDict;	// 664 = 0x298
    MISSING_TYPE *myMMContextDict;	// 672 = 0x2a0
    MISSING_TYPE *myUMTSRRCConfigDict;	// 680 = 0x2a8
    MISSING_TYPE *myUMTSCellInfoDict;	// 688 = 0x2b0
    MISSING_TYPE *myUMTSCellMeasDict;	// 696 = 0x2b8
    MISSING_TYPE *myUMTSTxPowerDict;	// 704 = 0x2c0
    MISSING_TYPE *myUMTSSelReselDict;	// 712 = 0x2c8
    MISSING_TYPE *myUMTSNbrMeasDict;	// 720 = 0x2d0
    MISSING_TYPE *myGSMScellInfoDict;	// 728 = 0x2d8
    MISSING_TYPE *myGSMIdleConfigInfoDict;	// 736 = 0x2e0
    MISSING_TYPE *myGSMIdleScellMeasDict;	// 744 = 0x2e8
    MISSING_TYPE *myGSMConnRfMeasDict;	// 752 = 0x2f0
    MISSING_TYPE *myGSMNbrMeasDict;	// 760 = 0x2f8
    MISSING_TYPE *myGSMGPRSConfigDict;	// 768 = 0x300
    MISSING_TYPE *dlbwlookup;	// 776 = 0x308
}

- (void).cxx_destruct;	// IMP=0x00000001000f979c
- (void)eventsDidUpdate:(id)arg1;	// IMP=0x00000001000eb9b0
- (void)metricsDidUpdate:(id)arg1;	// IMP=0x00000001000eb90c
- (id)init;	// IMP=0x00000001000eb8ec

@end

