//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import "NSCopying-Protocol.h"

@interface ComponentCarrierInfo : PBCodable <NSCopying>
{
    int _dlBandwidth;	// 8 = 0x8
    unsigned int _dlEarfcn;	// 12 = 0xc
    unsigned int _dlRfBand;	// 16 = 0x10
    struct {
        unsigned int dlBandwidth:1;
        unsigned int dlEarfcn:1;
        unsigned int dlRfBand:1;
    } _has;	// 20 = 0x14
}

@property(nonatomic) unsigned int dlRfBand; // @synthesize dlRfBand=_dlRfBand;
@property(nonatomic) unsigned int dlEarfcn; // @synthesize dlEarfcn=_dlEarfcn;
- (void)mergeFrom:(id)arg1;	// IMP=0x000000010005edc4
- (unsigned long long)hash;	// IMP=0x000000010005ed50
- (_Bool)isEqual:(id)arg1;	// IMP=0x000000010005ec54
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x000000010005eb94
- (void)copyTo:(id)arg1;	// IMP=0x000000010005eaf0
- (void)writeTo:(id)arg1;	// IMP=0x000000010005ea48
- (_Bool)readFrom:(id)arg1;	// IMP=0x000000010005ea40
- (id)dictionaryRepresentation;	// IMP=0x000000010005e3ac
- (id)description;	// IMP=0x000000010005e2f8
@property(nonatomic) _Bool hasDlRfBand;
- (int)StringAsDlBandwidth:(id)arg1;	// IMP=0x000000010005e198
- (id)dlBandwidthAsString:(int)arg1;	// IMP=0x000000010005e0f0
@property(nonatomic) _Bool hasDlBandwidth;
@property(nonatomic) int dlBandwidth; // @synthesize dlBandwidth=_dlBandwidth;
@property(nonatomic) _Bool hasDlEarfcn;

@end

