//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import "NSCopying-Protocol.h"

@interface EgwErrcNbrEutraMeas : PBCodable <NSCopying>
{
    unsigned int _freqBandInd;	// 8 = 0x8
    unsigned int _nbrEarfcn;	// 12 = 0xc
    unsigned int _nbrPhysCellId;	// 16 = 0x10
    int _nbrRsrp;	// 20 = 0x14
    int _nbrRsrq;	// 24 = 0x18
    struct {
        unsigned int freqBandInd:1;
        unsigned int nbrEarfcn:1;
        unsigned int nbrPhysCellId:1;
        unsigned int nbrRsrp:1;
        unsigned int nbrRsrq:1;
    } _has;	// 28 = 0x1c
}

@property(nonatomic) int nbrRsrq; // @synthesize nbrRsrq=_nbrRsrq;
@property(nonatomic) int nbrRsrp; // @synthesize nbrRsrp=_nbrRsrp;
@property(nonatomic) unsigned int freqBandInd; // @synthesize freqBandInd=_freqBandInd;
@property(nonatomic) unsigned int nbrPhysCellId; // @synthesize nbrPhysCellId=_nbrPhysCellId;
@property(nonatomic) unsigned int nbrEarfcn; // @synthesize nbrEarfcn=_nbrEarfcn;
- (void)mergeFrom:(id)arg1;	// IMP=0x00000001000d5784
- (unsigned long long)hash;	// IMP=0x00000001000d56d0
- (_Bool)isEqual:(id)arg1;	// IMP=0x00000001000d5584
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001000d5474
- (void)copyTo:(id)arg1;	// IMP=0x00000001000d5380
- (void)writeTo:(id)arg1;	// IMP=0x00000001000d5290
- (_Bool)readFrom:(id)arg1;	// IMP=0x00000001000d5288
- (id)dictionaryRepresentation;	// IMP=0x00000001000d4a54
- (id)description;	// IMP=0x00000001000d49a0
@property(nonatomic) _Bool hasNbrRsrq;
@property(nonatomic) _Bool hasNbrRsrp;
@property(nonatomic) _Bool hasFreqBandInd;
@property(nonatomic) _Bool hasNbrPhysCellId;
@property(nonatomic) _Bool hasNbrEarfcn;

@end

