//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import "NSCopying-Protocol.h"

@interface GsmCellMeasResult : PBCodable <NSCopying>
{
    unsigned int _arfcn;	// 8 = 0x8
    unsigned int _bsic;	// 12 = 0xc
    unsigned int _rxlev;	// 16 = 0x10
    CDStruct_ed0dc830 _has;	// 20 = 0x14
}

@property(nonatomic) unsigned int rxlev; // @synthesize rxlev=_rxlev;
@property(nonatomic) unsigned int bsic; // @synthesize bsic=_bsic;
@property(nonatomic) unsigned int arfcn; // @synthesize arfcn=_arfcn;
- (void)mergeFrom:(id)arg1;	// IMP=0x00000001000a91d0
- (unsigned long long)hash;	// IMP=0x00000001000a915c
- (_Bool)isEqual:(id)arg1;	// IMP=0x00000001000a9060
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001000a8fa0
- (void)copyTo:(id)arg1;	// IMP=0x00000001000a8efc
- (void)writeTo:(id)arg1;	// IMP=0x00000001000a8e54
- (_Bool)readFrom:(id)arg1;	// IMP=0x00000001000a8e4c
- (id)dictionaryRepresentation;	// IMP=0x00000001000a8838
- (id)description;	// IMP=0x00000001000a8784
@property(nonatomic) _Bool hasRxlev;
@property(nonatomic) _Bool hasBsic;
@property(nonatomic) _Bool hasArfcn;

@end

