//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class UITextView;

@interface STKClass0SMSAboutViewController : UIViewController
{
    UITextView *_aboutContentView;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0000000100004b24
- (id)formattedAboutText;	// IMP=0x000000010000479c
- (void)doneButtonTapped:(id)arg1;	// IMP=0x0000000100004788
- (void)viewDidLoad;	// IMP=0x00000001000044e0
- (_Bool)_canShowWhileLocked;	// IMP=0x00000001000044d8

@end

