//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC8coreidvd19DIPSqliteLocalStore : _TtCs12_SwiftObject
{
    MISSING_TYPE *taskQueue;	// 16 = 0x10
    MISSING_TYPE *subdir;	// 24 = 0x18
    MISSING_TYPE *dbfile;	// 40 = 0x28
    MISSING_TYPE *rawSqliteDB;	// 56 = 0x38
    MISSING_TYPE *fileManager;	// 64 = 0x40
    MISSING_TYPE *databaseFullPath;	// 72 = 0x48
}

@end

