//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class DIPage, DIVerificationSessionContext, NSDictionary, NSString;

@protocol DIVerificationServerSideProtocol <NSObject>
- (void)concludeVerification:(NSString *)arg1;
- (void)getVerificationResultWithOptions:(NSDictionary *)arg1 completion:(void (^)(NSString *, NSError *))arg2;
- (void)shareVerificationResultWithOptions:(NSDictionary *)arg1 completion:(void (^)(NSUUID *, NSError *))arg2;
- (void)performVerificationWithAttributes:(DIPage *)arg1 completion:(void (^)(DIPage *, long long, NSError *))arg2;
- (void)configure:(DIVerificationSessionContext *)arg1 completion:(void (^)(NSError *))arg2;
@end

