//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "HSPCSetupPairingViewController.h"

#import "CRCameraReaderDelegate-Protocol.h"
#import "HFItemManagerDelegate-Protocol.h"
#import "HFSetupPairingObserver-Protocol.h"
#import "HSNFCManagerDelegate-Protocol.h"

@class CRCameraReader, HFSimpleItemManager, HSNFCManager, HSSetupPairingHeaderView, NAFuture, NSObject, NSString, UILabel, UIView;
@protocol NACancelable, OS_dispatch_queue, OS_dispatch_semaphore;

@interface HSPCSetupCameraViewController : HSPCSetupPairingViewController <CRCameraReaderDelegate, HFSetupPairingObserver, HSNFCManagerDelegate, HFItemManagerDelegate>
{
    _Bool _codeScanningRequired;	// 8 = 0x8
    _Bool _cameraReaderIsRunning;	// 9 = 0x9
    HFSimpleItemManager *_itemManager;	// 16 = 0x10
    UIView *_cameraContainerView;	// 24 = 0x18
    HSSetupPairingHeaderView *_pairingHeaderView;	// 32 = 0x20
    CRCameraReader *_cameraReader;	// 40 = 0x28
    HSNFCManager *_nfcManager;	// 48 = 0x30
    NAFuture *_nfcAvailableFuture;	// 56 = 0x38
    UILabel *_interruptionLabel;	// 64 = 0x40
    NSObject<OS_dispatch_queue> *_updateActionButtonTypeSerialQueue;	// 72 = 0x48
    NSObject<OS_dispatch_semaphore> *_updateActionButtonTypeSemaphore;	// 80 = 0x50
    id <NACancelable> _delayedSetupCodeHandler;	// 88 = 0x58
    unsigned long long _mode;	// 96 = 0x60
}

- (void).cxx_destruct;	// IMP=0x000000010006fbe8
@property(nonatomic) unsigned long long mode; // @synthesize mode=_mode;
@property(retain, nonatomic) id <NACancelable> delayedSetupCodeHandler; // @synthesize delayedSetupCodeHandler=_delayedSetupCodeHandler;
@property(nonatomic) _Bool cameraReaderIsRunning; // @synthesize cameraReaderIsRunning=_cameraReaderIsRunning;
@property(retain, nonatomic) NSObject<OS_dispatch_semaphore> *updateActionButtonTypeSemaphore; // @synthesize updateActionButtonTypeSemaphore=_updateActionButtonTypeSemaphore;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *updateActionButtonTypeSerialQueue; // @synthesize updateActionButtonTypeSerialQueue=_updateActionButtonTypeSerialQueue;
@property(retain, nonatomic) UILabel *interruptionLabel; // @synthesize interruptionLabel=_interruptionLabel;
@property(retain, nonatomic) NAFuture *nfcAvailableFuture; // @synthesize nfcAvailableFuture=_nfcAvailableFuture;
@property(retain, nonatomic) HSNFCManager *nfcManager; // @synthesize nfcManager=_nfcManager;
@property(retain, nonatomic) CRCameraReader *cameraReader; // @synthesize cameraReader=_cameraReader;
@property(retain, nonatomic) HSSetupPairingHeaderView *pairingHeaderView; // @synthesize pairingHeaderView=_pairingHeaderView;
@property(retain, nonatomic) UIView *cameraContainerView; // @synthesize cameraContainerView=_cameraContainerView;
@property(retain, nonatomic) HFSimpleItemManager *itemManager; // @synthesize itemManager=_itemManager;
@property(nonatomic) _Bool codeScanningRequired; // @synthesize codeScanningRequired=_codeScanningRequired;
- (void)itemManager:(id)arg1 didUpdateResultsForSourceItem:(id)arg2;	// IMP=0x000000010006f994
- (void)pairingController:(id)arg1 didTransitionToPhase:(unsigned long long)arg2 statusTitle:(id)arg3 statusDescription:(id)arg4;	// IMP=0x000000010006f2c4
- (void)nfcManager:(id)arg1 didReadSetupResult:(id)arg2;	// IMP=0x000000010006f18c
- (_Bool)cameraReader:(id)arg1 shouldReturnQRCode:(id)arg2;	// IMP=0x000000010006f010
- (void)cameraReader:(id)arg1 didRecognizeObjects:(id)arg2;	// IMP=0x000000010006eca8
- (void)cameraReaderDidDisplayMessage:(id)arg1;	// IMP=0x000000010006eca4
- (void)cameraReaderDidFindTarget:(id)arg1;	// IMP=0x000000010006eca0
- (void)cameraReaderDidEnd:(id)arg1;	// IMP=0x000000010006eb84
- (void)cameraReaderDidCancel:(id)arg1;	// IMP=0x000000010006ea40
- (void)cameraReader:(id)arg1 didFailWithError:(id)arg2;	// IMP=0x000000010006e8d4
- (void)_handleOverrideSetupCodeIfNeeded;	// IMP=0x000000010006e50c
- (void)_updatePairingSessionForViewPresented:(_Bool)arg1;	// IMP=0x000000010006e2d8
- (void)handleSetupFailedForDiscoveredAccessory:(id)arg1;	// IMP=0x000000010006e1e4
- (void)_handleSetupURLString:(id)arg1;	// IMP=0x000000010006de30
- (void)_handleSetupCode:(id)arg1;	// IMP=0x000000010006db60
- (void)showManualCodeUI:(id)arg1;	// IMP=0x000000010006d9fc
- (void)cancel:(id)arg1;	// IMP=0x000000010006d934
- (void)_addInterruptionLabel;	// IMP=0x000000010006d3f0
- (void)_cameraWasInterrupted:(id)arg1;	// IMP=0x000000010006d278
- (long long)preferredStatusBarStyle;	// IMP=0x000000010006d270
- (void)_stopReaders;	// IMP=0x000000010006d0ec
- (void)_startReaders;	// IMP=0x000000010006cfd0
- (void)_unloadCameraReader;	// IMP=0x000000010006cd90
- (void)_loadCameraReader;	// IMP=0x000000010006c638
- (void)viewDidDisappear:(_Bool)arg1;	// IMP=0x000000010006c5b4
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x000000010006c564
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x000000010006c4a8
- (void)viewDidLoad;	// IMP=0x000000010006c30c
- (id)initWithCoordinator:(id)arg1 mode:(unsigned long long)arg2 codeScanningRequired:(_Bool)arg3;	// IMP=0x000000010006bbec

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

