//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface HSSetupStateMachine : NSObject
{
}

- (_Bool)stepRequiresIdentifyButton:(unsigned long long)arg1 withCoordinator:(id)arg2 configuration:(id)arg3;	// IMP=0x000000010000987c
- (_Bool)stepRequiresDismissalConfirmation:(unsigned long long)arg1 withCoordinator:(id)arg2 configuration:(id)arg3;	// IMP=0x0000000100009740
- (_Bool)_sync_shouldSkipStep:(unsigned long long)arg1 withConfiguration:(id)arg2;	// IMP=0x00000001000091e4
- (id)shouldSkipStep:(unsigned long long)arg1 withConfiguration:(id)arg2;	// IMP=0x0000000100009084
- (unsigned long long)stepFollowingStep:(unsigned long long)arg1 withConfiguration:(id)arg2;	// IMP=0x0000000100008c2c
- (Class)configurationObjectClass;	// IMP=0x0000000100008c20

@end

